### ISSUE TITLE
Allow wasmd to not require first CodeID to be 1

### ISSUE THREAD

**Issue by sunnya97** [CosmWasm/wasmd#10]
It's hardcoded into a bunch of tests.  Should be turned into a constant `firstCodeID`.

**Comment by alpe** [comment]
Does this issue address the initial value of the codeID sequence or the duplication in tests?
The initial CodeID can be set via [genesis](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/types/genesis.go#L26) meanwhile.

**Comment by gustavohmsilva** [comment]
Address the amount of hardcoded values distributed between the module with a non-exported const collection file. Not sure about the naming convention tho. I think although not necessary it is cool to have it still there, increase the understandability of the tests for first timers. Wanna drop it completely from the tests?

**Comment by ethanfrey** [comment]
This was @sunnya97 idea. Complaining that we start counting with 1 not 0 I think.

Maybe he can comment. But I think the improvement to test fixtures is nice. I don't see the use of making this variable in the code. Clients would also expect some behavior and will not read the go code, so standards are useful.

That said, I agree with removing any making number from the tests.
