### ISSUE TITLE
Support instantiation permission > chain permission for gov store

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1020]
> Chain permission parameters are set at Nobody for both store code and instantiation. When we try to submit a proposal to store a contract code with different instantiation config than Nobody it gives error as the permission must be subset of the Nobody permission. What I'm confused about is, since it anyways goes via a governance vote and the instantiation config is visible to the voters, why can't we directly upload with right permissions directly. Currently, it requires 2 governance proposals (one for store, one for config update) to be floated which is not ideal imo since one can also serve the same purpose. It would have made sense if we never allowed any contract to have instantiation config outside the subset of the chain config, but since we do, how does it matter that if we have 2 proposals or 1 to achieve exactly the same config. 

https://discord.com/channels/737637324434833438/737643344712171600/1017724135897579621

**Comment by vuong177** [comment]
@alpe could notional take this work?

**Comment by alpe** [comment]
@vuong177 help is always welcome 🚀 
I think it would be good to have the decision logic in the `AuthorizationPolicy` implementations but I am open for other ideas
