### ISSUE TITLE
BSR - Failure: repository has no commits

### ISSUE THREAD

**Issue by frostornge** [CosmWasm/wasmd#1023]
There's an error when i try to fetch wasmd's protobuf from `buf.build` like this
``` yaml
# buf.yaml
deps:
  - buf.build/cosmwasm/wasmd
```

``` bash
$ buf mod update
Failure: repository has no commits
```

plus. seems like actions for publish keeps aborted due to dependency issue.
https://github.com/CosmWasm/wasmd/actions/runs/3107091489/jobs/5034779022

**Comment by alpe** [comment]
Thanks for reporting! This needs to be fixed

**Comment by alpe** [comment]
@pinosu I agree! This is pending for too long already. Let's use the same approach
