### ISSUE TITLE
wasmd v0.7.1 does not working  on CentOS7

### ISSUE THREAD

**Issue by westaking** [CosmWasm/wasmd#103]
## Summary of Bug

wamsd v0.7.0  works fine. everything ok.
but, v0.7.1 does not work.

> wasmd: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jun/go/pkg/mod/github.com/confio/go-cosmwasm@v0.7.1/api/libgo_cosmwasm.so)

This is the same problem that was reported last time.
https://github.com/CosmWasm/go-cosmwasm/issues/32

## Version
wamsd  v0.7.1

## Steps to Reproduce

git checkout v0.7.1
make install
wasmd

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Sorry for the slow response, this slipped my eye.

I prepared a 0.7.2 release with centos support,  but somehow forgot to tag it. Sorry.

**Comment by ethanfrey** [comment]
Okay v0.7.2 is now released, fixes this and based on cosmos-sdk v0.38.3 for more security
