### ISSUE TITLE
CosmWasm contracts unable to withdraw rewards with authz

### ISSUE THREAD

**Issue by mikedotexe** [CosmWasm/wasmd#1031]
## Problem

When a CosmWasm contract is granted authz privileges to withdraw staking rewards on behalf of a user, there is code blocking the message from being authorized.

## Context

If I grant a smart contract the ability to withdraw on my behalf, I might execute something like this:

`junod tx authz grant juno15u274csscgyds6q65kzekm2lsze4cuujf67z344s7yrxlnfjv3gque9ly9 generic --msg-type /cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward --from mikereg --node https://rpc-juno.itastakers.com:443 --chain-id juno-1 --gas-prices 0.025ujuno --gas auto --gas-adjustment 1.3 -b block -y`

I wrote a smart contract that used protobufs as a workaround for this issue with the `/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward` message. https://github.com/CosmWasm/cosmwasm/issues/1447

This is the part where the message is getting sent:

https://github.com/mikedotexe/yieldcat-contract/blob/f4af8dcd8f12f3e76a12e546a8c332afb00fedc2/src/contract.rs#L115-L129

This returns:

<img width="666" alt="access-denied-message" src="https://user-images.githubusercontent.com/1042667/193637017-6c66e5f4-e8ce-4042-9722-a5a1ace8fc41.png">

@webmaster128 pointed out that it's here:

https://github.com/CosmWasm/wasmd/blob/v0.29.0-rc1/x/wasm/keeper/handler_plugin.go#L88-L93

Thanks for the help on this.

**Comment by jhernandezb** [comment]
The issue here is that you are trying to withdraw rewards from the granter (saved from info.sender) but in reality it should be the contract 
```diff
    let mut withdraw_msg = MsgWithdrawDelegatorReward::new();
-   withdraw_msg.delegator_address = config.granter.to_string();
+   withdraw_msg.delegator_address = info.contract.address;
    withdraw_msg.validator_address = validator_address;

```

**Comment by jhernandezb** [comment]
@mikedotexe disregard my previous comment I see the issue now, and its that you need to wrap it in a `MsgExec` or something similar
```
  let exec = MsgExec {
                grantee: env.contract.address.to_string(),
                msgs:Binary(withdraw_msg.encode_to_vec())
            };
  let exec_msg: CosmosMsg<Empty> = CosmosMsg::Stargate {
        type_url: "/cosmos.authz.v1beta1.MsgExec".to_string(),
         value: Binary(exec.encode_to_vec()),
      };
```

**Comment by alpe** [comment]
As @jhernandezb  (👏 ) pointed out, granted authorizations need to be executed via `MsgExec`. In the source code linked, you were using `MsgWithdrawDelegatorReward` which must be wrapped into [`MsgExec`](https://github.com/cosmos/cosmos-sdk/blob/v0.45.11/x/authz/spec/03_messages.md#msgexec).

**Comment by llllllluc** [comment]
@jhernandezb thanks for the above example! im also trying to use authz exec from a contract, however im trying to trigger it from javascript environment but i can't get the encoding done right, could you take a look? Thanks

```
  export const toBase64 = (obj: Object) => {
    return Buffer.from(JSON.stringify(obj)).toString("base64");
  };

  const exec = {
    "@type": "/cosmos.authz.v1beta1.MsgExec",
    type_url: "/cosmos.authz.v1beta1.MsgExec",
    grantee: warpAccountAddress,
    msgs: [
      {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        type_url: "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
        value: toBase64({
          delegator_address: myAddress,
          validator_address: testnetValidator,
        }),
      },
    ],
  };
  const executeMsg = {
    msgs: [
      {
        stargate: {
          type_url: "/cosmos.authz.v1beta1.MsgExec",
          value: toBase64(exec),
        },
      },
    ],
  };
  const contractSend = new MsgExecuteContract(myAddress, warpAccountAddress, executeMsg);

```

**Comment by llllllluc** [comment]
> @jhernandezb thanks for the above example! im also trying to use authz exec from a contract, however im trying to trigger it from javascript environment but i can't get the encoding done right, could you take a look? Thanks 🙏
> 
> warp account is a smart contract i own, i grant it permission to withdraw staking reward on behalf of me using authz, now im trying to call warp account to make it claim for me.
> 
> ```
>   export const toBase64 = (obj: Object) => {
>     return Buffer.from(JSON.stringify(obj)).toString("base64");
>   };
> 
>   const exec = {
>     "@type": "/cosmos.authz.v1beta1.MsgExec",
>     type_url: "/cosmos.authz.v1beta1.MsgExec",
>     grantee: warpAccountAddress,
>     msgs: [
>       {
>         "@type": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
>         type_url: "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward",
>         value: toBase64({
>           delegator_address: myAddress,
>           validator_address: testnetValidator,
>         }),
>       },
>     ],
>   };
>   const executeMsg = {
>     msgs: [
>       {
>         stargate: {
>           type_url: "/cosmos.authz.v1beta1.MsgExec",
>           value: toBase64(exec),
>         },
>       },
>     ],
>   };
>   const contractSend = new MsgExecuteContract(myAddress, warpAccountAddress, executeMsg);
> ```

tried `@type` and `type_url` but keep getting 
```
Code=2 Message=failed to execute message; message index: 0: dispatch: submessages: Cannot unpack proto message with type URL: /cosmos.authz.v1beta1.MsgExec: invalid CosmosMsg from the contract [CosmWasm/wasmd@v0.30.0/x/wasm/keeper/handler_plugin_encoders.go:201] With gas wanted: '50000000' and gas used: '120076'
```

**Comment by alpe** [comment]
@llllllluc this issue has been closed. Your problems seem more stargate message related, now. The encoding format is protobuf not base64. You may find better support in our [discord server](http://chat.cosmwasm.com/) smart-contract channel

**Comment by llllllluc** [comment]
> @llllllluc this issue has been closed. Your problems seem more stargate message related, now. The encoding format is protobuf not base64. You may find better support in our [discord server](http://chat.cosmwasm.com/) smart-contract channel

Thanks for pointing out, i fixed it after using proto encode, i literally searched entire github and maybe im the first one to do this from js, [this is how i did it](https://github.com/llllllluc/cosmos-examples/blob/main/src/warp/account/execute_authz_from_account.ts#L36), hope it can help future people looking at this issue.

**Comment by mikedotexe** [comment]
>i literally searched entire github and maybe im the first one to do this from js, [this is how i did it](https://github.com/llllllluc/cosmos-examples/blob/main/src/warp/account/execute_authz_from_account.ts#L36), hope it can help future people looking at this issue.

thank you for sharing!

I'd also like to share a small project I made where you include a simplified protobuf file, and it turns it into a Rust file, and then runs a script that'll do authz execute and print the JSON payload out
https://github.com/mikedotexe/prost-dot-exe
