### ISSUE TITLE
Allow gov votes to upload larger wasm bytecode

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#1038]
We currently limit the [max size for wasm to 800 KB]( https://github.com/CosmWasm/wasmd/blob/a76999a1d7c3ed3570a5f319940667a5e5b61eaf/x/wasm/types/validation.go#L15)

This is very reasonable for most contracts, but I have passed this limit when trying to embed an interpreter in a cosmwasm contract. This is a pretty unusual case, but could open interesting possibilities. wasm sizes when compiling some repos I found are around 2MB however.

A chain could raise global limit to 3MB, but that is not always desirable. To enable such use case without opening other issues, I was thinking we could use a different limit for gov contracts. Say a gov vote could upload wasm up to 4MB, while normal tx only the 800 KB limit.

Open for other approaches, but I think it would be nice to allow some way to bypass this limit when governance agrees.

@alpe I would love this on 0.30 backlog if possible, as I think it is a simple code change once we agree on an approach.

**Comment by alpe** [comment]
Good idea. The gov process makes sense to bypass these restrictions.

🤔 On the practical side, the contract has to be completed to start the process and we have some high voting gas costs. 
For unrestricted chains, a size or time based "exceed default limit"-permission granted by gov to an address would be nicer. But this would be a more complex solution

**Comment by jhernandezb** [comment]
Removing the check will allow spam proposals to submit really huge blobs.

**Comment by ethanfrey** [comment]
Hmm.. good points on gas as well as spam proposals. Will think more

**Comment by alpe** [comment]
Good point with spam proposals. The gov module will delete them when they become "inactive".

**Comment by ethanfrey** [comment]
We agreed that removing it for gov doesn't make sense, but we could raise it for gov.

There was a fear of gas price to vote on this, but with Cosmos SDK 0.47, they separate out the proposals, so you only pay for the proposal size on creating it and executing it, that will make it much more usable.

I would love to add this soon, so people can try it on testnets for larger contracts (where expensive vote cost is not an issue), preparing for a future 0.31-sdk47 release where this would be cheap enough for mainnet
