### ISSUE TITLE
it can't upload contract from ledger device address

### ISSUE THREAD

**Issue by westaking** [CosmWasm/wasmd#104]
## Summary of Bug
It works fine to upload contract from local address.
but regen.network wasmd v0.7.1 can't upload contract from ledger device.

the following error occurs.

`ERROR: [APDU_CODE_OUTPUT_BUFFER_TOO_SMALL] Authentication method blocked`

![photo_2020-03-24_16-10-14](https://user-images.githubusercontent.com/52248090/77397991-fbf27580-6de9-11ea-910e-e8b5f6dac928.jpg)

maybe.. ledger buffer problem?

## Version
regen.network wasmd v0.7.1

## Steps to Reproduce

1. build contract
2. upload contract from ledger address

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
I have not used the ledger before with the cli. Not sure how it works. I am happy for any pr to fix it,  but personally, I am putting all client effort into the js / rest client. So this will likely only get fixed if someone from the community needs it and fixes it. 

This shouldn't be anything specific to wasmd, but a general configuration for all cosmos sdk apps, so someone with experience there can hopefully help

**Comment by webmaster128** [comment]
Contract uploads are transactions with about a hundred kilobytes of data. It is unlikely that Ledger devides have the resources to process this. cc @jleni

**Comment by jleni** [comment]
Well... signing a contract is a extreme case.. there is nothing to show in the device screen... 
the user will not be sure about what it is being signed... while the client-side can say, I will send A to the device, it may send B and get the user to sign something unexpected...

Still.. as Simon said, the challenge is memory.. the limit is 8Kb today. If you need to sign blindly and that is acceptable.. some smart streaming through the device may work.. only keeping the hash state as things go through.. but again.. this breaks a bit the concept behind Ledger devices where you can have "independent review"

**Comment by jleni** [comment]
btw, there is a feature request about "arbitrary signing" that could help.. (not exactly the same) and could be prioritized ..
https://github.com/cosmos/ledger-cosmos/issues/18

**Comment by ethanfrey** [comment]
Now I get this issue... you can use the ledger for sending tokens, staking with wasmd, but the custom tx types are not supported.

I agree we do not need to support upload code with ledger (just use a temp account, uploader doesn't really matter).

But it would be nice to be able to *execute* a contract (and instantiate one) via ledger. Looking at https://github.com/cosmos/ledger-cosmos/issues/18 it seems that is non-transaction text and even that is "too experimental".  I guess we would have to fork the ledger app and leave it in dev mode to add support for cosmwasm-specific messages (does anyone support ledger with their custom modules?)

**Comment by jleni** [comment]
no, this is not correct. Custom tx types are all supported. You just don't have "friendly" names but they work and are shown correctly. Many projects are using the app with custom types.
What you cannot do is send 100K. That will not work.

**Comment by ethanfrey** [comment]
> Custom tx types are all supported. You just don't have "friendly" names but they work and are shown correctly.

Awesome. Can you send me an example or docs on how this works. I'd love to test this

**Comment by jleni** [comment]
Anything that respect this should work:
```
{
  "account_number": {number},
  "chain_id": {string},
  "fee": {
    "amount": [{"amount": {number}, "denom": {string}}, ...],
    "gas": {number}
  },
  "memo": {string},
  "msgs": [{arbitrary}],
  "sequence": {number}
}
```
https://github.com/Zondax/ledger-cosmos/blob/master/docs/TXSPEC.md#format

in `msgs` you should be able to add anything (subject to size restructions of course)

**Comment by ethanfrey** [comment]
Closing this issue, but will ensure the execute contract can be signed by ledger (in CosmJS)
