### ISSUE TITLE
x/wasm/ioutils: leaking gzip Writer inside GzipIt if a Write fails

### ISSUE THREAD

**Issue by odeke-em** [CosmWasm/wasmd#1048]
Flagged by [StaticMajor ](https://github.com/marketplace/actions/staticmajor-analyzer) from Orijtech Inc, we can see this 
```shell
$ staticmajor -resleak=true -resleak.fuzzy=true -resleak.generated=false -test=false ./...
/Users/emmanuelodeke/go/src/github.com/CosmWasm/wasmd/x/wasm/ioutils/utils.go:35:3: leaking resource created on line 32
```

per https://github.com/CosmWasm/wasmd/blob/319a9482a4b690cabe379ac3ee03880116904173/x/wasm/ioutils/utils.go#L32-L37

where on lines 34 to 35 there is a return if an error is encountered, that can be fixed by closing the writer with a separate error variable, firstly before checking the .Write error per 
```diff
diff --git a/x/wasm/ioutils/utils.go b/x/wasm/ioutils/utils.go
index 197c44c..f6d5462 100644
--- a/x/wasm/ioutils/utils.go
+++ b/x/wasm/ioutils/utils.go
@@ -31,12 +31,12 @@ func GzipIt(input []byte) ([]byte, error) {
 	var b bytes.Buffer
 	w := gzip.NewWriter(&b)
 	_, err := w.Write(input)
+	cerr := w.Close() // You must close this first to flush the bytes to the buffer.
 	if err != nil {
 		return nil, err
 	}
-	err = w.Close() // You must close this first to flush the bytes to the buffer.
-	if err != nil {
-		return nil, err
+	if cerr != nil {
+		return nil, cerr
 	}
 
 	return b.Bytes(), nil
```

Found by Quicksilver @zanicar @joe-bowman

Kindly FYI-ing @elias-orijtech @kirbyquerby @jhusdero @willpoint

**Comment by peterbourgon** [comment]
The analyzer is incorrect, as far as I can see. Failing to call Close on a gzip.Writer means that the gzipped data written to the underlying io.Writer will be invalid, but it doesn't represent any kind of resource leak. If the gzip.Writer.Write method returns an error, and you're giving up on the operation, then calling Close serves no real purpose.

**Comment by alpe** [comment]
Thanks for reporting this! I agree with @peterbourgon that this is a false positive.
When [write](https://github.com/golang/go/blob/go1.18.7/src/compress/gzip/gzip.go#L196) would fail for any reason then there is nothing [close](https://github.com/golang/go/blob/go1.18.7/src/compress/gzip/gzip.go#L229) would do.
