### ISSUE TITLE
All transactions return the same code and info

### ISSUE THREAD

**Issue by dsmello** [CosmWasm/wasmd#1059]
Hello everyone, I'm trying to create a chain based on wasmd v0.29.1, but for some reason, all my transactions always return the same info. The only thing that changed was the txhash. Does anyone know what it can be?
```
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: "
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: 66736217B674E8A0A543B673E35168DF16FE1019C47CE80DBF0BED7BDCC5C220
```

**Comment by jhernandezb** [comment]
this is because the transaction is being broadcasted in async mode meaning you only get the hash. Try querying the hash to get full tx information
```wasmd q tx [hash]```

**Comment by ethanfrey** [comment]
That is the best answer.
If you are trying to script it, it is rather annoying to wait N seconds for this, and can use `-b block` on the `wasm tx` commands to wait until it is included in a block, and then have the proper info.

**Comment by alpe** [comment]
You can find us on [discord](https://chat.cosmwasm.com/) for help as well.
