### ISSUE TITLE
Error: flag any of: flag accessed but not defined: instantiate-anyof-addresses

### ISSUE THREAD

**Issue by Sandeep-Narahari** [CosmWasm/wasmd#1078]
I am tried to deploy smartcontract on permissioned and permissionless chain using gov proposal  but facing this issue `wasmd tx gov submit-proposal wasm-store "artifacts/cw_nameservice.wasm"  --title "testing"  --description "Testing" --deposit "10000000000000stake"  --run-as $(wasmd keys show -a key1)   --from key1 --gas auto  -y --chain-id wasm-01 -b block -o json --gas-adjustment 1.5
`

Note :Using local chain to deploy
![Screenshot from 2022-11-05 18-23-38](https://user-images.githubusercontent.com/46187761/200120877-d79a7d7d-a740-45bf-a52e-41fe2a2a56bc.png)

**Comment by jhernandezb** [comment]
This is because the chain you are trying to deploy is running on 0.28, but your binary is either using main branch or 0.29, you will have to downgrade your binary.

**Comment by Sandeep-Narahari** [comment]
Could you please explain , `"This is because the chain you are trying to deploy is running on <=0.28, but your binary is either using main branch or 0.29, you will have to downgrade your binary."`   , you mean the contract which I am trying to deploy is running on <=0.28 or something else, 
I have also tried to deploy on 0.28 also but getting "no handler exists " error 
 ![Screenshot from 2022-11-06 00-54-17](https://user-images.githubusercontent.com/46187761/200137577-1a602384-dd45-4512-8195-533202929f42.png)

**Comment by ravaliGangasani** [comment]
added flag in the gov_tx file. That worked for me for wasm v0.29.1.
