### ISSUE TITLE
how to install wasmd?

### ISSUE THREAD

**Issue by morgansz** [CosmWasm/wasmd#1109]
I am learning the cosmwasm,but the fitst difficulty is how to install wasmd.

The problem is:first I run “make install” in the terminal,and there is some files downloading,and after about 10 minutes,I meet the error,the downloadings fail. the last line in the terminal is:x/wasm/types/params.go:12:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 172.217.160.113:443: i/o timeout make: *** [install] Error 1

the cosmwasm doc suggest that I should do these commands(https://docs.cosmwasm.com/docs/1.0/getting-started/installation): https://i.stack.imgur.com/QUd7o.png

the error information of the image is: (https://i.stack.imgur.com/Aislv.png) How to fix this problem? the info in the cosmwasm doc suggest me I should check my PATH and make sure it includes $HOME/go/bin

I think this problem must be related to the path,but how to modify the path to install the wasmd?

**Comment by alpe** [comment]
The error message indicates an issue with your internet connection. Just try again, when it is more stable. 
You can also do `go mod download` to download them.
