### ISSUE TITLE
Cant install wasmd

### ISSUE THREAD

**Issue by lhtpavankumar** [CosmWasm/wasmd#1115]
I have cloned  & take a checkout to v0.27.0
when i try to run make install command shows below error

`
/usr/local/go/src/runtime/mem_linux.go:20:6: sysAlloc redeclared in this block
        /usr/local/go/src/runtime/mem.go:49:6: other declaration of sysAlloc
/usr/local/go/src/runtime/mem_linux.go:39:6: sysUnused redeclared in this block
        /usr/local/go/src/runtime/mem.go:60:6: other declaration of sysUnused
/usr/local/go/src/runtime/mem_linux.go:126:6: sysUsed redeclared in this block
        /usr/local/go/src/runtime/mem.go:75:6: other declaration of sysUsed
/usr/local/go/src/runtime/mem_linux.go:151:6: sysHugePage redeclared in this block
        /usr/local/go/src/runtime/mem.go:83:6: other declaration of sysHugePage
/usr/local/go/src/runtime/mem_linux.go:167:6: sysFree redeclared in this block
        /usr/local/go/src/runtime/mem.go:100:6: other declaration of sysFree
/usr/local/go/src/runtime/mem_linux.go:172:6: sysFault redeclared in this block
        /usr/local/go/src/runtime/mem.go:115:6: other declaration of sysFault
/usr/local/go/src/runtime/mem_linux.go:176:6: sysReserve redeclared in this block
        /usr/local/go/src/runtime/mem.go:132:6: other declaration of sysReserve
/usr/local/go/src/runtime/mem_linux.go:184:6: sysMap redeclared in this block
        /usr/local/go/src/runtime/mem.go:140:6: other declaration of sysMap
/usr/local/go/src/runtime/mgclimit.go:35:17: undefined: atomic.Bool
/usr/local/go/src/runtime/malloc.go:1520:38: not enough arguments in call to sysUsed
        have (unsafe.Pointer, uintptr)
        want (unsafe.Pointer, uintptr, uintptr)
/usr/local/go/src/runtime/malloc.go:1520:38: too many errors
make: *** [Makefile:96: install] Error 2
`

can anyone help me to understand why this error raise and how to solve it

**Comment by alpe** [comment]
Can you try again with the current version `v0.30.0` ?

**Comment by alpe** [comment]
Please reopen when you have the same issues with the latest version.
