### ISSUE TITLE
Support builds without CGO 

### ISSUE THREAD

**Issue by jhernandezb** [CosmWasm/wasmd#1129]
Following https://github.com/CosmWasm/wasmvm/pull/377

I already made an initial work to try it out, LibwasmvmVersion changes won't be required as it is supported from wasmvm directly. 
https://github.com/public-awesome/wasmd/commit/cffe53fa0eeee0a9735ac2dd6d419d9d1d25eccf

We might have to wait for a wasmvm release

**Comment by faddat** [comment]
hey, @jhernandezb 

<3

**Comment by webmaster128** [comment]
@jhernandezb could you update your work and create a PR with wasmvm v1.2.0-rc.1?

**Comment by jhernandezb** [comment]
added in https://github.com/CosmWasm/wasmd/pull/1166

**Comment by alpe** [comment]
Done in #1162
