### ISSUE TITLE
Export for migration to v0.30 from v0.28 did not include "created" in wasm contract state

### ISSUE THREAD

**Issue by discoverdefiteam** [CosmWasm/wasmd#1139]
Currently having issues validating the genesis for an exported state of a network. We had briefly tested the migration steps, however did not include more db traffic (contract upload & interaction) in testing. 

Initial testing showed that migration would have to include the removal of  `"gen_msg":` , & the addition (alphebetically) of `"feeibc": {}` to the exported genesis would confirm the genesis file is valid, however with contracts instantiated, we can find the `"created": null,` param in every contract state. 

- here is a exported genesis collected by validators: 
**High Stakes Exported Genesis**:  https://transfer.sh/j9UMCP/new_genesis.json

**Comment by alpe** [comment]
Thanks for reporting. I have looked into the provided genesis and see the `"created": null` attribute value. This is causing you trouble indeed. But next would be the missing `"contract_code_history"` element for contracts. See [#1076](https://github.com/CosmWasm/wasmd/pull/1076/files#diff-d097074994dd7fbb095fde3e0a35bb24e91d653ccb122789fde9e97deb1d04d1) and the linked issue for more context.
There is no migration path provided for state dump/import chain upgrades out of the box.

Is there any reason that you can not use the [sdk/upgrade](https://github.com/cosmos/cosmos-sdk/tree/v0.45.11/x/upgrade/spec) module instead? It is a much smoother way with short downtime only (depending on your migrations).

**Comment by alpe** [comment]
Closing this now as discussion has ended
