### ISSUE TITLE
Optional flags in ProposalStoreCodeCmd are not being used

### ISSUE THREAD

**Issue by kogisin** [CosmWasm/wasmd#1140]
## Summary

In [ProposalStoreCodeCmd](https://github.com/CosmWasm/wasmd/blob/v0.29.2/x/wasm/client/cli/gov_tx.go#L20), optional flags such as `flagInstantiateByEverybody`, `flagInstantiateNobody`, `flagInstantiateByAddress`, and `flagInstantiateByAnyOfAddress` are not being used in the command. Is this intended?

## Version

v0.29.2

**Comment by alpe** [comment]
>  are not being used in the command

They are registered with the command (`wasmd tx gov submit-proposal wasm-store -h`) and read via [parseStoreCodeArgs](https://github.com/CosmWasm/wasmd/blob/v0.29.2/x/wasm/client/cli/gov_tx.go#LL31C27-L31C27) in [`parseAccessConfigFlags`](https://github.com/CosmWasm/wasmd/blob/v0.29.2/x/wasm/client/cli/tx.go#L114). I hope this answers the question. 

Please note that v0.30.0. was released already
