### ISSUE TITLE
Deploying Smart contract with multisig accout

### ISSUE THREAD

**Issue by VineeDev** [CosmWasm/wasmd#1141]
While deploying the smart contract using `multisig` account, getting error.
wasm file in genesis is 
```
"wasm": {
      "params": {
        "code_upload_access": {
          "permission": "OnlyAddress",
          "address": "wasm1fppvtvc6e4ga70ylnp2jd8u9jfvtudd82ypted"
        },
        "instantiate_default_permission": "OnlyAddress",
        "max_wasm_code_size": "1228800"
      }
    }
```
The command using to deploy the contract is 
```
simd tx wasm store cw20_base.wasm --from wasm1fppvtvc6e4ga70ylnp2jd8u9jfvtudd82ypted --chain-id testnet --gas auto --gas-adjustment 1.3 --generate-only > unsignedTx.json

```
While signing the transaction got this error
```
Error: rpc error: code = InvalidArgument desc = expected *signing.MultiSignatureData, got, *signing.SingleSignatureData: invalid request
```

**Comment by lhtvineettiwari** [comment]
hey @jhernandezb, is there any way we can remove a signer and add another signer from a `multisig` account ?

**Comment by jhernandezb** [comment]
> hey @jhernandezb, is there any way we can remove a signer and add another signer from a `multisig` account ?

cosmos multisigs don't work that way you can't add or remove signers, you will need to create a new one.

**Comment by alpe** [comment]
Thanks @jhernandezb for the help! 👍 

@lhtvineettiwari I am closing this issue now as it is not wasmd related. Feel free to reach out the the SDK team on [discord](https://discord.com/invite/cosmosnetwork) for support or on our [discord server](https://chat.cosmwasm.com/).
