### ISSUE TITLE
Remove ACCESS_TYPE_ONLY_ADDRESS?

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#1142]
Now that we have ACCESS_TYPE_ANY_OF_ADDRESSES, can we remove ACCESS_TYPE_ONLY_ADDRESS or is there any good reason to preserve that long term?

I think a migration path could look something like this (over multiple wasmd releases, multiple months):

- [ ] Disallow storing new codes with ACCESS_TYPE_ONLY_ADDRESS (hint to ACCESS_TYPE_ONLY_ADDRESSES in error message) https://github.com/CosmWasm/wasmd/issues/1144
- [ ] Create a migration that converts all ACCESS_TYPE_ONLY_ADDRESS -> ACCESS_TYPE_ONLY_ADDRESSES and `string address = 2` -> `repeated string addresses = 3`.
- [ ] Delete enum case ACCESS_TYPE_ONLY_ADDRESS and field 2 from protos

**Comment by alpe** [comment]
Thanks for the issue. There are no plans to preserve the type. It was deprecated in code already and can be removed. Your migration path makes sense 👍

**Comment by webmaster128** [comment]
Cool, I'll split the steps in small tickets such that we can do them over time.
