### ISSUE TITLE
Upgrade to cosmos-sdk proto 0.47.x

### ISSUE THREAD

**Issue by pinosu** [CosmWasm/wasmd#1148]
Bump [cosmos-sdk proto dependency](https://github.com/CosmWasm/wasmd/blob/558147d054c88840a804a3ec4e0bba5b3cb5905a/proto/buf.yaml#L10) to 0.47.x commit when available [here](https://github.com/cosmos/cosmos-sdk/blob/main/proto/README.md)

**Comment by alpe** [comment]
done
