### ISSUE TITLE
clean up `{accept,implement}_interface` in protos

### ISSUE THREAD

**Issue by pyramation** [CosmWasm/wasmd#1155]
we need to keep in sync with using full-scoped interface names in protos (already merged in cosmos-sdk)

- [reference PR](https://github.com/cosmos/cosmos-sdk/pull/14476)
- [issue describing problem](https://github.com/cosmos/cosmos-sdk/issues/14353)
- [new updated docs with required changes](https://github.com/cosmos/cosmos-sdk/blob/a0da913e86e43fd8cb1eafb49f5473e976d0b514/UPGRADING.md#acceptsimplements_interface-proto-annotations)

I can make a PR, making the issue for reference

cc @amaurym

**Comment by alpe** [comment]
This was done on the sdk v0.47 [branch](https://github.com/CosmWasm/wasmd/pull/1149/files) already which is planned to be in v0.32. Is this needed for v0.31 already?
