### ISSUE TITLE
new proto annotations 

### ISSUE THREAD

**Issue by pyramation** [CosmWasm/wasmd#1157]
We have new code upstream in the cosmos-sdk that will allows adding `option (amino.name)` to `messages` which will enable automated amino encoders, and a bunch of other codegen features. In the future will automate registration of amino interfaces as well.

[This PR](https://github.com/cosmos/cosmos-sdk/pull/13501) added amino annotations for codegen.
[This is the original issue](https://github.com/cosmos/cosmos-sdk/issues/13407)

If we don't want to take the entire PR, I suggest we at least [add this proto file](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino)

cc @faddat @amaurym

**Comment by alpe** [comment]
I had hoped to not invest more time for amino. 🙈

The amino file is available on the [buf-repo](https://buf.build/cosmos/cosmos-sdk/docs/main:amino) now.
