### ISSUE TITLE
Missing events for admin-related methods

### ISSUE THREAD

**Issue by tkxkd0159** [CosmWasm/wasmd#1173]
There seems to be no event for `setContractAdmin`, `setAccessConfig`. 
Is there any particular reason you didn't add events for these methods? Because I think this information is very important for everyone who use that contract. If not, I wanna add some events for them.

**Comment by alpe** [comment]
You are right. There should be events. I will prepare a PR so that we get this into v0.31

**Comment by tkxkd0159** [comment]
Thank you for your answer and I need to use this event for my product. So I hope to make a PR now bc it's simple things.
