### ISSUE TITLE
Trim label to prevent whitespaces

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1183]
or other non printable chars

**Comment by ruthishvitwit** [comment]
I am not able to understand the issue from the given data . Can you provide more details regarding the issue??

**Comment by alpe** [comment]
The description is not great, indeed.
This task is about preventing whitespaces in labels. This can either be done by a silent trim before it is stored in instantiate or to fail when the label != trim(label) in [ValidateLabel](https://github.com/CosmWasm/wasmd/blob/v0.40.0-rc.2/x/wasm/types/validation.go#L36).

**Comment by ruthishvitwit** [comment]
can i work on this issue??
