### ISSUE TITLE
Add REST server support for new messages

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#119]
Add support for `MsgUpgradeAdminsitrator` and `MsgMigrateContract` to `client/rest`. Also update the return value of `ContractInfo` to contain the `Administrator`.

Please put this code in a separate file as we will need to update it when merging into the cosmos-sdk 0.39-master branch.

**Comment by alpe** [comment]
How should we handle the `LastUpdated` and `PreviousCodeID` field in `ContractInfo`? The are exposed by default now.

**Comment by webmaster128** [comment]
Why are those fields strored at all? Where is this information needed?

From a transparancy perspective, I think you'd want to have a list of changes. Only exposing the most recent change seems random.

**Comment by alpe** [comment]
A full history would we best indeed. Let's have a new issue to address this proper. Adding last_id and last_updated were low hanging fruits to store some info that a contract was modified. Let's not expose them via rest for now.

**Comment by ethanfrey** [comment]
I agree, we only need to add Administrator to the rest output for ContractInfo

**Comment by ethanfrey** [comment]
Closed by #131
