### ISSUE TITLE
Wasmd breaks simulation

### ISSUE THREAD

**Issue by wojtek-coreum** [CosmWasm/wasmd#1210]
Hi,

I'm trying to run simulation tests (https://github.com/cosmos/cosmos-sdk/blob/release/v0.45.x/simapp/sim_test.go) on chain with wasmd integrated.

Test fails with this panic:

```
Block (unix) time must never be empty or negative
```

This error is produced by wasmd. Looks like that cosmos simulator produces blocks with 0 block time.

https://github.com/CosmWasm/wasmd/blob/main/x/wasm/types/types.go#L271

**Comment by alpe** [comment]
The context does not contain a proper block timestamp. As you are running SDK tests, the fix should go there. Please see our version of simulations [tests](https://github.com/CosmWasm/wasmd/blob/main/app/sim_test.go) .
