### ISSUE TITLE
Replace Tendermint with Comet BFT

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1217]
## Placeholder for future work (47)

We were following the SDK with dependencies and Tendermint versions with our defaults as a good practice.
Chain architects though can make their own decision which fork or version they want to use. The `go.mod` file can have [replacement](https://go.dev/ref/mod#go-mod-file-replace) statements for this.

## Background
* About [Tendermint](https://twitter.com/informalinc/status/1613580954383040512) 
* About [Comet BFT](https://twitter.com/informalinc/status/1620825636213526528)
* SDK 47 dev branch uses [Comet bft](https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/go.mod#L18)

## Update:
SDK v0.45.15 will contain Comet BFT

**Comment by dakom** [comment]
RIIR! ;)

**Comment by alpe** [comment]
Requires https://github.com/CosmWasm/cosmwasm/issues/1622

**Comment by alpe** [comment]
Already in #1149
