### ISSUE TITLE
Replace circleci with github actions?

### ISSUE THREAD

**Issue by gjermundgaraba** [CosmWasm/wasmd#1266]
It's a little problematic that CI runs are not visible to anyone outside of whoever (I assume Confio) is running the circleci setup. Would it be acceptable to migrate this over to GitHub actions so that us mere mortals can keep an eye on CI as well?

Edit: I of course just now saw that it is indeed open to see - so pardon me for that.
I will however keep the issue, because I still think it would be better to use GitHub actions since it is easier to see status directly in GitHub and it the standard that most other projects seem to use.

Happy to be told good reasons why I am wrong though :)

**Comment by alpe** [comment]
The CircleCI executions are visible and linked on the PR automatically, indeed. I may be biased but I don't find them hard to spot. Nevertheless, we can question previous decisions, when there some clear benefits in alternatives.

We use CircleCI first of all for historical reasons. When the original setup was copied from Cosmos-SDK, their built system was CircleCI.  Other reasons
* We can [scale](https://github.com/CosmWasm/wasmd/blob/v0.31.0/.circleci/config.yml#L121) worker instances for high hardware requirements
* Pipelines to fail fast
* Consistent with other CosmWasm projects

Please note that the 'simulations run' is quite cpu intense and takes a lot of time. Confio is paying for the CI system as we exceed the free tier. Switching to github actions must bring clear benefits. Please outline them with some data.

**Comment by gjermundgaraba** [comment]
I think the cost could be a major improvement as "GitHub Actions usage is free for standard GitHub-hosted runners in public repositories."

As a contributor, GitHub actions bring major benefits as I can run them on my own fork very easily. This is useful if I want to make any bigger changes, but especially if I want to contribute to the pipelines themselves.

The Cosmos-SDK has since moved over to GH Actions, so you could ask them about it too.

**Comment by alpe** [comment]
Thanks for the infos. I do understand your motivation better now.
 
In order to move this forward, I would still like to see some numbers on build time with github actions. Especially the simulation run.
 
Please note that github actions have a very limited free [plan](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).
We used 450 GB of storage last month on circleCI for the project with more than 5000 compute minutes for example.

**Comment by gjermundgaraba** [comment]
The limited free plan is not for public repos, for this repo those limits would not be there. "GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. **For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners**, depending on the product used with the account. Any usage beyond the included amounts is controlled by spending limits."

So you should be able to run it all for free.

As for the build times, nothing is easier to provide :)
Here are the simulations that the Cosmos SDK run every 2 hours: https://github.com/cosmos/cosmos-sdk/actions/workflows/sims.yml

You can break it down to see the length of each task as well: 
![image](https://user-images.githubusercontent.com/1344105/225591686-57410d7b-4405-410a-b238-714d88bc27f0.png)

We have one too, but it includes the long running sim so takes longer: https://github.com/EmpowerPlastic/empowerchain/actions/runs/4433742359

Here is a build pipeline: https://github.com/EmpowerPlastic/empowerchain/actions/workflows/chain_build.yml

You can go through the github actions for the SDK as they are pretty standard. We have a slightly specialized setup with Empower using Earthly (with dind) to run everything.

**Comment by alpe** [comment]
Thanks for the infos! Do you want to provide a PR so that we can see the build, test + sim runs for wasmd?

**Comment by gjermundgaraba** [comment]
@alpe demo PR: https://github.com/CosmWasm/wasmd/pull/1347
