### ISSUE TITLE
How can people find Notional's SDK v0.46 branch

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1267]
There should be a way for people to find the [branch](https://github.com/CosmWasm/wasmd/pull/1126), get in contact with the maintainers and understand their future plans and commitment. 

Some ideas:
* We can have a `sdk46_readme.md` in the project root
* or a GH issue open that Notional maintains and link to their resources
* or an article by Notional on https://medium.com/cosmwasm

Other ideas are very welcome! 
Maintaining a branch on this repo is not a good option. It may set expectations on quality, ownership and support by the core team, which is not given.

For some context, see 
* https://github.com/CosmWasm/wasmd/issues/927
* https://github.com/CosmWasm/wasmd/issues/941

**Comment by gjermundgaraba** [comment]
How about a pinned issue called "Community-maintained forks/branches"? Or a more specific title to lead anyone looking for a 46 solution? It could also be linked directly in the Readme to be easier to find.

**Comment by alpe** [comment]
There is a questions on [discord](https://discord.com/channels/737637324434833438/1016389766033457253/1087999589442912266) now with a SDK ticket linked. It would be good to help people with more information. If we can link to some external resource that would be great. Some example questions that come to my mind:

- (Why does this fork exists? - Motivation)
- Where can I get some specific or latest versions?
- How can I get support or help?
- What are the future plans and commitment? (features, upgrades, security fixes)
- Who owns the fork (is this Notional or other community members, too)?

@faddat can you own this task, please?

**Comment by alpe** [comment]
@faddat a gentle reminder to own this task

**Comment by alpe** [comment]
Thanks for the updates. Very much appreciated!
