### ISSUE TITLE
Update to latest (early June) cosmos sdk dependency

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#128]
## Summary

Based on #127 
Once we have 0.8 working on a recent cosmos sdk, let's update the sdk to the most recent version published. More or less what is being used in GoZ.

TODO:
- [ ] Update Cosmos SDK deps
- [ ] Ensure IBC commands work like in GoZ examples (set up in app.go, manual testing via cli)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alpe** [comment]
The SDK was tagged for GoZ with the [goz-phase-3 label](https://github.com/cosmos/cosmos-sdk/tree/goz-phase-3)

**Comment by ethanfrey** [comment]
That seems like a fair one to pin to for now. Thanks for the good eye here, and please use that tag for this issue.

I will have to pull this forward when I start messing more with IBC, but nice to have a stable target.

**Comment by ethanfrey** [comment]
Closed by #138
