### ISSUE TITLE
Return non redacted error content on IBC packet recv

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1289]
Current response in json is: `{"error":"ABCI code: 5: error handling packet: see events for details"}`
Instead of the default error constructor, we could pass the string directly

Note: Only for this case: https://github.com/CosmWasm/wasmd/blob/v0.31.0/x/wasm/keeper/relay.go#L135-L136

See also #1220

**Comment by alpe** [comment]
Does it make sense to prevent empty error strings? Technically it is not an issue and would save some gas for the relayer.

**Comment by 0xekez** [comment]
this would be a really nice feature 🙏
