### ISSUE TITLE
Full history of contract code migrations

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#130]
## Summary
Contracts can be migrated to different code versions. A full history of the changes would be helpful for audits and debugging issues.

## Problem Definition
Follow up from [comment](https://github.com/CosmWasm/wasmd/issues/119#issuecomment-638729015)

## Proposal
Mandatory data would be `codeID` and `AbsoluteTxPosition` for each migration
This data should be available via rest/ cli as an ordered list.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Sounds good. Let's do it for 0.9

**Comment by alpe** [comment]
As we currently store the `init_msg` with the codeInfo It may make sense to store the `migrate_msg` with this history

**Comment by ethanfrey** [comment]
> As we currently store the init_msg with the codeInfo It may make sense to store the migrate_msg with this history

You mean [with the `ContractInfo`](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/types/types.go#L40-L49)?

But yes, I agree, adding an array in the same `ContractInfo` struct seems like a fine solution as long as we can assume there will never be more than 10 or 20 migrations on a contract. I guess it just means each migration makes the contract more expensive to load.

I would go for this simple solution now and you can add a TODO issue to see about making this more performant if the information rarely needs to be read.

**Comment by ethanfrey** [comment]
@alpe it seems you are close to finishing up all the gov stuff :tada: 

If you feel blocked some day, you could also tackle this one for the release.
