### ISSUE TITLE
Getting "failed to execute message; message index: 0: exceeds limit: create wasm contract failed" on a cw721_base contract

### ISSUE THREAD

**Issue by xmichael446** [CosmWasm/wasmd#1342]
Hi there! I've compiled the cw721_base contract from the cw-nfts repository and I've been trying to upload it to the blockchain (my own, on cosmos sdk). I don't think I have any problems with the chain itself coz I've been able to successfully upload other contracts (nameservice, escrow). The error message I'm getting is very strange: `"failed to execute message; message index: 0: exceeds limit: create wasm contract failed"`. Would be grateful if you guys could somehow assist.

**Comment by alpe** [comment]
Fixed in both branches
