### ISSUE TITLE
Nolus protocol actively utilized wasm genesis messages

### ISSUE THREAD

**Issue by Lockwarr** [CosmWasm/wasmd#1346]
We noticed that in v0.31.0[ the functionality to add genesis messages has been removed. ](https://github.com/CosmWasm/wasmd/issues/987)

Our system was relying on storing/instantiating contracts in the genesis, since we wanted to start our chain with a set of contracts. Could this cli command be returned in next releases? We build an app chain where we run the application right from the genesis. Is there an alternative way to achieve it?

cc @ethanfrey @alpe

**Comment by alpe** [comment]
Sorry to hear that you were still using them. We deprecated the genesis messages and finally removed them. They were a very complex block of code for some very limited functionality.
 
My recommendation would be to follow the example of the tgrade [poe module](https://github.com/confio/tgrade/blob/main/x/poe/bootstrap.go). This gives you much better control
