### ISSUE TITLE
Replace `json.RawMessage` in ContractInfo and Messages

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#145]
## Summary
To discuss (again):
- Should ContractInfo InitMsg be exported as `[]byte` instead of raw json?

We do allow raw json in instanciate and migrate Messages currently. So I assume we don't get invalid json into the system currently. Though the fuzz test (#142) is not that smart so I ran into this "issue" and thought it would be good to bring it up again. I know contracts run with json currently but there is some potential to drop this constraint easily in wasmd by using bytes. This could be a first step to protobuf. We should leave the interpretation of the messages to the wasm code and their devs.
I assume this has effects on the client code as well....

## Proposal

Replace `json.RawMessage` in ContractInfo and Messages
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
We can change those, but for 1.0 we are sticking with JSON-only and this does improve the UX (and do some basic sanity checks) for this case. We just added that in 0.7 I believe (or 0.6?) and I would like to keep it. 

When we do support other non-JSON encodings in the contracts, we should definitely update this, but for now, I don't think this is useful for production. For fuzzing... maybe you can generate valid JSON - either with correct schema or incorrect schema?

**Comment by ethanfrey** [comment]
We can close this right? As we are enforcing JSON-only messages and queries for the time being.

@webmaster128 @alpe

**Comment by webmaster128** [comment]
From my point of view, JSON is set for any client-facing communication for the forseeable future. Changing this has significant drawbacks and the only good reason to change it would be gas consumption in the contract.

**Comment by ethanfrey** [comment]
Good, then let's just keep it consistent in the whole stack.

We can revisit this when working on 2.0
