### ISSUE TITLE
How to use UpdateContractAdmin proposal

### ISSUE THREAD

**Issue by JoowonYun** [CosmWasm/wasmd#1452]
I have a question about the process of looking at the `UpdateContractAdmin` proposal process.

In proposal_handler, caller is nil. So it seems that the condition of CanModifyContract below cannot be satisfied.

https://github.com/CosmWasm/wasmd/blob/a4548ba17526027ced9cfd3fe783c4d66831f9e4/x/wasm/keeper/proposal_handler.go#LL286C18-L286C18

https://github.com/CosmWasm/wasmd/blob/a4548ba17526027ced9cfd3fe783c4d66831f9e4/x/wasm/keeper/keeper.go#LL603C17-L603C17

https://github.com/CosmWasm/wasmd/blob/a4548ba17526027ced9cfd3fe783c4d66831f9e4/x/wasm/keeper/authz_policy.go#LL39C2-L39C2

Did you want to override and use the new ContractKeeper?

**Comment by alpe** [comment]
For gov proposals the [GovAuthorizationPolicy](https://github.com/CosmWasm/wasmd/blob/a4548ba17526027ced9cfd3fe783c4d66831f9e4/x/wasm/keeper/authz_policy.go#L58) is used. It is selected in the [msg_server](https://github.com/CosmWasm/wasmd/blob/a4548ba17526027ced9cfd3fe783c4d66831f9e4/x/wasm/keeper/msg_server.go#L183).
I hope this answers the question.
