### ISSUE TITLE
Using custom any resolver to `StargateQuerier`

### ISSUE THREAD

**Issue by dadamu** [CosmWasm/wasmd#1454]
## Context

Currently `StargateQuerier` is using default any resolver provided by codec.Codec, which unpacks `Any` type to the underlying structure then builds the JSON message for wasmvm. That makes parsing the proto message difficult since parsing underlying structure into `Any` requires a custom decoder inside contract. 

The definition of default codec any resolver can be traced here:
https://github.com/cosmos/cosmos-sdk/blob/13e61bd0c5c7950d137bbdfb171f95d87179ed29/codec/proto_codec.go#L148
https://github.com/cosmos/cosmos-sdk/blob/13e61bd0c5c7950d137bbdfb171f95d87179ed29/codec/json.go#L16

For example, Desmos profiles is a `Any` proto message, the json pass to wasmvm is:
```json
{
    "@type": "/desmos.profiles.v3.Profile",
    "dtag": "abc",
    "nickname": "abc",
    "bio": "abc",
    ...other fields
}
``` 
Instead of a `Any` JSON can be easily deserialized
```json
{
    "@type": "/desmos.profiles.v3.Profile",
    "value": "<bas64 encoded of desmos Profile>"
}
```

As a result, it is not easy to deserialize the `Any` structure in Rust like:
```rust
pub struct Any {
     #[prost(string, tag = "1")]
    pub type_url: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}

impl<'de> Deserialize<'de> for Any {
   fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
       logic of deserialize the JSON into Any
    }
}
```

## Solution

The solution can be implementing a custom any resolver to unpack to `Any` JSON without underlying structure, it would be like the following commit, then the `Any` deserialization will be easy in contract side:
https://github.com/desmos-labs/wasmd/commit/b7700dfcc403b58c9702f0c45f4016b9668a287e

What do you think? I can create a pull request if you think it is worth to do.

**Edited: 05:00 UTC +0, June 20, 2023**

**Comment by webmaster128** [comment]
> Instead of a proper any JSON format like

This is only a smaller point of the whole problem, but please note that in https://protobuf.dev/programming-guides/proto3/#json the flattening of the `Any` is specified. This might not be the best way to use it in a contract, but is correct from the standardization point of view.

**Comment by dadamu** [comment]
@webmaster128 Thanks for the reference! I see and fixed the content.

**Comment by alpe** [comment]
Changing the response encoding would be a breaking change for existing contracts. We can not simply do this without a lot of communication and coordination work. I do see your use case but the query plugin provides an extension point to set your own Stargate query handler and use that with your community. Our default is `RejectStargateQuerier` currently.

The `AcceptListStargateQuerier` accepts any `codec.Codec` implementation. Why not use this to wrap your logic with a custom `MarshalJSON` implementation that makes use of your `WasmAnyResolver`. Simple, testable and no need to fork. 
WDYT?

**Comment by dadamu** [comment]
@alpe I think it the best solution for my usecase. Thanks for the wonderful solution!
