### ISSUE TITLE
Invalid Request: error reading request body: http: request body too large

### ISSUE THREAD

**Issue by 99Kies** [CosmWasm/wasmd#1478]
this is my wasmd config:

<img width="739" alt="image" src="https://github.com/CosmWasm/wasmd/assets/45918704/a1656eb3-18e6-4eae-a3ff-524735b097e3">

and I use this command to  compile my wasm contract:
```
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer-arm64:0.12.11

```

this is my file:

![image](https://github.com/CosmWasm/wasmd/assets/45918704/c2dfecd2-1e48-4f8b-bb66-ed66064522cf)

this is my store command:

```bash
wasmd tx wasm store ./artifacts/xxx-aarch64.wasm --from wallet --node http://xxxx:26657 --chain-id "xxx-testnet" --fees 10token --gas auto --gas-adjustment 1.1
```

this is my log:

```shell
Error: RPC error -32600 - Invalid Request: error reading request body: http: request body too large
```

**Comment by alpe** [comment]
The contract file size exceeds the chain limit. Not sure if you are the same person but I had answered this here:
https://discord.com/channels/737637324434833438/737640672680607764/1125452849787195392

As you are using the rust-optimize already, you may need to separate some logic into a new contract and call it via submessages

**Comment by alpe** [comment]
I am closing this now. Please feel free to follow up here or on discord
