### ISSUE TITLE
System tests to cover chain upgraded

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1480]
Our current system tests or integration tests do not cover migration of legacy state to the current version. This is a blind spot that was covered by community testnets and their feedback.
Unfortunately that had become a bottleneck that we need to automate and own in the project.

The system tests setup a multi node environment easily that can be used for this, now.

Preconditions:
- [x]  published artifacts of the previous version(s)
- [x] a contract for smoke tests that has data persisted, supports a smart query and can trigger a message
- [ ] a rich state dump that seed the chain (ideally coming from some production environment)

The chain upgrade test would then:
- start a multi node chain with an older version and the seed state from the dump
- submit an upgrade proposal to the current version and vote yes (voting period must be reduced/ or instant proposal type in SDK 50)
- halt the chain when upgrade height is reached
- replace the binary used with the current version
- do some smoke tests to ensure system is still healthy

**Comment by Reecepbcups** [comment]
@alpe I'm happy to take this on if you all are okay with using Strangelove's interchain test?

https://github.com/strangelove-ventures/interchaintest

**Comment by Anmol1696** [comment]
I think there can be a couple of ways to achieve this.

1. Remote docker containers. We can use the CI to trigger spinning up the infra, or multi-node docker containers in a remote k8s cluster, and then run tests against the setup to perform the chain upgrades or multi-node tests. This is something [Starship](http://starship.cosmology.tech) is capable and built for.
2. Bring in the same paradigms of docker based upgrade testing directly as a system test as you mention. The idea here would be, we use something like cosmovisor to run the genesis chains and have the upgrade binaries in upgrade dirs, and have the system controller run and trigger upgrades.
3. Just do it ourselves directly in the system test runner without cosmovisor. We could just call the upgrade keepers if we have access to App itself.

If you wouldn't mind, I can try out both the approaches too. It would be really nice to be able to have system tests be run against and actual e2e testing framework, both InterchainTest and Starship.

**Comment by alpe** [comment]
Thanks @Anmol1696 for your thoughts and proposals!
I would prefer if we can focus on option 3) to have a slim setup. No need for cosmovisor as we can fully control the nodes from Go. There may be some updates required to the `system.go` but it should not be too complicated to stop a chain on some height and restart it with a new binary. 
The system tests do not have access to the upgrade keeper. Everything has to go through the system as black box. Therefore some modifications to the gov setup in genesis would be required for short voting periods.

**Comment by Anmol1696** [comment]
Yup that would make sense. Could we define the scope of the system test though?
You need multi-node, upgradeable system tests. I will be working on something very similar for Starship as well, so maybe I can have a look at this. What is the priority and timeline for this?

I think you are right about flaky docker setups, even with Starship local testing, docker and k8s both seem to be an overkill. But I think we should be careful to limit the scope, so that other e2e frameworks can take over from the limits of this system.

**Comment by Reecepbcups** [comment]
yea this is exactly what we do for Juno with ictest already. Only would have to add a genesisDump() method at the end and add contract executes & wasmd cli queries

if you guys change your mind (from System go) just let me know :)

https://github.com/CosmosContracts/juno/blob/main/interchaintest/chain_upgrade_test.go

**Comment by alpe** [comment]
Testing a chain upgrade from a rich state dump is still open. The problem here is to stay vendor neutral and storing the dump. Chains should have their own tooling in place to verify their migrations. 
Nevertheless, we can revisit this when we have another wasmd testnet.
