### ISSUE TITLE
Announcement: End of life for v0.3x series

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1578]
We are planning to do a last v0.34 release with some bugfixes but not backport new features or upgrade wasmvm to v1.4+. This may become inconvenient but our core dependencies are end of life, too.

> The Cosmos SDK v0.45.x line has reached end-of-life since v0.45.15. This is an exceptional security release according to our [release policy](https://github.com/cosmos/cosmos-sdk/blob/2262199/RELEASE_PROCESS.md#major-release-maintenance).

https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.16

> End of Life Date: v4.4.x | October 31, 2023

https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#stable-release-policy

**Comment by webmaster128** [comment]
See https://github.com/CosmWasm/wasmd/compare/v0.33.0...releases/v0.3x for the latest changes contained in 0.34.0
