### ISSUE TITLE
Custom StoreCode Authorization for authz module

### ISSUE THREAD

**Issue by jhernandezb** [CosmWasm/wasmd#1584]
Currently signing store code transactions with multisigs can only be done if you use non-ledger keys due to the memory limit on such devices it makes impossible for signers and for this reason I think it would be very useful to have a contract upload authorization for authz. 

- Authorize grantee to upload any contract (although this can already be achieved by the generic grant authorization)
- Authorize grantee to upload any contract from a list of given hashes  so the granter can verify and be confident the grantee only uploads pre-approved contracts, 

This can even  be useful for DAOs or CW4 multisigs giving access to an uploader by creating a custom authorization.

**Comment by alpe** [comment]
This is a good idea!
Would it make sense to have the same for migration?

On store code, an instantiateAccess configuration can be set. Is this something that you want to ensure by the grant as well?   I does not seem required but I want to bring this up.

**Comment by jhernandezb** [comment]
I don't see migration being necessary but would see it as a nice to have.

On instantiate access now that you bring it up might makes a lot of sense to limit it to a specific config per code hash
```
hash1 -> AnyOfAddress(address1)
hash2 -> EveryBody
```

**Comment by jhernandezb** [comment]
Perhaps same for admin?  NoAdmin/SpecificAddress ?
