### ISSUE TITLE
Merge 0.9.0 into sdk 0.39 tracking branch

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#159]
There were some changes between the 0.9.0-alpha version that will need to be adjusted, notably splitting out clear-admin from update-admin

**Comment by ethanfrey** [comment]
This was done, right @alpe ?

Actually, I am not sure what the difference between these two PRs is:
* #172 
* #146 

Best to finish up the governance stuff first anyway before touching stargate, but curious where things stand there

**Comment by alpe** [comment]
ja, 0.9.1 was merged in #172

**Comment by ethanfrey** [comment]
Good. And I closed #146 to avoid more confusion
