### ISSUE TITLE
Make contract lable updatable

### ISSUE THREAD

**Issue by oldremez** [CosmWasm/wasmd#1601]
Currently, the admin of a contract is able to migrate the contract (i.e. change the code), and change or remove the admin but isn't able to change the contract's label. 

From a theoretical point of view, it just looks a bit strange (for me) that the only things that can't be changed by the admin are the address (which is obvious) and the label of the contract. While an address is essentially the thing that defines the contract instance the label is just metadata that is carved in stone while even the code/admin can be changed (thus the purpose of the contract can be changed which might make the initial label misleading).

From the practical point of view, Neutron organized DAO contracts with the hierarchical naming convention that helps with e.g. querying the contracts from the chain. Since labels aren't editable any mistake made is going to be preserved and there's no way to update the convention (even while DAO is the admin of those contracts).

I propose to consider making contract labels updatable by the contract's admin.

**Comment by alpe** [comment]
Thanks for bringing attention to this and sharing your use case!
Would it make more sense for your use cases to updated with the migration or should it be a separate message?

**Comment by webmaster128** [comment]
I support this request. I don't know any reason why a label should be immutable. Especially for long living contract addresses this can become important. E.g. when handing a smart wallet from one organization to another.

I'd implement this as a separate message as you might want to change the label without chaning code.

Overall I think it's great to encourage nicely maintained labels which incentivises UIs to display them prominently.

**Comment by oldremez** [comment]
Agree with @webmaster128 that it will be better to be done as a separate message.
