### ISSUE TITLE
feat(fuzz): provide example to generate arbitrary and yet correct CW modules

### ISSUE THREAD

**Issue by dzmitry-lahoda** [CosmWasm/wasmd#1615]
We fuzzied alternative impl of CW, but where able to fuzz only store code via wasm_smith::Module.

https://github.com/ComposableFi/composable/pull/4125/files

I was run tool for dozen of hours, never got to module which is CW module (sure, export names are impossible to guess).

So some generator example CW module, and yet random could be awesome. With all combination if possible exports and random CW function bodies. 

I can port it to rust after.

Alternative generate it directly in Rust, not in Go keeper.

I asked issue here only because found other fuzz usage in keeper.

**Comment by alpe** [comment]
I am not sure if I understand you correct. What are you trying to do and how can we help?

The fuzzer code in wasmd is used to have a richer variety of data for i/o data. There is also the [simulation package](https://github.com/CosmWasm/wasmd/tree/v0.41.0/x/wasm/simulation) that integrates with the cosmos-sdk fuzzer to provide random data.

**Comment by dzmitry-lahoda** [comment]
i have not found the code which simulates arbitrary wasm modules which are compatible with wasm specification of cw host, fully or deloberately partial. i see it loads very specific contract. 

https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-smith#with-cargo-fuzz-and-libfuzzer-sys

so something like CwCorrectWithIbcAndIterarorsModule or CwBadFunctionParametersModule

**Comment by dzmitry-lahoda** [comment]
as soon i will have cw module generator, i can use json module generator to validate entry points jsons. https://docs.rs/arbitrary-json/latest/arbitrary_json/

**Comment by alpe** [comment]
We don't generate arbitrary wasm contracts for testing. I don't know any project which does this.
Maybe @webmaster128 can help when he is back but this is off scope of this project. 

I will keep this issue open for a week to let people find it and comment.

**Comment by dzmitry-lahoda** [comment]
so how project going to fuzz? except using some predefined contract, but that would be more of testing the contract, less contract host interaction.

**Comment by alpe** [comment]
If there are more questions, feel free to reach out. Closing this now
