### ISSUE TITLE
Create Governance Proposals for Contract Lifecycle

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#162]
## Summary

We wish to allow the chain governance to "act as root" on all contracts in the system. It can execute any privileged operation on any contract. To allow this to happen, we must define some new governance proposals that can perform the required actions, before potentially restricting them to other users in follow-up PRs.

The decision to allow governance control should be optional and configured by each chain at compile time. 

## Problem Definition

See #161 for the larger discussion.

You should consider the hub governance as root.  If you do not want this, then disable those governance proposal types in the binary, so the governance oversight / backdoor (depending on your view) doesn't exist. This means that governance can migrate/burn a contract even if it is marked "immutable". We will add at least three new proposal "content" types. The basics would be UploadCodeProposal, InstantiateContractProposal, MigrateContractProposal. We would also likely want to add an UpdateAdministratorProposal, as hub governance may not want to migrate directly but appoint a new committee as administrator to some contested contract after the instantiation (or change the committee responsible).

## Proposal

Add 5 new proposal types that mirror the 5 messages (besides Execute) that exist in the `x/wasm` module:

These two act like normal messages, except they can never be prohibited (that will be added in future PRs):

* `StoreCodeProposal` == `MsgStoreCode`
* `InstantiateContractProposal` == `MsgInstantiateContract`

These act like the normal message "as root", meaning they always succeed, regardless of who is set as "Admin" on the contracts:

* `MigrateContractProposal` ~ `MsgMigrateContract` 
* `UpdateAdminProposal` ~ `MsgUpdateAdmin`
* `ClearAdminProposal` ~ `MsgClearAdmin`

~~When compiling a chain, you should be able to enable None of these, All of these, or Some of these. By default, none of the proposal types are enabled. There should be one function to easily register all proposals with the application. And there should be another function (or functions) that can be used to selectively enable some of these. The last 3 - `MigrateContract`, `UpdateAdmin`, `ClearAdmin` can all be enabled/disabled as a block, as giving access to governance to do one is close to giving access to all.~~ (moved as a separate task into #175 )
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alpe** [comment]
* For CodeInfo we have a `creator` field.  Should this be passed via StoreCodeProposal content? Same for `InstantiateContractProposal`
* Do we want to expose the same wasm events as with regular calls?

The configuration to enable/disable proposal types feels like a non trivial task with the current app constructor. Can we move this to a new ticket? I would like to get the permission system setup first.

**Comment by ethanfrey** [comment]
For the first 2 questions- yes, sounds good.

> The configuration to enable/disable proposal types feels like a non trivial task with the current app constructor. Can we move this to a new ticket? I would like to get the permission system setup first

That can move into a new ticket. Can you create it and link it?
