### ISSUE TITLE
Can the --allowed-messages in this feegrant be set to the specified contract address?

### ISSUE THREAD

**Issue by 99Kies** [CosmWasm/wasmd#1654]
![image](https://github.com/CosmWasm/cosmwasm/assets/45918704/0b43d6bf-850e-47f3-abac-95fbacc97d3f)

Can the `--allowed-messages` in this `feegrant` be set to the specified `contract address`? 

I want dapp user to be able to use money from my account for `gas fee` when they can use my `contract`.

https://github.com/CosmWasm/cosmwasm/issues/1738

**Comment by alpe** [comment]
This feature request makes sense. Let's follow up in  https://github.com/CosmWasm/wasmd/issues/1571. I will close this as duplicate
