### ISSUE TITLE
OnChanOpenInit Implementation may not follow IBCModule docs

### ISSUE THREAD

**Issue by chipshort** [CosmWasm/wasmd#1693]
Maybe this is not relevant in practice, but it seems to me that [our implementation of OnChanOpenInit](https://github.com/CosmWasm/wasmd/blob/606289ab56dbe803bc28941a4b4c361b26435d37/x/wasm/ibc.go#L40) doesn't uphold the contract specified in the [doc comment of the IBCModule
](https://github.com/cosmos/ibc-go/blob/9c7212198d0ef82b8219ea66cee9c96b40e7981d/modules/core/05-port/types/module.go#L23-L24):
> If the version string is empty, OnChanOpenInit is expected to
return a default version string representing the version(s) it supports.
If there is no default version string for the application,
it should return an error if provided version is empty string.

In our implementation, we let the [contract return a version](https://github.com/CosmWasm/wasmd/blob/606289ab56dbe803bc28941a4b4c361b26435d37/x/wasm/ibc.go#L73) or [default to the provided one](https://github.com/CosmWasm/wasmd/blob/606289ab56dbe803bc28941a4b4c361b26435d37/x/wasm/ibc.go#L77-L79) if the contract does not return a version, but we do not handle the case mentioned above, where the contract does not return a version and the provided version is empty.

**Comment by alpe** [comment]
Thanks for bringing this up! Your observation is correct that we do not error in case of the empty version. I am surprised to see this not handled by the ibc-go module themself. 🤷 I may open an issue with ibc-go repo to discuss this
