### ISSUE TITLE
Remove keeper.MaxGas or write a comment why it is needed

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#170]
The existence of [keeper.MaxGas](https://github.com/CosmWasm/wasmd/blob/v0.9.1/x/wasm/internal/keeper/keeper.go#L30-L31) is suspicious and is confusing people. @ethanfrey, why do we need a limit for the smart contract execution other than the gas limit of the block or the tx?

Even if the VM has an execution limit (which is [has right now](https://github.com/CosmWasm/cosmwasm/blob/v0.9.2/packages/vm/src/backends/singlepass.rs#L15-L23) but should not), I don't see a reason to maintain the value in two places. The VM then just stops once its limit is eached.

**Comment by ethanfrey** [comment]
It was there, as once upon a time if the gas limit from go was higher than that of rust. We got an under flow panic in some rust gas calculation code.

I think it is unneeded now

**Comment by alpe** [comment]
It is used for the [upper](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/keeper.go#L532) gas limit and still part of the [go-wasm api](https://github.com/CosmWasm/go-cosmwasm/blob/master/api/lib.go#L78) and rust [code](https://github.com/CosmWasm/go-cosmwasm/blob/5a3a5a790a4da0bcf3ca858f8584759d322bf3e8/src/lib.rs#L313)

**Comment by ethanfrey** [comment]
Yes, the gas limit needs to be passed in (this is read from the context).

The only use of [`MaxGas` is here](https://github.com/CosmWasm/wasmd/blob/9ab18fc46f2779cbc6642ff395ed8fd47b879142/x/wasm/internal/keeper/keeper.go#L532-L534), which put an upper limit of what we passed into rust, as there used to be an overflow problem (fixed in 0.7 I think)

**Comment by ethanfrey** [comment]
I figured it was easier to fix than discuss, so I made the PR #188

Turns out one test fails. Not all the gas tests, but one. If anyone wants to look into it, feel free... or I will come back to this in a few days

**Comment by ethanfrey** [comment]
After more discussions with Simon, it seems there still is a limit in cosmwasm-vm, which is needed to prevent an overflow there.

We can set it to `10_000_000_000 / GasMultiplier` which is the maximum amount of SDK gas we can allow (`10_000_000_000` wasmer gas)
