### ISSUE TITLE
Add gRPC querier for Build Address Query

### ISSUE THREAD

**Issue by NotJeremyLiu** [CosmWasm/wasmd#1705]
Right now, the Build Address query used for instantiate2 is exposed as a CLI query only: https://github.com/CosmWasm/wasmd/blob/62d91d972a913888eb1c6ef692e372b8ceb1f560/x/wasm/client/cli/query.go#L73

For my current use case, this requires all deployers of our contracts to have daemons for multiple networks locally installed to then generate the necessary instantiate2 addresses in advance.

I would love for the query to be implemented in the gRPC query service, allowing for easier/automatic deployment processes that need to pre-gen the addresses just using public endpoints.

If the team is in favor of this addition, I can write the PR.

**Comment by alpe** [comment]
👍 Good idea

**Comment by NotJeremyLiu** [comment]
Awesome, I will PR this early next week!
