### ISSUE TITLE
Provide migration code for gov beta1 to v1

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#1713]
Follow up on https://github.com/CosmWasm/wasmd/issues/1608#issuecomment-1806330871

**Comment by emidev98** [comment]
Hey @alpe thank you for considering this,  as a quick solution for the chains migrating from 0.41 to +0.41 you could revert the pr similar to what has been done here https://github.com/terra-money/wasmd/commit/21809bc112681a0044b360ee90368914bd6d28d1

**Comment by alpe** [comment]
Thanks for bringing this up and the help! We need to bring back the v1beta1 wasm proposal types to support gov v1 with legacy content stored. Otherwise historic gov proposals can not be queried anymore.

**Comment by emidev98** [comment]
For sure @alpe always happy to help! If there is any other way I can help let me know! Congrats for the latest releases!
