### ISSUE TITLE
key not found while deploying the smart contract

### ISSUE THREAD

**Issue by olfa-dallel-enit** [CosmWasm/wasmd#1745]
Hello,

I am trying to deploy a smart contract on the wasmd using the following command:

sudo ~/go/bin/wasmd tx wasm store  ./target/wasm32-unknown-unknown/release/counting_contract.wasm  --from main 

I obtained the following error:

ERR failure when running app err="rpc error: code = NotFound desc = rpc error: code = NotFound desc = account wasm1lqmjjrkr5033lh38e7ty4jwlq0cqngxpm0w73x not found: key not found"

Please, how to solve this error?

Thank you.

**Comment by alpe** [comment]
Do you have tokens for your account on the chain? It looks like this is the issue as the key name `main` was resolved to address `wasm1lqmjjrkr5033lh38e7ty4jwlq0cqngxpm0w73x` locally. 
You may find our [examples](https://github.com/CosmWasm/wasmd/tree/main/contrib/local) useful.

**Comment by olfa-dallel-enit** [comment]
Hello,

Thank you for your reply.
I followed the examples, but I got this error:

ERR failure when running app err="rpc error: code = NotFound desc = \ngithub.com/cosmos/cosmos-sdk/baseapp.gRPCErrorToSDKError\n\tgithub.com/cosmos/cosmos-sdk@v0.50.1/baseapp/abci.go:1143\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC\n\tgithub.com/cosmos/cosmos-sdk@v0.50.1/baseapp/abci.go:1127\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query\n\tgithub.com/cosmos/cosmos-sdk@v0.50.1/baseapp/abci.go:190\ngithub.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Query\n\tgithub.com/cosmos/cosmos-sdk@v0.50.1/server/cmt_abci.go:24\ngithub.com/cometbft/cometbft/abci/client.(*localClient).Query\n\tgithub.com/cometbft/cometbft@v0.38.1/abci/client/local_client.go:106\ngithub.com/cometbft/cometbft/proxy.(*appConnQuery).Query\n\tgithub.com/cometbft/cometbft@v0.38.1/proxy/app_conn.go:181\ngithub.com/cometbft/cometbft/rpc/core.(*Environment).ABCIQuery\n\tgithub.com/cometbft/cometbft@v0.38.1/rpc/core/abci.go:22\nreflect.Value.call\n\treflect/value.go:596\nreflect.Value.Call\n\treflect/value.go:380\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3\n\tgithub.com/cometbft/cometbft@v0.38.1/rpc/jsonrpc/server/http_json_handler.go:108\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4\n\tgithub.com/cometbft/cometbft@v0.38.1/rpc/jsonrpc/server/http_json_handler.go:140\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2514\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP\n\tgithub.com/cometbft/cometbft@v0.38.1/rpc/jsonrpc/server/http_server.go:256\ngithub.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1\n\tgithub.com/cometbft/cometbft@v0.38.1/rpc/jsonrpc/server/http_server.go:229\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2938\nnet/http.(*conn).serve\n\tnet/http/server.go:2009\nrpc error: code = NotFound desc = account wasm12yqczxhvqdjepu54xeqnqhlhz8vghlyknhpy4j not found: key not found"

Thank you

**Comment by olfa-dallel-enit** [comment]
In addition, when i execute this command

HOME=/tmp/trash bash setup_wasmd.sh

I got this error
setup_wasmd.sh: ligne 10: wasmd : commande introuvable

while  wasmd is created in ~/go/bin/!?

**Comment by olfa-dallel-enit** [comment]
Hello,

I find the solution

I added "--home /home/nocseniso/.wasmd" for each transaction that look for a key to force him not to look for the keys from /root/.wasmd

Thank you
