### ISSUE TITLE
adding new module to wasm

### ISSUE THREAD

**Issue by olfa-dallel-enit** [CosmWasm/wasmd#1749]
Hello,

I am trying to add a new module to wasm by executing this commend:
ignite scaffold module testcreat

However, i got this error

✘ Error while running command go mod tidy: go: downloading github.com/cockroachdb/pebble v0.0.0-20231102162011-844f0582c2eb
go: downloading github.com/linxGnu/grocksdb v1.8.4                                                                       
go: downloading github.com/sagikazarmark/locafero v0.3.0                                                                 
go: downloading github.com/frankban/quicktest v1.14.4                                                                    
go: downloading github.com/btcsuite/btcd/btcutil v1.1.3                                                                  
go: downloading github.com/onsi/gomega v1.26.0                                                                           
go: downloading github.com/decred/dcrd/crypto/blake256 v1.0.1                                                            
go: downloading github.com/go-errors/errors v1.4.2                                                                       
go: downloading github.com/pingcap/errors v0.11.4                                                                        
go: downloading github.com/hashicorp/go-uuid v1.0.2                                                                      
go: downloading github.com/golang/glog v1.1.2                                                                            
go: downloading github.com/gin-gonic/gin v1.8.1                                                                          
go: downloading github.com/petermattis/goid v0.0.0-20230904192822-1876fd5063bc                                           
go: downloading github.com/gobwas/httphead v0.1.0                                                                        
go: downloading github.com/gobwas/pool v0.2.1                                                                            
go: downloading golang.org/x/tools v0.14.0                                                                               
go: downloading github.com/Azure/go-ansiterm v0.0.0-20230124172434-306776ec8161                                          
go: downloading github.com/go-playground/validator/v10 v10.11.1                                                          
go: downloading github.com/ugorji/go/codec v1.2.11                                                                       
go: downloading github.com/goccy/go-json v0.9.11                                                                         
go: downloading github.com/sourcegraph/conc v0.3.0                                                                       
go: downloading go.uber.org/multierr v1.11.0                                                                             
go: downloading github.com/ugorji/go v1.2.7                                                                              
go: downloading github.com/go-playground/locales v0.14.0                                                                 
go: downloading golang.org/x/mod v0.13.0                                                                                 
go: downloading github.com/cockroachdb/datadriven v1.0.3-0.20230413201302-be42291fc80f                                   
go: downloading github.com/DataDog/zstd v1.5.5                                                                           
go: downloading github.com/cockroachdb/tokenbucket v0.0.0-20230807174530-cc333fc44b06                                    
go: finding module for package github.com/cosmos/cosmos-sdk/store/types                                                  
go: finding module for package github.com/CosmWasm/wasmd/testutil/sample                                                 
go: finding module for package github.com/cosmos/cosmos-sdk/store                                                        
go: finding module for package github.com/CosmWasm/wasmd/testutil/nullify                                                
go: downloading github.com/cosmos/cosmos-sdk/store v1.0.1                                                                
go: found github.com/cosmos/cosmos-sdk/store in github.com/cosmos/cosmos-sdk/store v1.0.1                                
go: found github.com/cosmos/cosmos-sdk/store/types in github.com/cosmos/cosmos-sdk/store v1.0.1                          
go: github.com/CosmWasm/wasmd/testutil/keeper imports                                                                    
	github.com/cosmos/cosmos-sdk/store: github.com/cosmos/cosmos-sdk/store@v1.0.1: parsing go.mod:                           
	module declares its path as: cosmossdk.io/store                                                                          
	        but was required as: github.com/cosmos/cosmos-sdk/store                                                          
: exit status 1                                                                                                 

Please, how to solve this error.
Thank you

Regards

**Comment by pinosu** [comment]
This issue is not related to wasmd, so I will close it.
Anyway, as written in the output you need to modify go.mod and require `cosmossdk.io/store` instead of `github.com/cosmos/cosmos-sdk/store` .
