### ISSUE TITLE
Enable/disable  wasm gov message types

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#175]
## Summary
See #162 for context

When compiling a chain, you should be able to enable None of these, All of these, or Some of these. By default, none of the proposal types are enabled. There should be one function to easily register all proposals with the application. And there should be another function (or functions) that can be used to selectively enable some of these. The last 3 - MigrateContract, UpdateAdmin, ClearAdmin can all be enabled/disabled as a block, as giving access to governance to do one is close to giving access to all.

**Comment by alpe** [comment]
Add in code doc: https://github.com/CosmWasm/wasmd/pull/173#discussion_r450856050

**Comment by ethanfrey** [comment]
It actually looks quite good now, they way you set this in `app.go`.

You can add another docstring somewhere if you wish, or just close this issue

**Comment by alpe** [comment]
I have added some inline doc. One note on the defaults: currently all wasm proposal types are enabled. The opposite was defined in the original issue. Should we keep them all enabled? That would make it easier with the CLI where all types are enabled, too.

**Comment by ethanfrey** [comment]
Hmm... what I want to here is make two binaries - `wasmd` and `wasmgovd` which are 99% the same except for all government votes disabled in `wasmd` (permissionless network) and all enabled in `wasmgovd` (permissioned for cosmos hub proposal).

Ideally there should be minimal code copy and we can even pass in this set to `app.go` so we can use the same `app` package, just change the setup in `main`. 

Maybe we can close this issue (which is done in the module level) and add a new one for the two binaries (on the cli/binary level)

**Comment by alpe** [comment]
In this case we could just pass the supported types to the `NewWasmApp` constructor function and we are done here.
