### ISSUE TITLE
wasmd instalation error

### ISSUE THREAD

**Issue by kaikyfersoa** [CosmWasm/wasmd#1760]
have cloned & take a checkout to v0.30.0
when i try to run make install command shows below error:

$ make install
go install -mod=readonly -tags "netgo,ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=wasm -X github.com/cosmos/cosmos-sdk/version.AppName=wasmd -X github.com/cosmos/cosmos-sdk/version.Version=0.30.0 -X github.com/cosmos/cosmos-sdk/version.Commit=a347ace2ff41539fe06c68168bc6f28d6ca9fa52 -X github.com/CosmWasm/wasmd/app.Bech32Prefix=wasm -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' -trimpath ./cmd/wasmd
go: downloading github.com/cosmos/cosmos-sdk v0.45.11
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/spf13/cobra v1.6.0
go: downloading github.com/tendermint/tendermint v0.34.23
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/cosmos/ibc-go/v4 v4.2.0
go: downloading github.com/cosmos/interchain-accounts v0.2.4
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/CosmWasm/wasmvm v1.1.1
go: downloading github.com/docker/distribution v2.8.1+incompatible
go: downloading github.com/cosmos/cosmos-proto v1.0.0-alpha8
go: downloading github.com/cosmos/gogoproto v1.4.3
go: downloading google.golang.org/genproto v0.0.0-20221024183307-1bc688fe9f3e
go: downloading github.com/rs/zerolog v1.27.0
go: downloading github.com/spf13/viper v1.14.0
go: downloading golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
go: downloading github.com/99designs/keyring v1.2.1
go: downloading google.golang.org/protobuf v1.28.2-0.20220831092852-f930b1dc76e8
go: downloading github.com/google/btree v1.1.2
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20210819022825-2ae1ddf74ef7
go: downloading github.com/armon/go-metrics v0.4.0
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/cosmos/cosmos-sdk/ics23/go v0.8.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading golang.org/x/net v0.1.0
go: downloading github.com/go-kit/log v0.2.1
go: downloading github.com/cosmos/iavl v0.19.4
go: downloading golang.org/x/crypto v0.1.0
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/btcsuite/btcd v0.22.1
go: downloading github.com/lib/pq v1.10.6
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/danieljoos/wincred v1.1.2
go: downloading github.com/dvsekhvalnov/jose2go v1.5.0
go: downloading golang.org/x/term v0.1.0
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.2
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/libp2p/go-buffer-pool v0.1.0
go: downloading github.com/creachadair/taskgroup v0.3.2
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading github.com/golang/snappy v0.0.4
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/pelletier/go-toml/v2 v2.0.5
go: downloading github.com/mimoo/StrobeGo v0.0.0-20210601165009-122bf33a46e0
go: downloading github.com/klauspost/compress v1.15.11
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/pelletier/go-toml v1.9.5
# github.com/CosmWasm/wasmd/cmd/wasmd
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwasmvm
collect2.exe: error: ld returned 1 exit status

make: *** [Makefile:96: install] Error 1

Can anyone help me to understand why this error raise and how to solve it?

**Comment by webmaster128** [comment]
Heyhey! Running wasmd nodes on Windows cannot work as this has never been fully implemented in wasmvm. What should work is building a wasmd CLI client to the blockchain without executing smart contracts. For this you have to disable cgo in the build. Would that solve your problem or do you try to run a node on Windows?
