### ISSUE TITLE
question: how to set fee for upload of wasm file proportional to wasm file size?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [CosmWasm/wasmd#1768]
I am trying to add spam protection against contract files uploads.

I spent hour searching here or in Osmosis how to set fee for upload (on top of usual gas TX), but failed.

How can I ensure to set custom fee for upload?

**Comment by webmaster128** [comment]
There is not message-specific fee setting. The gas parameters you can change are:
1. Transaction size limits in CometBFT
2. Wasm size limits (`MaxWasmSize`)
3. The compile cost per by (`CompileCosts` in `GasRegister`). This is charged for every upload where the contract is compiled once from Wasm to a module.

The last one is probably the closest to what you are looking for.
