### ISSUE TITLE
Gov: revisit events

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#181]
# Summary
Relates to #161 

There is still the open question what event attributes we want to publish for gov.
The AttributeSigner does not really fit IMHO. Should we remove it/ leave it empty/ put a string "gov" there?

```
    ourEvent := sdk.NewEvent(
        sdk.EventTypeMessage,
        sdk.NewAttribute(sdk.AttributeKeyModule, types.ModuleName),
        //sdk.NewAttribute(AttributeSigner, p.Creator.String()),
        sdk.NewAttribute(AttributeKeyCodeID, fmt.Sprintf("%d", p.Code)),
        sdk.NewAttribute(AttributeKeyContract, contractAddr.String()),
    )
```
See https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/proposal_handler.go#L99
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Okay, after researching the "sdk best practices", I see TextProposal has a nil handler, and the upgrade proposal mechanism returns no events at all: https://github.com/cosmos/cosmos-sdk/blob/9a183ffbcc0163c8deb71c7fd5f8089a83e58f05/x/upgrade/handler.go#L9-L29

I think you can safely remove the commented out line and declare our governance proposals "best in class event tagging"
