### ISSUE TITLE
Upgrade vuepress-theme-cosmos from 1.0.133 to 1.0.166

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#185]
## Summary
https://github.com/R1971/wasmd/commit/153ac9f6367abe4220648c64985227bfe0561499
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Actually, I should just gut the docs section as it doesn't apply to us (left over from forking gaia)
