### ISSUE TITLE
Introduce wasmgovd binary

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#187]
"Make two binaries - wasmd and wasmgovd which are 99% the same except for all government votes disabled in wasmd (permissionless network) and all enabled in wasmgovd (permissioned for cosmos hub proposal)."

Follow up from https://github.com/CosmWasm/wasmd/issues/175#issuecomment-658092631

Context https://github.com/CosmWasm/wasmd/issues/161

Can we ship both binaries within the same docker artifact or should we split them?
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alpe** [comment]
Can we use the same home dir for both binaries? `~/.wasmd/`? That would make the docker setup script easier

**Comment by ethanfrey** [comment]
Yes, we can use everything the same.

No one should mix them. They can take the same docker image and run either `wasmd` or `wasmgovd` consistently. If you run the different apps on the same data, that may lead to consensus failure

**Comment by ethanfrey** [comment]
I guess if you expect people to run non-dockerized versions of both binaries on the same computer, you are right, it is better different. I doubt that will happen, but it is definitely safer
