### ISSUE TITLE
wasmd installation issues

### ISSUE THREAD

**Issue by Mikecryptoma** [CosmWasm/wasmd#1890]
# runtime/cgo
gcc_libinit_windows.c: In function '_cgo_beginthread':
gcc_libinit_windows.c:143:27: error: implicit declaration of function '_beginthread'; did you mean '_cgo_beginthread'? [-Werror=implicit-function-declaration]
  143 |                 thandle = _beginthread(func, 0, arg);
      |                           ^~~~~~~~~~~~
      |                           _cgo_beginthread
cc1: all warnings being treated as errors
make: *** [Makefile:96: install] Error 1

**Comment by pinosu** [comment]
Windows is not supported yet. `make install` works only on linux and macOS
