### ISSUE TITLE
Can't download wasmd

### ISSUE THREAD

**Issue by MateoGargano** [CosmWasm/wasmd#1908]
I followed the instructions to download wasmd from this tutorial (https://docs.cosmwasm.com/docs/getting-started/installation) but when i run 'wasmd version' i get the following error: wasmd: command not found.
Im running this in wsl with Ubuntu and followed all the previous steps from the tutorial mentioned before. I also tried making the same in dev instead of checking out to v0.27.0 but i get the same results.

**Comment by pinosu** [comment]
Hey @MateoGargano, check this issue to understand how to fix it https://github.com/CosmWasm/wasmd/issues/821
