### ISSUE TITLE
Move history of contract code migrations to their own prefix store. 

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#196]
## Summary

Move history of contract code migrations to their own prefix store. This would reduce the overhead in de-/serialization data for ContractInfo and save gas.

Follow up on #130 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Good idea.

I think they can have a different prefix store, but one element per contract. Using the same address as key.

Definitely makes most queries much cheaper when there is much migration

**Comment by alpe** [comment]
👍  Another benefit is easier genesis ex-/ import as there is no need to import the history
