### ISSUE TITLE
Limit  init/migrate/execute payload message size

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#203]
## Summary
There are currently no limits to the msg payload in `MsgInstantiateContract`, `MsgMigrateContract` and `MsgExecuteContract`. Should we set limit for external/ dispatched messages?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
You have to pay gas for them, and they cost lots of wasm gas to process.

It might make sense to produce a reasonable limit on them, but what is reasonable? If I want to start an erc20 like contract with eg. 5000 addresses from some import, that will be easily 200kb.

I would rely on the tx gas limit and byte size to enforce this

**Comment by ethanfrey** [comment]
Unless you have an objection, I would close this and just rely on other controls (like "max tx bytes" and "gas cost per tx byte") to limit this

**Comment by alpe** [comment]
Thanks for the updates. A scenario I had in mind was a contract that returns a very big message. Tx limits would not apply here as we dispatch them internally. I hope this is covered. 🤞

**Comment by ethanfrey** [comment]
You are right, this could be quite large. But as soon as we write this to the migration history, it will charge a bunch of gas based on size. I don't see a need for explicit limits, but if you want to make some (very large) ones, like 64kB, that is fine

**Comment by alpe** [comment]
Instead of a hard byte size lime we can charge for the bytes as proposed in option 2 in #297

**Comment by ethanfrey** [comment]
Let's do that.
