### ISSUE TITLE
Find and remove unused gaia legacy

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#206]
# Cleanup Project

For example
* /docs
* /contrib ?
...

Inside .circleci , .github, Makefile,...

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
I agree with this. We can bring pieces in as we need them (like the CI stuff).

Good to trim down this repo to what we actually use.
