### ISSUE TITLE
Delete /docs folder since we have a separate docs repo

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/wasmd#215]
Looks like there is a left over [/docs](http://orkunkl.github.com/CosmWasm/wasmd/blob/6e021d9b452f7cd69f3bbf55a7c4ad05ebbd4532/docs#L18-L18) from the last iterations of documentation. If there is no need for it we should delete it to prevent confusion.

**Comment by ethanfrey** [comment]
Part of #206 

This can be a separate issue, and one checkbox off the larger cleanup.
