### ISSUE TITLE
version subcommand does not work

### ISSUE THREAD

**Issue by clevinson** [cosmwasm/wasmd#24]
## Summary of Bug

`wasmd version` does not work.

Output is currently a blank newline whenever running `wasmd version`. Seems like this the correct subcommand though, as `wasmd --version` returns an "unknown flag" error and trying something like `wasmd verssion` outputs:
```
ERROR: unknown command "verssion" for "wasmd"

Did you mean this?
	version
```

## Version

git commit hash: ce35d8de8296193fd7ab8f848917563df7b90089

## Steps to Reproduce

```
make install
wasmd version
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by clevinson** [comment]
Seems to pull in version logic from this submodule: https://github.com/cosmos/cosmos-sdk/tree/master/version

I tried looking in cosmos-sdk repo to see if this was a known issue that has already been fixed, but couldn't find anything.

**Comment by ethanfrey** [comment]
Ah, yes, this needs to be set in the Makefile when building.

I don't know why it defaults to empty rather than git commit.
Valid issue

**Comment by sahith-narahari** [comment]
I think there's no valid tag and hence the empty response. 
Pushing a tag  `0.0.0` should solve this or alternatively replacing `git describe --tags` with `git describe --always` in this line will give commit hash as response https://github.com/cosmwasm/wasmd/blob/b2086bb6b40ca74a3959927ca7219bfe0b60c7d9/Makefile#L4

**Comment by ethanfrey** [comment]
Good to know.
There will be a 0.6.0 tag within a day or so, so let's see see if this fixes the issue

**Comment by ethanfrey** [comment]
>  There will be a 0.6.0 tag within a day or so, so let's see see if this fixes the issue

:man_facepalming: delays and more delays on 0.38.0...

I have been tagging pre-release versions and `wasmd version` now reads: `0.0.3-4-ge4be8f1`. Case closed.
