### ISSUE TITLE
Add more metadata along with contract

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#251]
The builds on and extends #241 which is a great idea.

When we upload code, we upload a ~200kB wasm blob. 
There is no reason we cannot add even 20kB of metadata like schemas and other references. Let's collect more ideas besides the JSON schemas and see which make sense:

- [ ] json-schema-to-typescript interfaces (as this is primary user of json schemas)
- [ ] source code??? (rather than a link)
- [ ] links to helpers.ts script (as @orkunkl suggested here: https://github.com/CosmWasm/docs2/pull/73#discussion_r470449702)
- [ ] links to deployed webapp frontends (or maybe that belongs with the contract, not code)

I wonder if this makes sense to add all of them on the Code itself, or as annotations. In this case, the key technical items - schemas, ts interface, maybe source code would go on the Code. We would then allow any number of "Annotations" that can be attached to a Code blob, not only by the owner. These are suggestions, as `{Type, URL}` pairs

```go
{
  Type: "cosmjs/cli",
  URL: "https://raw.githubusercontent.com/CosmWasm/cosmwasm-plus/master/contracts/cw20-base/helpers.ts",
  By: "coral162d3zk45ufaqke5wgcd3kh336k6p3kwwkdj3ma",
}

{
  Type: "dApp",
  URL: "https://dapps.coralnet.cosmwasm.com/cw20",
  By: "coral1e86v774dch5uwkks0cepw8mdz8a9flhhapvf6w",
}

// we can even add some "code review" type comments here as claims
{
  Type: "Audit",
  URL: "???",
  By: "coral1dyual04q9m3f0a7qsvfx4hvu8ceyrxw9yldp8w",
}

{
  Type: "Bug"
  URL: "???",
  By: "coral1dyual04q9m3f0a7qsvfx4hvu8ceyrxw9yldp8w",
}
```

**Comment by ethanfrey** [comment]
@alpe @webmaster128 I would be curious for your opinions here when you have time. Nothing urgent, just may be a nice polish for 1.0.

**Comment by alpe** [comment]
I like the idea to store metadata. 🌷 
This can be very powerful feature for various use cases that people will come up with.
Though we need some structure and permissions in place at some point so that this does not go wild.
For example if everybody can add metadata to codes then how do we prevent scammers?
The metadata may be displayed in web UIs so it should be safe and (partly) human readable

I can imagine that we want to store metadata with codes and contracts separately. For example: the code was audited by xxxx, the contract UI runs on IP: yyyy

**Comment by ethanfrey** [comment]
@webmaster128 any opinions, feedback here? I know cosmjs will be the largest provider/consumer of such metadata, so it would be good to know your desires to make the customer happy :smile:

**Comment by webmaster128** [comment]
Some of this data is good to have. I like the JSON Schema, as an interface description.

I'm highly sceptical with respect to TypeScript types. I don't consider the JSON Schema -> .d.ts super stable and would also avoid to have better support for one client technology than for others. JSON Schema is stable and universal.

As mentioned elsewhere, I think it is a serious security issue to add helper scripts to the chain. Users will execute them in a node process with their current user's pevillages no matter what they contain. I'd rather have a service that creates the helper scripts dynamically based on some variables than users storing arbitrary code on chain. Also things like fees and RPC endpoints are probably not stable for the lifetime of the contract.

Re: source code
As Ethan wisely noted, people will trust the source code if it is on chain, no matter matches the compiled code. Also is we are moving towards monolytic contract repos (like cosmwasm-plus), we suddenly get a very big source as the whole repo is part of the contract build.

**Comment by ethanfrey** [comment]
Closing for the same reason as https://github.com/CosmWasm/wasmd/issues/241#issuecomment-756376059

This is too much logic to put in a blockchain, we should put that in an explorer "web app" or "api service" that allows a lot more fleixibllity to iterate and run long-lived tasks
