### ISSUE TITLE
Revisit "smart" query gas costs

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#266]
The current query gas costs let people prefer "raw" queries over "smart" queries to other contracts. That would encourage integration on the DB layer which is an anti-pattern in system integration. 

This issue was inspired by some conversation on [discord](https://discord.com/channels/737637324434833438/738016386625830973/751107960964382721)

**Comment by alpe** [comment]
Let's benchmark this and revisit the cost when wasmer-reborn lands in cosmwasm-vm. We may be able to reduce this gas price with a more efficient startup phase

**Comment by alpe** [comment]
Other option is arbitrarily increase cost of raw query

**Comment by ethanfrey** [comment]
Now with pinned contracts, smart queries no longer have the 40k overhead and are more or less the same price (there is some wasm gas used, possibly multiple storage calls, but that is things that cannot be done with raw queries).

I would close this as pinning changes handle this issue
