### ISSUE TITLE
Add deterministic build system

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#268]
This lets us get deterministic binaries.

https://github.com/cosmos/cosmos-sdk/pull/7247 is a very nice example for the go part. We will need to ensure a deterministic build system for the rust dll as well, but piece by piece

**Comment by ethanfrey** [comment]
They just overhauled the gaia build system to a simpler version. We should use that as reference when we start on this issue. 

https://github.com/cosmos/gaia/pull/523/files

**Comment by yihuang** [comment]
Is it possible to statically link the libwasmvm library? not familiar with golang's build system, but static link should make it easier to redistribute binary.
Also I'd like to make a nix expression for wasmd, static link also make it easier, no need to manipulate rpath stuff.

**Comment by ethanfrey** [comment]
Look at the Docker build in the repo. It does static.

With glibc systems we can only build rust dll, which dynamically link to Go. With muslc (alpine), we can make a static build of rust and thus a static build of the wasmd binary.

We only include the dlls (not static libs) in wasmvm due to size.

I spent several days trying to get static builds to work and using muslc based docker was the best I got. I would be very happy if you can figure out how to build a static lib of wasmvm on a glibc system (ubuntu, Debian, centos, etc)

**Comment by alpe** [comment]
This is a very old issue. gaia has moved away from gitian meanwhile. I found the docker approach that was used by [terra](
https://github.com/terra-money/core/blob/main/Makefile#L121-L134) very nice.
The container provides the "identical environment" to build the binary artifact.
Should be easy to add a new target to the Makefile

**Comment by pinosu** [comment]
Closing because not relevant. 
See [this comment](https://github.com/CosmWasm/wasmd/pull/1128#issuecomment-1359695053)
