### ISSUE TITLE
Let contracts not abuse the event system

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#280]
There are no explicit restrictions in wasmd right now for contracts to emit events. We should make sure that this is not abused by malicious actors.

We could charge SDK gas per byte after the contract execution as suggested by @webmaster128.

**Comment by webmaster128** [comment]
> We could charge SDK gas per byte after the contract execution as suggested by @webmaster128.

The reason behind this is: the contract does not call any function for sending events (there is no such thing as "emit"). It returns them as part of the execution result. So the first point at which we know the events/attributes is after the VM is done. So we need to charge SDK gas for processing and persisting the result.

Do we have the exact same issue for the result `data`?

**Comment by webmaster128** [comment]
I think we have the same problem with contract generated error messages and VM generated error messages including user data as well.

**Comment by ethanfrey** [comment]
I think a hard cap would be too arbitrary and hit some limits we do not want.
I think charging "per byte" or each event attribute would be break expectations of other modules.

I would propose a "soft cap" of some reasonable limit based on other modules usage (say 1 event, 5 attributes, 60 chars each). And then charge some small fee for everything that goes over it.

**Comment by ethanfrey** [comment]
I guess the same would apply to user-returned errors. If the string length is less than say 500, it is free.
Otherwise charge 0.5 gas for every byte over (or something like that)
