### ISSUE TITLE
Cosmwasm v 0.11 - broken wasm files (deserialization error) 

### ISSUE THREAD

**Issue by BlockscapeLab** [CosmWasm/wasmd#288]
After I upgraded my toolchain to cosmwasm v 0.11. I can't upload contracts any longer to wasmd with 'wasmcli tx wasm store 'contractv11.wasm'

Following error encountered: 

ERROR: create wasm contract failed: Error calling the VM: Error during static Wasm validation: Wasm bytecode could not be deserialized. Deserialization error: "I/O Error: UnexpectedEof": failed to execute message; message index: 0: failed to simulate tx

Of course I recompiled my existing contract with cargo clean/build/schema/wasm before. 

Here are more details:

ls -l contractv11.wasm 
-rwxr-xr-x  1 changed  staff  1640608 Oct 10 20:35 contractv11.wasm

file contractv11.wasm
contractv11.wasm: WebAssembly (wasm) binary module version 0x1 (MVP)

$uname -a
Darwin MacBook-Pro-16-inch-2019 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

docker version 
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Here is the repo with the contract: https://github.com/BlockscapeLab/contractv11/tree/master

**Comment by webmaster128** [comment]
This issue is now tracked in #287 and #289. For the 0.11 release series, we need to keep in mind that deserialization errors can be a caused by too large Wasm files. Thank you.
