### ISSUE TITLE
More ContractInfo

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#291]
Builds on #251 and #241 

Besides API, do we want to store more info?

* If two contracts are linked together, deployed as a bundle, maybe this is stored?
* Linking contract to token vouchers? (if implemented)
* Some sort of permission levels if we can control minting, etc from contract?

And how to set such metadata?

**Comment by ethanfrey** [comment]
I think this was mostly addressed by letting chains extend ContractInfo.
We don't need to handle these use cases in wasmd, but allow chains to import x/wasm and add such functionality without forking.

Maybe just document how one could do such a process? I see no code changes needed in the core library

**Comment by ethanfrey** [comment]
@alpe can we close this? Anything else to add?

I see #584 as relevant, but I think this was solved by the extensions support you have added.
