### ISSUE TITLE
Instantiate contract process ordering

### ISSUE THREAD

**Issue by YunSuk-Yeo** [CosmWasm/wasmd#292]
## Problem State
As you can see in https://github.com/terra-project/core/issues/399

If you store the instantiated contract after dispatching all messages, it will block the messages to use instantiated contract.

https://github.com/CosmWasm/wasmd/blob/ff37dc68f2a4ea86abf7b7f124c166c793d63e67/x/wasm/internal/keeper/keeper.go#L242-L250

## Proposed solution
So recommend to store the instantiated contract data and dispatch response messages later.

**Comment by ethanfrey** [comment]
Good point. So the messages sent out can refer back to the newly instantiated contract. Will add to next release
