### ISSUE TITLE
Limit Event Attribute Sizes

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#297]
Currently the contract can return unlimited data in the log attribute fields. We should provide some reasonable limits. Either:

1. Provide a hard limit of # of attributes and key/value lengths
2. Charge gas per attribute/byte of data logged

Opinions on which is better?

**Comment by alpe** [comment]
I prefer option 2 as there is no overhead for managing the limit

**Comment by alpe** [comment]
Part of #280
