### ISSUE TITLE
write some code include panic, the stack info will print on terminal

### ISSUE THREAD

**Issue by KamiD** [CosmWasm/wasmd#3]
## Summary of Bug
I wrote a panic code in contract: 'escrow'. then i deployed on my wasmd. after init, i call contract by 
`wasmcli tx wasm execute fred $CONTRACT "$APPROVE" -y`
The tx was succeed, when i terminate wasmd by ctrl+c, the stack error print on my terminal 

## Version

- using branch: master.

- commit id: d12c434ab6cc158bd05376d32c58f2ca2e6b0d66 

nothing to show for `wasmcli --version` and `wasmd --version`

## Steps to Reproduce

1.  add follow code in contract.rs and call it in `pub fn handle<T: Storage>`
 ```rust
fn try_panic(){
    panic!("panic test!");
} 
```   

2.  compile and deploy it to your own wasmd.
3.  use wasmcli to test contract
4. switch to wasmd and send ctrl+c to terminate it

The error will showed up

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
Thank you for the report. Can you send a copy of your forked escrow code? And the value of `$APPROVE` pass in here? `wasmcli tx wasm execute fred $CONTRACT "$APPROVE" -y`.

The contract should fail. If not, I will investigate further and fix it.

As to the error message / stack trace when hitting ctrl+C, this is an odd known issue that doesn't affect the chain performance but is worrying on restart. I will create a new issue for this.

**Comment by ethanfrey** [comment]
This has been fixed with wasmer 1.0.0, used by cosmwasm-vm 0.13.

Fix is on master as of #358 and will be on the v0.14.0 release. Took a year, but this looks a lot nicer now.
