### ISSUE TITLE
Support custom MessageHandler in wasm

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#327]
An `interface` would be a great extension point to the system.

We provide a default implementation but people may want to use a different implementation in their system or for testing.
This is only a small change in [keeper](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/internal/keeper/keeper.go#L54)

**Comment by alpe** [comment]
As an implementation detail:
We could have the following type definition 
```go
// Option is an extension point to instantiate keeper with non default values
type Option interface {
	apply(*Keeper)
}
```
With implementations that can set new values on private attributes. The constructor would be easily extendable:
```go
func NewKeeper(
	cdc codec.Marshaler,
	[...]
	opts ...Option,
) Keeper {
// and apply them all
	for _, o := range opts {
		o.apply(&keeper)
	}

```

**Comment by ethanfrey** [comment]
I think this was closed in the IBC mega-merge. @alpe can you verify and close if true?

**Comment by alpe** [comment]
Hot done for MessageHandler, yet
