### ISSUE TITLE
Charge gas for contract KV store keys

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#333]
Currently only the stored value is charged. With other cosmos modules the keys are build in Go and user input can not influence them very much but with our Wasm contracts the keys could be easily used for payload to bypass the gas metering. 🤪

**Comment by ethanfrey** [comment]
This is done in CosmWasm main, and I think will be back ported to 0.44.

Can we just rely on that and make a note about it somewhere (that people can back port PR x if they need it, otherwise available in next wasmd version)?

**Comment by ethanfrey** [comment]
This is in Cosmos SDK 0.45 and on master!
