### ISSUE TITLE
Follow proto dir best practice (in cosmos eco)

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#342]
I found more and more projects that store the protobuf files into
* `proto/` - for their own files
* `third_party/proto` - for the dependencies

This will make it easier to maintain multiple versions in the future but also works more nicely with `buf` linter.
On the downside these folders are not resolved by the Golang IDE automatically for dependencies.

**Comment by ethanfrey** [comment]
I like this idea. I've never had much IDE support for proto files, so I won't miss it (as long as the generated `*.pb.go` files work with the IDE).

**Comment by willclarktech** [comment]
This would also align us with Cosmos SDK.
