### ISSUE TITLE
Add MsgInstantiateContractResponse.data

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#385]
[MsgExecuteContractResponse](https://github.com/CosmWasm/wasmd/blob/v0.14.1/x/wasm/internal/types/tx.proto#L80-L84) and [MsgMigrateContractResponse](https://github.com/CosmWasm/wasmd/blob/v0.14.1/x/wasm/internal/types/tx.proto#L98-L103) have a contract defined `data` field. [MsgInstantiateContractResponse](https://github.com/CosmWasm/wasmd/blob/v0.14.1/x/wasm/internal/types/tx.proto#L62-L66) does not have this for historic reasons (we returned the raw contract address before).

Now that we can easily return structured proto messages, it would be good to add `MsgInstantiateContractResponse.data` for consistency.

**Comment by ethanfrey** [comment]
Ah, so we can have both fields, sender address and contract data in the same response.

Yes, this makes sense. :+1: for being able to return structured data

**Comment by alpe** [comment]
Good 💡 The field is easy to add. 

As a note: `Instantiate` can also be called by a gov proposal. The `data` field would not be returned or printed anywhere. 
If there is a requirement for the data then the best we can do IMHO would be adding an attribute to the event.  
WDYT? (This also affects migrate proposals) @webmaster128 @ethanfrey

**Comment by webmaster128** [comment]
> As a note: `Instantiate` can also be called by a gov proposal. The `data` field would not be returned or printed anywhere.

How does this work for other message types that are executed as part of a gov proposal?

**Comment by ethanfrey** [comment]
Hmmm... it makes sense to return it as a hex/base64 encoded attribute as well.

The types allow you to pass in bytes but much code blindly converts to and from string, so let's keep it utf8

**Comment by webmaster128** [comment]
> The types allow you to pass in bytes but much code blindly converts to and from string, so let's keep it utf8

This does not sound like a winning strategy. With the Stargate upgrade it is encouraged to store a serialized protobuf response in there, which is definitely not UTF8.

**Comment by alpe** [comment]
@webmaster128 do you have found an example or doc you can point me too?

**Comment by ethanfrey** [comment]
@webmaster128 @alpe  Please read the discussion from here on: https://github.com/cosmos/cosmos-sdk/pull/8624#issuecomment-788324243

There was quite some discussion about using raw bytes in events

**Comment by ethanfrey** [comment]
> Next question would be to always store the data or only for operations not triggered by a client (gov/contracts) ?
> Always would be easier to implement.

I'd take the simpler route
