### ISSUE TITLE
IBC: Querying which port a contract binded to

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/wasmd#415]
Currently there is no way to find out which port a smart contract is binded to after instantiation.

**Comment by ethanfrey** [comment]
This is [defined in code here](https://github.com/CosmWasm/wasmd/blob/14b4d167682be7f0f741e017232db8e1dda3db61/x/wasm/internal/keeper/ibc.go#L25-L44).

Basically, we just prefix the contractAddress with `wasm.` to make the port name. On musselnet, eg. `wasm.wasm10tsncqntt778xpkt7d5uwhul2rcmlj5c3larlj` on a cosmos chain, `wasm.cosmos1xj8j98thjnsnh62058v25r0hnthtdg53svu83a`

We should provide this info via a query somehow. Maybe on the contractInfo query we can add a field for IBCPort, which is either unset (if non-ibc) or set to the proper port if this is ibc-enabled.

**Comment by ethanfrey** [comment]
Oh, wait, we do return this via the ContractInfo query: https://github.com/CosmWasm/wasmd/blob/14b4d167682be7f0f741e017232db8e1dda3db61/x/wasm/internal/types/types.pb.go#L261-L274

Alex is a few steps ahead of me as always :smile:

**Comment by ethanfrey** [comment]
If this works for you, can you close the issue? Or maybe add a documentation PR to close it?

It was a good question
