### ISSUE TITLE
[Bug] Can't make store code tx with gas simulation

### ISSUE THREAD

**Issue by YunSuk-Yeo** [cosmwasm/wasmd#42]
## Summary of Bug

When we send tx with gas simulation (== --gas auto ), it will simulate the tx and then the code is created in the ~/.wasmd/wasm/. As a result, real execution of store code tx will fail with already exists error.

## Version

all version

## Steps to Reproduce

$ wasmcli tx store ./contract.wasm --gas auto --gas-adjustment 1.4 ~~
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ethanfrey** [comment]
That is interesting.... I never thought about simulation mode. Just check and deliver.

Good thing to fix.

**Comment by alpe** [comment]
For manual tests I was using the `cosmwasm/wasmd-demo`  docker image
```
cd /go/src/github.com/cosmwasm/wasmd/x/wasm/testdata
wasmcli tx wasm store ./escrow.wasm --from validator --gas auto --gas-adjustment 1.4  --chain-id=testing -y
```

**Comment by ethanfrey** [comment]
Thanks for fixing and testing
