### ISSUE TITLE
Revisit event types 

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#440]
We emit events of type `sdk.EventTypeMessage` mostly. They could become more useful with specific types.

**Comment by ethanfrey** [comment]
Nice idea, the `TypedEvent` stuff, right?

I saw this as I was parsing the abci.Events returned when dispatching an sdk.Msg and passing them to the EventManager and wondering why the method was deprecated. It would be good to use this for the ones we generate manually.

**Comment by alpe** [comment]
Sorry, I should have been more precise. This is not about the deprecated method but the string we pass as first argument https://github.com/CosmWasm/wasmd/blob/v0.15.1/x/wasm/internal/keeper/msg_server.go#L33 .
If we would use more concrete types like "contract_stored" instead of "message" then it would be easier for a client to subscribe to the right one. 
I found some good example in the [distribution module](https://github.com/cosmos/cosmos-sdk/blob/v0.41.4/x/distribution/types/events.go#L5-L10)

Ref [sdk-events](https://docs.cosmos.network/master/core/events.html)
