### ISSUE TITLE
Update wasmvm to v0.14.0-beta2

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#479]
As soon as https://github.com/CosmWasm/wasmvm/pull/208 is merged.

Besides updating contracts and gas and some error message, the only major change is adding `ReplyOn` to SubMsg. We need to check for Always (current behavior), Success (only reply if success, return errors directly) or Error (only reply if error, continue as normal on success).

**Comment by webmaster128** [comment]
wasmvm v0.14.0-beta2 is tagged now. Static lib was build [and deployed](https://github.com/CosmWasm/wasmvm/releases/tag/v0.14.0-beta2) as well.
