### ISSUE TITLE
Update to cosmwasm 0.14

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#486]

**Comment by webmaster128** [comment]
wasmvm v0.14.0-beta4 is released. Most important changes are the split of StakingMsg::Withdraw, the renamings of the all validators query and the new single validator query. You can also try the `GetMetrics(cache)` call if you are interested.

**Comment by ethanfrey** [comment]
There will be some ibc-related changes coming in `beta5`. 
So far, we modified all the `timeout` fields on the messages (but left them as-is for the packets)

**Comment by webmaster128** [comment]
This is done and released as 0.16.0
