### ISSUE TITLE
Add cli alias

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#496]
My common typos :-)
* `list-code`, `codes` -> `list-codes`
* `list-contracts-by-code`, `contracts` -> `list-contract-by-code`

How about some short aliases for 
* `c` -> `contract`
* `lco` -> `list-codes`
* `lca` -> `list-contract-by-code`
* `ch` -> `contract-history`
* `cs` -> `contract-state`

**Comment by ethanfrey** [comment]
I like more aliases. And optional short names.
