### ISSUE TITLE
Move sdk.Result downstream

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#498]
Currently the wasm `keeper` returns an `sdk.Result` on certain methods. In order to move towards a service oriented architecture the `sdk.Result` should be build in the handler. The `msgServer` should not need to unpack it for the GRPC result.

**Comment by ethanfrey** [comment]
Sounds good. But can you specify what the Keeper methods *should* return.

Especially ones that execute messages via the router get `sdk.Result` internally and then must combine them some way with the data. I feel there is a lot of back and forth with the event types between `EventManager` and `sdk.Result`. IIRC, one was `string` the other `[]byte`, or maybe there were the same but different names so we hand to go over the array converting them,

**Comment by alpe** [comment]
This is implemented
