### ISSUE TITLE
failed to instantiate contract in recent master version

### ISSUE THREAD

**Issue by yihuang** [CosmWasm/wasmd#511]
The error message for `wasmd tx wasm instantiate ...` is:

```
Error parsing into type cosmwasm_std::types::Env: Invalid type: instantiate wasm contract failed
```

Same test case works with previous version, not on recent version that update to `v0.14.0-rc1` wasmvm.

The test is here: https://github.com/crypto-org-chain/cosmwasm-plus-plus/pull/11

**Comment by ethanfrey** [comment]
You will need to update the contracts to rc1. We changed the env time representation.

I have an open PR that updates most of cosmwasm-plus (will finish monday). You can look at that for reference

**Comment by yihuang** [comment]
now it works 👍
