### ISSUE TITLE
nsmd tx wasm store ./cosmwasm-examples/contracts/escrow/target/wasm32-unknown-unknown/release/cw_escrow.wasm --from alice \ --gas-prices="0.025token" --gas="auto" --gas-adjustment="1.2" -y

### ISSUE THREAD

**Issue by worryFree56** [CosmWasm/wasmd#514]
Error: failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: "cosmwasm_vm_version_4". Exports required by VM: ["cosmwasm_vm_version_4", "query", "init", "handle", "allocate", "deallocate"]. Contract version too old for this VM?: create wasm contract failed: invalid request

golang:v1.15
wasmd: v0.14.1-0.20210113091717-f9015cba4793

![image](https://user-images.githubusercontent.com/22309148/117636584-8bf0ab80-b1b3-11eb-8476-75494aa865d9.png)

**Comment by the-frey** [comment]
What was the resolution here?

**Comment by alpe** [comment]
Maybe @worryFree56 wants to answer for his concrete problem but the error message in the issue description gives the hint: "Contract version too old for this VM". 
The wasmvm was upgraded since the the wasmvm version above.

**Comment by the-frey** [comment]
Yep, the answer to anybody finding this thread is to check versions are compatible and select an appropriate git tag/branch/what have you. Probably won't be as much of an issue when everybody's on a stable 1.0.0 release soon 👀
