### ISSUE TITLE
build error in mac m1

### ISSUE THREAD

**Issue by junjie-bianjie** [CosmWasm/wasmd#517]
[My step]
    git clone https://github.com/CosmWasm/wasmd.git
    make install 

[error]
ld: warning: ignoring file ../../go/pkg/mod/github.com/!cosm!wasm/wasmvm@v0.14.0/api/libwasmvm.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
 .......
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
make: *** [install] Error 2

**Comment by webmaster128** [comment]
This is expected because of the wasmvm depenndency (https://github.com/CosmWasm/wasmvm/issues/53)

**Comment by ethanfrey** [comment]
We can add a note about this to the wasmd readme: https://github.com/CosmWasm/wasmd#supported-systems

**Comment by junjie-bianjie** [comment]
thank you for you help

**Comment by PotasticPotatoe** [comment]
another solution could be use docker on M1

**Comment by ethanfrey** [comment]
> another solution could be use docker on M1

I tried that and art does start running, but eventually crashes when executing contracts. Not very stable.

**Comment by PotasticPotatoe** [comment]
What about using gitpod?

**Comment by ethanfrey** [comment]
> What about using gitpod?

Care to take on https://github.com/CosmWasm/cosmwasm-template/issues/58 ?

I'd love to have it, just never been high priority.

**Comment by PotasticPotatoe** [comment]
oscar beat me to it, ive been busy with work and only have time during weekends ;-;
