### ISSUE TITLE
Extendable gas costs

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#525]
Gas costs are currently constants in the Code that can not be changed without forking. For example https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/keeper.go#L41

We should not enforce the same costs on every chain that is using this module. Some options are
- Params (create extra gas costs)
- Overwrite via compile time flag on a `var`
- Abstract provider interface that returns the value

**Comment by ethanfrey** [comment]
Important to allow this customization.

> Overwrite via compile time flag on a var

I would support this as an easy first step. You could override when compiling wasmd, or in the `app.go` of any chain importing `x/wasm`. These need to be able to be tuned, but I do not think very often.

> Params (create extra gas costs)

This is an important one for any gas costs or limits that need to be adjusted "quickly" with a governance vote without redeploying a new binary. I would reflect carefully on what fields to add to params if it would really be useful (and just use public `var` for the rest)
