### ISSUE TITLE
Contract can mint vouchers

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#526]
Like IBC vouchers we can have contracts interact with the sdk to mint new vouchers.
We can follow the IBC denum design here to identify them and avoid conflicts.

Adding the pure mint/burn functionality is not complicated in our design but the complexity comes for the client that has to interact with these new vouchers. We would need to provide additional information for any contract voucher id (denum) so that a user can make qualified decisions using it. For example:
- source contract
- displayable denum (symbol)
- decimals

**Comment by ethanfrey** [comment]
Not sure we do this, but definitely a v2 feature if so.

If anyone has a concrete use case and needs this for their chain integration, please comment.

**Comment by alpe** [comment]
This is available as module: [token-factory](https://github.com/CosmWasm/token-factory)
