### ISSUE TITLE
Is MaxGas Still Limited by Rust?

### ISSUE THREAD

**Issue by loloicci** [CosmWasm/wasmd#528]
There is a comment about GasLimit
https://github.com/CosmWasm/wasmd/blob/bbb1669ada840757ce7d599660b48abc5c634c4b/x/wasm/keeper/keeper.go#L31-L33

But in the present version, I cannot find this parameter in cosmwasm/vm.
Is it still limited by rust?

**Comment by ethanfrey** [comment]
@webmaster128 would know better.

This may have been fixed with wasmer 1.0. If so, I should remove the comment

**Comment by webmaster128** [comment]
Nice find, thank you! The value was increased from 10_000_000_000 to 0x7FFFFFFFFFFFFFFF in CosmWasm 0.10 and completely removed in CosmWasm 0.13. Now ever uint64 is a valid gas limit. The constant `MaxGas` should be removed completely.
