### ISSUE TITLE
Error: error unmarshalling result: unknown field "proof" in types.ResponseQuery

### ISSUE THREAD

**Issue by AbhinavMir** [CosmWasm/wasmd#543]
While running `wasmd query wasm list-code $NODE` to figure out the number of nodes, the code is failing with the following error: `Error: error unmarshalling result: unknown field "proof" in types.ResponseQuery`.

System: Ubuntu 20.04, running latest wasmd release.

**Comment by ethanfrey** [comment]
You are running `wasmd 0.17` locally?
What version is running on the server? If you are pointing to any live chain/testnet I know of, I doubt it is 0.17, even Oysternet is wasmd 0.16

**Comment by AbhinavMir** [comment]
@ethanfrey Sorry for the late reply. I am running `0.17.0-23-g6a6d6c9` version.

**Comment by ethanfrey** [comment]
We are only supporting full releases, not main/master. Also I highly recommend never running main/master on a server.

If you are running `0.17.0-23-g6a6d6c9` on the cli and `0.16` (or earlier) on the server, there is very likely a mismatch.

**Comment by alpe** [comment]
I can not confirm this issue (on OSX). I have run the query against Oysternet:
```sh
wasmd query wasm list-code --node=http://rpc.oysternet.cosmwasm.com:80
``` 
Tested versions: `6a6d6c9` and current master `c05df88`. Both worked as expected.

I am closing this issue now. Feel free to open it again with more details on the server version/ OS setup.
It may be easier though to reach out on [discord](https://discord.com/invite/cPjEnPd).
