### ISSUE TITLE
Store wasmvm version with ContractInfo

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#547]
Useful metadata for backwards compatibility.

This data is currently not available in the [AnalysisReport](https://github.com/CosmWasm/wasmvm/blob/v0.15.0/types/types.go#L62)

Not sure what's the best strategy to provide the data. It could also be received on WasmVM instantiation.

**Comment by ethanfrey** [comment]
I am unclear what version you mean.

- the wasmvm go tag?
- the cosmwasm-vm crate version?
- the `interface_version_6` or whatever export is stored in the contract which determines compatibility?

**Comment by alpe** [comment]
I had the interface version in mind so that we can provide provide this for a backwards compatibility.

**Comment by ethanfrey** [comment]
Replaced by #574 
That may make it in 0.18.0 or 1.0.0
