### ISSUE TITLE
Revisit fee for wasm msg size

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#553]
With the new deserialization fee in wasmvm we charge twice

**Comment by webmaster128** [comment]
Could you elaborate what we charge twice and where?

`wasmvm` charges for the work done in `wasmvm` (the deserialization from the contract's binary response into structures). `wasmd` should charge for any work performed after that.

**Comment by alpe** [comment]
In the gas register we multiply the incoming message size by a factor see https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/gas_register.go#L127 .

**Comment by webmaster128** [comment]
But this is the input into the contract, not the output. So it does not duplicate the new deserialization fee in wasmvm.

However, the deserialization of input messages is executed in Wasm and metered there. So if there is no significant work in wasmd at this point, we can reconsider the linked fee.
