### ISSUE TITLE
SecTrustedApplicationCreateFromPath Problem

### ISSUE THREAD

**Issue by narawit0** [CosmWasm/wasmd#554]
I saw the issue was fixed on this [#60](https://github.com/keybase/go-keychain/pull/60).
But it stills happened on my mac

go install -mod=readonly -tags "netgo,ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=wasm -X github.com/cosmos/cosmos-sdk/version.AppName=wasmd -X github.com/cosmos/cosmos-sdk/version.Version=0.16.0 -X github.com/cosmos/cosmos-sdk/version.Commit=5eb3ae79ca31548bcf1eba730e4bd0e7fa51010b -X github.com/CosmWasm/wasmd/app.Bech32Prefix=wasm -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"' -trimpath ./cmd/wasmd
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:60:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here

**Comment by ethanfrey** [comment]
Oof, there is some ancient keychain being used here: https://github.com/CosmWasm/wasmd/blob/v0.16.0/go.sum#L326

Which comes from the cosmos-sdk https://github.com/cosmos/cosmos-sdk/blob/master/go.sum#L468 :cry: 

Can you please:

1. Try a local fix (I don't have a mac)
2. Report this on the cosmos-sdk repo (asking for backport to v0.42.x) and link this issue (I will add a comment to bump it up)

For the local fix:

1. Fork wasmd
2. `go get github.com/keybase/go-keychain@976c83ec27a644338b5e12baeb4ed6e8f7f863a9` which should update `go.mod` and `go.sum`
3. `make install`
4. Ensure it works properly
5. Make a PR on wasmd

Happy to merge the work-around if this works, but it really needs to be in the cosmos-sdk IMO

**Comment by alpe** [comment]
Thanks for bringing this up!
I see this issue on my mac every time I build wasmd binary. It is annoying but I agree with @ethanfrey that the upgrade needs to go into cosmos-sdk. 
I don't want to push you around but Wasmd is a library with an `app` as a demo to make the integration easier. Key management is done in the cosmos-sdk.
