### ISSUE TITLE
Update to wasmvm / cosmwasm 0.16

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#557]
There will be one more update before

Key Changes:
- Lots of changes to the `IbcChannel*Msg` types
- CounterPartyVersion is no longer in `IbcChannel` but in some of those messages
- Change standard `contract_address` event attribute (for `wasm` type) to `_contract_address`.
- Enforce the contract cannot return any `_*` attributes and thus conflict with any special "trusted" attributes from the runtime.
- Handle custom events from `IbcBasicResponse` and `IbcReceiveResponse` (not just attributes)

**Comment by webmaster128** [comment]
> `contract_address event attribute (for `wasm` type) to `_contract_address`.

This affects custom events as well. Alex started injecting wasmd attributes into those as well to make it possible to trust the origin of those events (see `contractSDKEventAttributes` in https://github.com/CosmWasm/wasmd/pull/548). This makes reserving all `_*` more important and powerful. You then get the guarantee that all `_*` attributes are written by wasmd, not the contract.
