### ISSUE TITLE
Bump proto definitions to version 1

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#558]
The Cosmos SDK [is struggeling](https://github.com/cosmos/cosmos-sdk/issues/9446) with protobuf version changes to the degree that it becomes clear releasing Stargate with "v1beta1" [was a mistake](https://github.com/cosmos/cosmos-sdk/issues/9445). The plan is not to use the simple linear versioning with "v1" from 0.44 on (https://github.com/cosmos/cosmos-sdk/issues/9446#issuecomment-857828835).

We can avoid repeating this mistake and start the version counting now with v1.

Proposed changes in v1:

- [x] `MsgMigrateContract.migrateMsg` -> `.msg` (analogue to MsgExecuteContract)
- [x] `MsgInstantiateContract.initMsg` -> `.msg` (analogue to MsgExecuteContract)

**Comment by ethanfrey** [comment]
Yeah, backwards compatibility is a bit harder than it looks like. And hiding behind "beta" doesn't really help when the code is on many main nets.

Let's make a final v1 and stick with it.

**Comment by webmaster128** [comment]
v1 should be the protobuf version for 0.18. If we need a v2, v3, v4, … on the way to wasmd 1.0, then this is fine. Clients can handle it.
