### ISSUE TITLE
Split Connect/Close callbacks in IbcContract interface into 2 variants.

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#561]
Question: do we want to do so?

We use an argument to construct IbcConnectInit or IbcConnectTry from an IbcConnectOpen callback. We could split this into 2 methods, or we could use a IbcConnectOpenMsg as an argument (which captures the 2 variants).

It could definitely be cleaner than mine, which I did to make minimal changes. I'd like feedback from @alpe to do this.

**Comment by alpe** [comment]
The new types are cleaner in wasmd so I like them. Though they push the complexity of handling more cases upstream.

**Comment by ethanfrey** [comment]
The work in cosmwasm is nice, such that you can call a helper `msg.channel()` to get the information common to both variants and not care about which one (as now), or actually switch on variant (if you care).

It is quite nice actually, from a fair bit of back and forth. At least it provides the contracts the *possibility* of handling the different events differently
