### ISSUE TITLE
Documentation: Code Pinning

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/wasmd#579]
Code Pinning is a powerful but underrated and under documented tooling.
It would be great to put some information about it under a document so I can move to docs.

- What is Code pinning?
- Benefits?
- How to enable?
- How to configure?

**Comment by orkunkl** [comment]
Documentation is up https://docs.cosmwasm.com/docs/1.0/smart-contracts/components/code-pinning/

**Comment by alpe** [comment]
Thanks for keeping an 👁️  on this!
