### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by husio** [CosmWasm/wasmd#595]
This issue is a container for ideas on how the application and the code could be improved. Not everything might be valid as I am learning the code base.

- [ ] use [`goimport`](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) as your code formatter :wink: 
- [ ] Always wrap returned errors. Doing `if err != nil { return err }` does not include each callers' context. Pushing errors up the stack without context makes it harder to test and debug. Additionally, a short context description makes it easier for the reader to understand the code. Example:
https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go#L334-L338
   It would be an improvement to return 
  ```go
   return nil, sdkerror.Wrap(err, "lock contract coins")
   ```
   Please notice that [`fmt.Errorf` is not used](https://github.com/CosmWasm/wasmd/issues/595#issuecomment-900904231), because the error handling predates `fmt.Errorf` and `errors.Is`
- [ ] Update tests so that mock objects own the data they modify. To describe the case, let's focus on a single test:
  https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/handler_plugin_test.go#L72-L75
   `gotMsgs` is a reference to a slice that is carried and modified by `NewCapturingMessageHandler`. Because it is used in all test cases, internal state of the mock requires resetting.
   I think it would be cleaner to apply two modifications to such test:
      1. make each mock own its internal state. In this case, instead of passing `gotMsgs` reference, let the mock own the slice and expose it via an attribute or a method.
      2. where can be done, move mock creation inside of each test case. Sharing mutable mocks breaks the islocation and tests can influence one another. When mocks are isolated, there is no need to reset them.

- [ ] Limit the use of aliases, when not used during the refactoring process. 
    I only briefly know the alias functionality story in Go. Apparently in 1.9 the current implementation fianlly landed ([issue](https://github.com/golang/go/issues/18130) and [proposal](https://go.googlesource.com/proposal/+/master/design/18130-type-alias.md)).
   My understanding of alias functionality is that this functionality is meant as a temporary mean during big code base refactoring. Using an alias allows gradually introducing an otherwise breaking change. 
   `x/wasmd` has a dedicated [`alias.go` file](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/alias.go). It seems like this file is a conscious decision rather than an in process refactoring state. Not sure what are consequences of this approach, maybe it is something worth looking deeper into.

**Comment by ethanfrey** [comment]
> return nil, fmt.Errorf("lock contract coins: %w", err)

The comment is valid, but syntax-wise we we wrap errors (they ported much of that from weave), so it would be `sdkerrors.Wrap(err, "lock contract coins")` or something like that.

Whether we want to wrap on every level is a question for Alex
