### ISSUE TITLE
Add transaction index implemented as counter

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/wasmd#601]
We'd like to expose the index of a transaction in a block in https://github.com/CosmWasm/cosmwasm/pull/1077. This allows contracts to get a pair `(block height, transaction index)` that uniquely identifies the transaction on a given chain. This transaction index should be easy to work with in other tools, e.g. by looking in a block explorer or using a call like

```
curl -sS "https://rpc.cosmos-hub.app.beta.starport.cloud/block?height=7590762" | jq .result.block.data.txs
```

In https://github.com/CosmWasm/wasmd/blob/v0.18.0/proto/cosmwasm/wasm/v1/types.proto#L123-L131 the gas meter is used for ordering, but the values from this are hard to work with. So what we look for is an 0-based index 0, 1, 2, ….

**Comment by ethanfrey** [comment]
Good request. And made me curious was tx[5] is?  It is about 23KB after base64 decoding...

A pdf embedded in a gov proposal?
