### ISSUE TITLE
Fix bug in query handler initialization on reply

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#604]
🙅 https://github.com/CosmWasm/wasmd/blob/v0.18.0/x/wasm/keeper/keeper.go#L486-L489

**Comment by ethanfrey** [comment]
Good find. Let's patch this.

**Comment by alpe** [comment]
A fix would be consensus breaking. Moving this to v0.19.0

**Comment by ethanfrey** [comment]
I agree. Let's merge and get in a 0.19.0 sometime soonish...

I guess this needs a x/upgrade on any chains. But no migration needed.
