### ISSUE TITLE
Optimize BalanceQuery in query plugin

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#606]
We can use [GetBalance](https://github.com/cosmos/cosmos-sdk/blob/v0.42.9/x/bank/keeper/view.go#L26) now instead of iterating through the list

**Comment by ethanfrey** [comment]
Very good point and much more efficient. This is why there were two different queries in the first place.

I was surprised to find https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/query_plugins.go#L171-L178 wasn't updated after the Stargate upgrade. But so many things to do there.
