### ISSUE TITLE
Inconsistent return of `contractAddress` from `keeper/init()`?

### ISSUE THREAD

**Issue by assafmo** [CosmWasm/wasmd#616]
Hi guys 👋, when there are errors in `keeper/init()`, why is `contractAddress` returned here [[1]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L291)[[2]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L281) but not here [[1]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L241)[[2]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L255)[[3]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L261)[[4]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L297)[[5]](https://github.com/CosmWasm/wasmd/blob/93e2e669402dd96b99f223bc6176abef6e794455/x/wasm/keeper/keeper.go?plain=1#L316)?

**Comment by alpe** [comment]
Good 👁️ . In idiomatic Go all other values should be ignored when an error is returned. Therefore the `contractAddress` should have no effect. But we can clearly improve this by returning `nil` in all error cases. 
Do you want to do the PR?

**Comment by assafmo** [comment]
Yeah, sure. Thanks for confirming.

**Comment by ethanfrey** [comment]
Also, in the sdk, when you return an error result, all events and data from the execution are ignored, just an error message is returned. So for the client, this is always invisible.
