### ISSUE TITLE
Update to wasmvm 1.0.0-soon2

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#624]
The main change needed is "Increase gas multiplier by 150_000 to 15_000_000" from #618 

@webmaster128 knows if there is anything else the wasmd runtime needs to be aware of. We added support for WasmQuery::ContractInfo already.

**Comment by webmaster128** [comment]
Release here: https://github.com/CosmWasm/wasmvm/releases/tag/v1.0.0-soon2
