### ISSUE TITLE
Test IBC edge cases

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#660]
Some scenarios to test:
- Can a contract close an ICS20 channel?
- Can a contract send data on a ICS20 counterparty channel?
- Can a contract send data to a ICS20 channel (local loop)?

- Can a contract close a wasm ibc channel that is not owned by the contract?
- Can a contract send data on a different's contract IBC counterparty channel ?
- Can a contract send data to a different's contract IBC channel (local loop)?

**Comment by catShaark** [comment]
@alpe, is this task still relevant ?

**Comment by alpe** [comment]
Closing this now. We have good test coverage and no issues were reported on this from mainnets.
