### ISSUE TITLE
Prevent infinite gas consumption in simulation queries

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#670]
- configurable per node
- default to block gas limit
- must not affect consensus

After some deeper analysis and discussion on #655 in our internal discord with @ethanfrey and @webmaster128 ,
we decided on a new path to solve the root cause. Or what may was the the root cause from the original issue on T.
No further infos provided 🤷‍♂️  
The problem described in #655 addresses only a subset of fraud scenarios as simulations run in the sdk with [infinite gas](https://github.com/cosmos/cosmos-sdk/blob/v0.42.10/x/auth/ante/setup.go#L71-L72)

**Comment by ethanfrey** [comment]
good one
