### ISSUE TITLE
`wasmd` should allow `PinCodesProposal`

### ISSUE THREAD

**Issue by elsehow** [CosmWasm/wasmd#686]
Currently, wasm supports [submitting proposals to pin and unpin code IDs](https://github.com/CosmWasm/wasmd/blob/master/proto/cosmwasm/wasm/v1/proposal.proto#L94-L118), but `wasmd` does not support these proposals [through `tx gov submit-proposal`](https://github.com/CosmWasm/wasmd/blob/dd390d7f5fe8d918bb78575cae98da6058fe8acb/x/wasm/client/cli/gov_tx.go#L92).

`wasmd` should support a command like:

```
wasmd tx gov submit-proposal pin-codes
```

**Comment by ethanfrey** [comment]
I believe this was closed by https://github.com/CosmWasm/wasmd/pull/707

Please re-open if something more is needed
