### ISSUE TITLE
Use proper SystemError::NoSuchContract on ContractInfo if missing

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#687]
We return "normal" SDK errors rather than cosmwasm errors on many cases. This just gives strings to the contracts, which are not the most useful if we need to check if a contract is missing or not.

Let's make sure to return the proper wasmvm SystemErr type for these cases (at least missing contract).

Context (and workaround): https://github.com/confio/tgrade-contracts/pull/368/files#diff-25abef21c13511fbb128155747fbe8e908d0827b23e56ab0718c0c1b52acb44eR1206-R1215

**Comment by ethanfrey** [comment]
For "proper" errors, see https://github.com/CosmWasm/wasmvm/blob/v0.16.0/types/systemerror.go#L8-L16

You need to do something like:

```go
err := wasmvmtypes.SystemError{
  NoSuchContract: &wasmvmtypes.NoSuchContract{
    Addr: contractAddr,
  },
}
```

**Comment by ethanfrey** [comment]
To see why it works when you return this type (and not sdk.Error), see:

`RustQuery`: https://github.com/CosmWasm/wasmvm/blob/v0.16.0/types/queries.go#L36-L52

`ToQuerierResult`: https://github.com/CosmWasm/wasmvm/blob/v0.16.0/types/queries.go#L60-L79

`ToSystemError`: https://github.com/CosmWasm/wasmvm/blob/12c336647f937183884fa52997ca9486d9a219e8/types/systemerror.go#L93

Actually, looking at this, we can simplify the above:

```go
return nil, wasmvmtypes.NoSuchContract{ Addr: contractAddr }
```

**Comment by ethanfrey** [comment]
By not returning SystemErr, you [fall into this case](https://github.com/CosmWasm/wasmvm/blob/v0.16.0/types/queries.go#L74-L78):

```go
	return QuerierResult{
		Ok: &QueryResponse{
			Err: err.Error(),
		},
	}
```

Which says the contract was called and returned an error. We should use the SystemErrors when appropriate to communicate such info. Also any query to a non-existent contract should return this error, not 'not found' or empty bytes.

**Comment by ethanfrey** [comment]
`InvalidRequest` and `InvalidResponse` are meant to be used for parsing errors.
Other ones are not needed AFAIK.

**Comment by alpe** [comment]
Thanks for the additional details!

**Comment by maurolacy** [comment]
I would like to take a stab at fixing / standardizing this.

**Comment by maurolacy** [comment]
Note for a future improvement: This is still incomplete in that the (key) "not found" error is still untyped.

**Comment by webmaster128** [comment]
> This is still incomplete in that the (key) "not found" error is still untyped / generic.

Which "not found" error are you referring to exactly? This one?


```go
	// ErrNotFound error for an entry not found in the store
	ErrNotFound = sdkErrors.Register(DefaultCodespace, 8, "not found")
```

**Comment by maurolacy** [comment]
> > This is still incomplete in that the (key) "not found" error is still untyped / generic.
> 
> Which "not found" error are you referring to exactly? This one?
> 
> ```go
> 	// ErrNotFound error for an entry not found in the store
> 	ErrNotFound = sdkErrors.Register(DefaultCodespace, 8, "not found")
> ```

I think so, yes.

**Comment by alpe** [comment]
This is true, I found some more cases that should be changed. I have opened https://github.com/CosmWasm/wasmd/issues/1258 to follow up
