### ISSUE TITLE
Smart query result is converted to string

### ISSUE THREAD

**Issue by webmaster128** [cosmwasm/wasmd#69]
In https://github.com/cosmwasm/wasmd/blob/v0.0.3/x/wasm/client/rest/query.go#L173, the smart query result is converted to a string. However, this is raw binary data with no guarantee of being UTF-8 (see also https://github.com/confio/cosmwasm/issues/144).

I don't know what Go's `string(bytes)` function does, but as far as I can see it adds no UTF-8 guarantee. Otherwise there would be a potential error to be handled. So it is probably possible to crash the JSON encoder when feeding this with non-UFT8 binary data.

**Comment by webmaster128** [comment]
The invalid UTF-8 bytes get converted to question mark symbols. This is a new query for Hackatom:

<img width="629" alt="Bildschirmfoto 2020-02-10 um 00 29 12" src="https://user-images.githubusercontent.com/2603011/74112365-659d2400-4b9c-11ea-9b5a-6a71254551e9.png">

Which results in a null character followed by two REPLACEMENT CHARACTER �.

```
$ curl http://localhost:1317/wasm/contract/cosmos18vd8fpwxzck93qlwghaj6arh4p7c5n89uzcee5/smart/7b22627265616b223a7b7d7d\?encoding=hex
{"height":"0","result":"\u0000\ufffd\ufffd"}
```

**Comment by ethanfrey** [comment]
All the data from the smart contract is raw bytes and we should take one of two approaches:

1. Require it to be valid json data, and *assert that or error* in the server. Then return the deserialized object over REST.
2. Allow any valid binary data here, and just encode it in base64 (standard byte slice encoding)

Note, we use `json.RawMessage` for the contract message when we submit an Instantiate or Execute transaction. This asserts a valid ut8 json string when parsing. For return data... we should be clearer for sure. At least consistent.

Which do you prefer - assert valid json, or base64 encode any binary data? Or do you have another idea? 

I'd love to sort this out and then cut 0.6.0

**Comment by webmaster128** [comment]
For 0.6.0 I'd stick to passing binary data from contract to client. We have contracts returning JSON bytes and contracts returning string bytes directly, so enforcing JSON would be a major breaking change.

Let's just avoid the invalid conversion to string and do proper base64 encoding.
