### ISSUE TITLE
wasmd tx wasm 

### ISSUE THREAD

**Issue by wotori** [CosmWasm/wasmd#695]
Hello everyone. Just looking for answer, Is It possible to run this command `wasmd tx wasm store` without cli asking the password? Can I pass data somehow into the command to make everything happen in just one commands?

**Comment by alpe** [comment]
It is not recommended but you can pipe the password like we do in our [test example scripts](https://github.com/CosmWasm/wasmd/blob/master/contrib/local/setup_wasmd.sh#L21)
Another option would be to use the `test` keyring-backend via `--keyring-backend=test` and `--keyring-dir`.

Beside these test scenarios, be aware that  **the password is there for a good reason.**
For follow up questions, please consider using our [discord](https://discord.com/invite/cPjEnPd) to get answers quicker
