### ISSUE TITLE
Change SDKMessageHandler to accept an interface

### ISSUE THREAD

**Issue by channa-figure** [CosmWasm/wasmd#696]
## Summary

The Provenance team has been working on a feature for adding addition fees for messages.  We ran into an issue with the `MsgServiceRouter` being a struct instead of an interface.  This caused an issue with trying to customize the behavior of message handling to fit our needs, i.e. we needed to add additional charges to msgs that were dispatched by a wasm contract.  We ended up making a fork of the cosmos-sdk and adding interface to the `MsgServiceRouter`.  We also changed the wasmd module's `SDKMessageHandler` to accept that interface: [change on our wasmd fork](https://github.com/CosmWasm/wasmd/commit/86a7c964346321a399229025abbb8b3a727afef4)   

## Proposal

Change the `SDKMessageHandler` to accept an interface for the `MsgServiceRouter` to allow users to inject custom behavior on msg routing.

**Comment by iramiller** [comment]
This is really only needed on the 0.44.x series as the upcoming middleware refactor provides ways to control the behavior of the system we are looking for.

**Comment by ethanfrey** [comment]
I like the idea of making it more extensible. And the general Go maxim "interfaces in, structs out"

Unless Alex sees a code issue here, I approve the idea. The current calling code should work unchanged, we just allow more possibilities

**Comment by alpe** [comment]
An interface makes perfect sense. Thanks for highlighting your use case 👍

**Comment by alpe** [comment]
This was implemented
