### ISSUE TITLE
interface_version_*: store wasm contract failed: invalid request

### ISSUE THREAD

**Issue by Unirealchaindev** [CosmWasm/wasmd#704]
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract missing a required marker export: interface_version_*: store wasm contract failed: invalid request

**Comment by alpe** [comment]
CosmWasm checks the [compatibilty](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md#compatibility) of your contract. It seems that you were not providing the proper interface.
Please check out the `#smart-contract` channel on our [discord-server](https://discord.com/invite/cPjEnPd). I am sure you will find help when you provide additional information about your contract and what you are trying to do
