### ISSUE TITLE
Publish protobuf files to https://buf.build/

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#706]
Inspired by https://github.com/CosmWasm/wasmd/issues/705

**Comment by ethanfrey** [comment]
Seems like a good idea and becoming cosmos-sdk standard.

@marbar3778 I think you were working with the buf tooling. Can you comment here re best practices in the Cosmos ecosystem?

**Comment by marbar3778** [comment]
It looks like the repo is set up as but recommends. Id suggest migrating to v1 buf and publishing. But released the docs page recently and its become super useful

**Comment by ethanfrey** [comment]
I hate auto-correct... seems like it did `s/buf/but/g` above.
But thanks for the info

**Comment by egaxhaj-figure** [comment]
This is great! 👍

**Comment by ethanfrey** [comment]
Link to cosmos-sdk issue.
Connect Pino with MarBar

**Comment by marbar3778** [comment]
here is how we do it in the sdk https://github.com/cosmos/cosmos-sdk/blob/master/.github/workflows/proto-registry.yml

**Comment by ethanfrey** [comment]
Thanks @marbar3778 

Also, Pino: Other buf.build task/pr (maybe useful to look at?) https://github.com/confio/ics23/pull/59
