### ISSUE TITLE
CosmWasm: Setup Go CLI NOT working -> Testnet-Sandynet issues not connected ?

### ISSUE THREAD

**Issue by conceptstom** [CosmWasm/wasmd#709]
Hello!
Running a WSL2 on Windows 10
I follow the instructions strictly carefully in the docs of the CosmWasm installation and setup.
The wasmd is now correctly installed and is in the folder: Home dir : \\wsl$\Ubuntu-20.04\home\tomcatzy\go\bin
Let's configure the wasmd executable, point it to the testnet, create a wallet and ask for tokens from faucet:
First source the sandynet network configuration in the shell:
        source <(curl -sSL https://raw.githubusercontent.com/CosmWasm/testnets/master/sandynet-1/defaults.env)
Setup the client:

![Skærmbillede 2021-12-27 03 09 19](https://user-images.githubusercontent.com/8062795/147436602-3a249421-4c99-4631-b63e-0dce29b551ec.png)
}
The wasmd won't obviously connect to the  testnet - Sandynet https://rpc.sandynet.cosmwasm.com
I don't get there to point to the testnet wasmd and creat to the wallet...

Anybody with the same problems -and any suggestions ?
Please much appreciated.

**Comment by ethanfrey** [comment]
Okay, this is an issue with WSL2 trying to use the native keyring system. There may be a workaround for DBUS issue, but I am unsure and this would be logged somewhere in https://github.com/cosmos/cosmos-sdk/issues

As a workaround for development (do not use this for real networks) there are some flags in `wasmd keys --help`. Particularly:

```
      --keyring-backend string   Select keyring's backend (os|file|test) (default "os")
```

Try with `--keyring-backend file` and it will store to an encrypted file on disk and not mess around with dbus. You will want to add this to all your TXFLAGS as well

**Comment by conceptstom** [comment]
> 
Thanks for your thoroughly and informative reply - and time.
Much appreciated.
Followed your advice and ran the:  wasmd keys add wallet --keyring-backend test(instead of your suggested 'file')
The result after creating the two wallets: Wallet and Wallet2 ->
![Skærmbillede 2021-12-28 02 52 44](https://user-images.githubusercontent.com/8062795/147520305-9cceca08-4d45-4f84-b7b1-bf0f51402eed.png)
![Skærmbillede 2021-12-28 03 07 06](https://user-images.githubusercontent.com/8062795/147520320-654478db-caa2-4139-8da8-d9e9cb269e5d.png)
Both wallets as seen in both screenshots comes up with - type: Local 
I don't know if this - local - is meant to be on my local machine or if it's gooing along with the testnet Sandynet-1 as realy was my purpose for all testing regarding cosmwasm ?
The 'test' flag is from the docs at Cosmos - The 'test' backend : https://docs.cosmos.network/master/run-node/keyring.html

**Comment by ethanfrey** [comment]
I can't really dig in more here, but iff you add that flag `-keyring-backend` you must add it to every call of `wasmd keys`

This means, in `$(wasmd keys show -a ...)` when creating the JSON as well.

There use to be config files and env variables that would set these flags globally... this was removed in the Stargate upgrade and I am still wishing for them. (But this is upstream in the Cosmos SDK)

**Comment by conceptstom** [comment]
> 
Defenetly it sems to be working with the flag consequently from step to step: -keyring-backend test

JSON=$(jq -n --arg addr $(wasmd keys show -a wallet) '{"denom":"ubay","address":$addr}') && curl -X POST --header "Content-Type: application/json" --data "$JSON" https://faucet.sandynet.cosmwasm.com/credit

# bash
export NODE="--node $RPC"
export TXFLAG="${NODE} --chain-id ${CHAIN_ID} --gas-prices 0.025ubay --gas auto --gas-adjustment 1.3"

wasmd query bank total $NODE

The working results ->

![Skærmbillede 2021-12-29 02 03 21](https://user-images.githubusercontent.com/8062795/147618054-2ac723d8-2623-4ce8-85c0-d6b5f4643cb4.png)

**Comment by ethanfrey** [comment]
Glad I could help.

**Comment by alpe** [comment]
Closing this now. If there are any follow up questions, please consider using our [discord](https://discord.com/invite/cPjEnPd) for faster feedback.
