### ISSUE TITLE
Some wasmd commands doesn't run in WSL. A lot of failures...

### ISSUE THREAD

**Issue by conceptstom** [CosmWasm/wasmd#712]
WSL2 Linux terminal: 
Wallets and genesis-file created in /.wasm/config folder
Fred = KeyName
APP_HOME="~/.wasmd"
Add Fred's address as validator's address
wasmd gentx --name fred --home ${APP_HOME}
Then i get this result ->
![Skærmbillede 2022-01-03 04 30 33](https://user-images.githubusercontent.com/8062795/147898070-48a243c6-2d17-467e-a4c3-eaa2c910f618.png)
Also following the docs in - Uploading and Interacting - from the main docs in Cosmwasm comes up with failures...

**Comment by alpe** [comment]
You have passed the key via "--name" which is not correct and you are missing some other arguments. The CLI output shows an example in the "usage" section. It is easy to miss if you are not used to [cobra](https://github.com/spf13/cobra) outputs.

The format should be like this: `wasmd gentx validator "250000000STAKE" --chain-id="my-chain" --amount="250000000STAKE"`
You can find a working example in the contrib folder: https://github.com/CosmWasm/wasmd/blob/master/contrib/local/setup_wasmd.sh#L33

You may get faster feedback on our [discord](https://discord.com/invite/cPjEnPd)

**Comment by conceptstom** [comment]
> 

Hi
Thanks for reply.
If i run your suffested format: wasmd gentx validator "250000000$STAKE" --chain-id="$CHAIN_ID" --amount="250000000$STAKE" 
As stated in https://github.com/CosmWasm/wasmd/blob/master/contrib/local/setup_wasmd.sh#L33
Theb i get this result ->
![Skærmbillede 2022-01-04 08 17 46](https://user-images.githubusercontent.com/8062795/148023218-8f34794c-4859-4035-ad8e-3ea8adca6e59.png)

**Comment by alpe** [comment]
@conceptstom please consider using our discord server for support questions. This issue is not a bug or general question that requires some some doc updates. The error message on your screenshot contains the root cause. Your genesis file is not valid.

**Comment by conceptstom** [comment]
> @conceptstom please consider using our discord server for support questions. This issue is not a bug or general question that requires some some doc updates. The error message on your screenshot contains the root cause. Your genesis file is not valid.

Thanks! for your recomendation regarding joining the discord channel. I've accepted the invitation and joined the channel now.
