### ISSUE TITLE
node's tendermint validator info

### ISSUE THREAD

**Issue by migmeneses** [CosmWasm/wasmd#735]
for wasmd v0.22.0

the sysntax:
```wasmd tendermint show-validator```
is not showing the right format:

Previusly on wasmd 0.21.0
```wasmvalconspub1zcjduepqaf8hfa625je7yapckr9r7sy5umjg8kfyysmlv3ckl709a478dfeq0hxtr4```

and now on wasmd 0.22.0
```{"@type":"/cosmos.crypto.ed25519.PubKey","key":"GIsPhzwYnrc2PX8fIpXVveZxGT4GKBLhpTNZxuQtQKU="}```

**Comment by ethanfrey** [comment]
Can you raise this issue on https://github.com/cosmos/cosmos-sdk ?

For their notes, wasmd 0.21 uses cosmos sdk 0.42.x and wasmd 0.22 uses cosmos sdk 0.45.0

Maybe check the [CHANGELOG](https://github.com/cosmos/cosmos-sdk/blob/master/CHANGELOG.md) if they documented this change before rising the issue. (Most commands not directly related to cosmwasm are simply inherited from the cosmos-sdk)

**Comment by migmeneses** [comment]
I could not find it in the CHANGELOG

Therefore, I filed a new issue where you requested:
https://github.com/cosmos/cosmos-sdk/issues/11046

**Comment by alpe** [comment]
This makes sense now with the changes in the SDK. 
Before a bech32 address was generated for the pubkey and submitted via gentx/create validator. Now this has changed to the json representation of the pubkey in the [MsgCreateValidator](https://github.com/cosmos/cosmos-sdk/blob/v0.45.0/proto/cosmos/staking/v1beta1/tx.proto#L49)

**Comment by migmeneses** [comment]
"This is the correct format. Public keys were never meant to be bech32 encoded and such functionality was removed.
Going to close the issue, but feel free to comment on it and re-open it if you need more details."
...Aleksandr Bezobchuk

Can I close the case/issue?
