### ISSUE TITLE
Custom client codec crashes with Rosetta enabled

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#749]
We use a custom client [codec](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/client/codec/marshaller.go) to not print empty elements. This unfortunately does not work with the current sdk (v0.45.1 + current master) and creates:

`panic: interface conversion: codec.Codec is *codec.ProtoCodec, not *codec.ProtoCodec (types from different packages)`

Root cause for this panic is the [type cast in the sdk](https://github.com/cosmos/cosmos-sdk/blob/v0.45.1/server/start.go#L355)

**Comment by ethanfrey** [comment]
So, we just use the standard codec?
Does this break anything?

**Comment by alpe** [comment]
Standard codec would be the quickest solution. On the downside, we end up with empty fields in genesis and cli json outputs.
I was thinking to open an issue with the sdk to address the cast, which should not be there IMHO but their workload is high already and we can solve this completely with standard codec.

**Comment by ethanfrey** [comment]
I think the first solution to use standard codec is better. It only seems to have cosmetic issues.

I would support an upstream PR on Cosmos SDK to support custom codecs, or even make this "non-empty field" codec the default. But that would have to come from us and not wait for their work.
