### ISSUE TITLE
list contracts by code id doesn't contain addresses

### ISSUE THREAD

**Issue by ethanfrey** [cosmwasm/wasmd#75]
## Steps to Reproduce

`curl http://demo.cosmwasm.com:1317/wasm/code/1/contracts | jq -r .result`

Result looks like:

```json
[
  {
    "code_id": 1,
    "creator": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
    "init_msg": {
      "decimals": 18,
      "name": "Jade Token",
      "symbol": "JADE",
      "initial_balances": [
        {
          "address": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
          "amount": "189189189000000000000000000"
        },
        {
          "address": "cosmos17d0jcz59jf68g52vq38tuuncmwwjk42u6mcxej",
          "amount": "189500000000000000000"
        }
      ]
    }
  }
]
```

There is no way to see the address of the contract returned (which is needed to call it).

Suggestion:

always return `code_id` and `address` for `ContractInfo` regardless of how we query
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by webmaster128** [comment]
Once we have this, `/wasm/contract` is obsolete, right?

**Comment by ethanfrey** [comment]
Well, that will give you data by contract address, not just code id. It seems fair to allow both ways to query.

**Comment by webmaster128** [comment]
I was referring to the list of addresses `/wasm/contract`, not `/wasm/contract/${address}`

**Comment by ethanfrey** [comment]
Ahh, yeah, that can go as part of any pr that addresses this. Good point
