### ISSUE TITLE
Reduce gas when using governance proposals to store wasm

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#761]
wasm contracts tend to be 200-300kb which is large and expensive.

In order to reduce gas, we already zip the wasm on `wasmd tx wasm store` in order to reduce the tx size by 3x. We never write the wasm to the iavl tree, but to disk directly, where it is handled by Rust code later.

However, I do not believe we perform these optimisations on `wasmd tx gov submit-proposal wasm-store`. We should check.

Also, even if we reduce the tx size, I am almost certain that when we create the proposal, we store the unzipped wasm. Once we validate the syntax (in memory), we can continue to store the original zip data in the proposal (in the IAVL tree) and unzip it when processing a passed proposal before sending it to the Rust library.

Context: when testing this on osmosis, I got surprisingly high gas costs for creating this proposal and for depositing on it (which read and wrote the proposal)

**Comment by jhernandezb** [comment]
I can confirm that the contract is stored compressed in the proposal we use the following to verify the contract checksum
```
# download the contract from the proposal
starsd q gov proposal [proposal-number] -o json | jq -r .content.wasm_byte_code | base64 --decode > contract.wasm.gz

# decompress de contract
gzip -d -c contract.wasm.gz > contract.wasm 

# checksum
sha256sum contract.wasm
```

However this still takes huge amount of gas  to submit a proposal and even after it causes issues for voters, taking almost 1M gas to submit a vote [see example](https://www.mintscan.io/stargaze/txs/003F93DDE4EE8AD86AE1285A05F399F581BCBAE22A84D8F6E83DE1B5F015048B).

Not really sure if there could be a different way to submit proposals for storing code like would it be possible to submit the hash to governance for approval?  and the contract can be uploaded with the regular store command.  Not really familiar with the process of verifying and storing contracts but some wallets doesn't even let the user change the gas param (like Keplr Mobile)

**Comment by ethanfrey** [comment]
Thanks for that check.

I took a brief look at the x/gov module and I don't see how we can somehow store the wasm outside of the contract using the normal submit proposal process.

If someone else wants to dig into the cosmos-sdk and look for some hooks where we can split this in the normal gov process, please do provide that info. The ProposalContent interface doesn't give so much power as far as I can see

**Comment by jhernandezb** [comment]
I looked into this there is a `func (h Hooks) AfterProposalSubmission(ctx sdk.Context, proposalID uint64) {}` hook, but basically it will have to hijack the gov module to remove the blob from the proposal and move  it to it's own storage location, not really fan of this. 

The 2 steps would be nice but maybe adding a store deposit that is released when the proposal ends  to prevent contracts from being uploaded and never removed.

**Comment by ethanfrey** [comment]
I make a proposal how we can handle this with a minor refactor here: https://github.com/CosmWasm/wasmd/issues/785#issuecomment-1067014657

Happy for feedback
