### ISSUE TITLE
Not Able to Instantiate the Contract using governance if admin is not provided

### ISSUE THREAD

**Issue by gitabhishekgit** [CosmWasm/wasmd#768]
no-admin flag is not added while using governance to instantiate the contract.

**Comment by ethanfrey** [comment]
If you do it without `--no-admin` it passes, right?

I believe the issue is we did not add the enforcement of either `--admin XYZ` or `--no-admin` like the normal instantiate and treat a missing `--admin` flag as no admin. Can you verify the current behavior and the desired behavior? Ideally pasting the cli commands you are using,

**Comment by gitabhishekgit** [comment]
It didn't passes if we don't provide the --no-admin flag and gave the below error - 

comdex tx gov submit-proposal instantiate-contract 1 '{"name":"GOOGLE","symbol":"mGOO","decimals":6,"initial_balances":[],"mint":{"cap":null,"minter":"comdex13wp8k2deecj0v38wplk4zc6g533kxw0a9mx940"}}' --label "mint" --title "inst" --description "cont" --run-as $(comdex keys show admin -a)
Enter keyring passphrase:
**Error: no-admin: flag accessed but not defined: no-admin**

**comdex keys show admin -a** here admin is my key name(Please don't get confuse).

If we provide the --no-admin flag, it gives the below error - 

comdex tx gov submit-proposal instantiate-contract 1 '{"name":"GOOGLE","symbol":"mGOO","decimals":6,"initial_balances":[],"mint":{"cap":null,"minter":"comdex13wp8k2deecj0v38wplk4zc6g533kxw0a9mx940"}}' --label "mint" --title "inst" --description "cont" --run-as $(comdex keys show admin -a) --no-admin
Enter keyring passphrase:
**Error: unknown flag: --no-admin**

if we provide the --admin flag, still it gives the below error - 

comdex tx gov submit-proposal instantiate-contract 1 '{"name":"GOOGLE","symbol":"mGOO","decimals":6,"initial_balances":[],"mint":{"cap":null,"minter":"comdex13wp8k2deecj0v38wplk4zc6g533kxw0a9mx940"}}' --label "mint" --title "inst" --description "cont" --run-as $(comdex keys show admin -a) --admin comdex13wp8k2deecj0v38wplk4zc6g533kxw0a9mx940
Enter keyring passphrase:
**Error: no-admin: flag accessed but not defined: no-admin**
