### ISSUE TITLE
Sort instances by creation (/wasm/code/${id}/contracts)

### ISSUE THREAD

**Issue by webmaster128** [cosmwasm/wasmd#78]
Right now, the results in `/wasm/code/${id}/contracts` are sorted unintuitively, probably by address. As a developer, I expect the list to be sorted by instantion order, creating an API that exposes this simple mental model:

- Code 1
  - Instance 1
  - Instance 2
  - Instance 3
- Code 2
  - Instance 1
  - Instance 2

This is the model I would like to present a user in a code explorer.

The order is also important for testing when you e.g. expect the first 3 instances of a token contract are HASH, ISA, JADE no matter which instances are created later on. It also allows you to get the most recent instance, iterating in reverse order.

**Comment by ethanfrey** [comment]
They are sorted by the binary representation of the address (which is not quite the same as sorting by the bech32 display version). This is what we get from iterating over the store, which needs to store via address to allow fast lookups for most queries.

We can add a `created_at_height int64` field and then sort by that in memory when preparing results for the query. Would that solve the issue here?

We will need to revisit this when we add pagination, as this involves loading all contracts in memory before sorting. Other approach would require a sorted secondary index to handle this.

**Comment by webmaster128** [comment]
> We can add a `created_at_height int64` field and then sort by that in memory when preparing results for the query. Would that solve the issue here?

Basically yes. Is there a way to get the (height, transaction number) pair to be correct for multiple transaction in a block?

> We will need to revisit this when we add pagination, as this involves loading all contracts in memory before sorting. Other approach would require a sorted secondary index to handle this.

👍 

I think with size limited list items we can live without pagination for a little while.

**Comment by ethanfrey** [comment]
> Basically yes. Is there a way to get the (height, transaction number) pair to be correct for multiple transaction in a block?

That is a good question. The `Context` provides all info about current blockchain state and contains the following:

```go
func (c Context) Context() context.Context    { return c.ctx }
func (c Context) MultiStore() MultiStore      { return c.ms }
func (c Context) BlockHeight() int64          { return c.header.Height }
func (c Context) BlockTime() time.Time        { return c.header.Time }
func (c Context) ChainID() string             { return c.chainID }
func (c Context) TxBytes() []byte             { return c.txBytes }
func (c Context) Logger() log.Logger          { return c.logger }
func (c Context) VoteInfos() []abci.VoteInfo  { return c.voteInfo }
func (c Context) GasMeter() GasMeter          { return c.gasMeter }
func (c Context) BlockGasMeter() GasMeter     { return c.blockGasMeter }
func (c Context) IsCheckTx() bool             { return c.checkTx }
func (c Context) IsReCheckTx() bool           { return c.recheckTx }
func (c Context) MinGasPrices() DecCoins      { return c.minGasPrice }
func (c Context) EventManager() *EventManager { return c.eventManager }
```

`BlockHeight()` and `BlockTime()` will increase monotonically between blocks, but be the same for any two transactions on the same block.

The only differentiator I can think of is `BlockGasMeter()`, which will decrease monotonically and deterministically between mutliple transactions in the same block.

```go
// Gas measured by the SDK
type Gas = uint64

// GasMeter interface to track gas consumption
type GasMeter interface {
	GasConsumed() Gas
	GasConsumedToLimit() Gas
	Limit() Gas
	ConsumeGas(amount Gas, descriptor string)
	IsPastLimit() bool
	IsOutOfGas() bool
}
```

 So the tuple `(ctx.BlockHeight(), ctx.BlockGasMeter().GasConsumed())` would provide a global ordering of all transactions in the same or different blocks, as `(int64, uint64)`

**Comment by webmaster128** [comment]
Very nice finding! Sounds like a perfectly correct solution as long as each transaction consumes at least 1 gas. I'd just not expose the value, such that we can change the implementation if needed.
