### ISSUE TITLE
Freeze Code ID Proposal

### ISSUE THREAD

**Issue by jhernandezb** [CosmWasm/wasmd#780]
With permissioned CosmWasm chains, it would be nice to freeze code ids from being instantiated. 

Example:  There is a security bug in a code id and a new one is deployed but you want to prevent the old one from being instantiated but at the same time keep previously instantiated contracts to keep running.

**Comment by ethanfrey** [comment]
We have a field that controls who can instantiate a given CodeID, [called `InstantiateConfig`](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/types/types.go#L50). Typically it is "Everybody", but could be set to "Nobody" as is sometimes done in permissioned environments, to only allow the governance mechanism to instantiate that codeID.

If we allowed modifying that field by a gov proposal, that should satisfy your request, right? It would also allow making a restricted codeID free to instantiate by anyone, which is more a permissioned use-case, but nice that one concept can cover a range of uses.

**Comment by jhernandezb** [comment]
Yes! modifying that value through a gov proposal will totally work

**Comment by alpe** [comment]
Thanks for bringing this up. I really like the idea of freezing a code id and releasing it. 💯 
 As Ethan pointed out, this would work with existing authz schema. 

I don't have the steps to implement this well documented but as a start these are the high level steps, in case somebody want to give it a try already:

* Add new type to [proposal.proto](https://github.com/CosmWasm/wasmd/blob/master/proto/cosmwasm/wasm/v1/proposal.proto)
* Run `make proto-all` to generate types from proto

Implementation on the server side:
* Register and implement interface methods in [proposal.go](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/types/proposal.go)
* Add [proposal handler](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/proposal_handler.go).
* Add to [codec](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/types/codec.go)
* Add [integration test](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/proposal_integration_test.go)
* Add to [doc](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/Governance.md)

Client side:
* Add to list of [ProposalHandlers](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/client/proposal_handler.go#L11)
* Add [cli command](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/client/cli/gov_tx.go)
* Verify cli command is in list of `wasmd tx gov submit-proposal -h`
* Add legacy REST [support](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/client/rest/gov.go)

Manual testing
* Build a wasmd binary via `make install`
* Start local instance (see contrib/local)
* Setup system under test and submit proposal

**Comment by jhernandezb** [comment]
I can probably work on this, how this proposal should be called? It's actually updating instantiation permissions so `UpdateInstantiatePermissions` ?

**Comment by alpe** [comment]
💪  great!
The proposal would update the `InstantiateConfig` on CodeInfo. Technically it is not just the "permission" but can also be an address that was accept-listed. 
I don't have a strong opinion on the naming. `UpdateInstantiateConfig` or `SetInstantiateConfig` came to my mind.

**Comment by jhernandezb** [comment]
`UpdateInstantiateConfig` sounds good to me will start working on it this week.
