### ISSUE TITLE
Remove legacy REST endpoints

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#782]
We still have a couple of custom legacy REST [endpoints](https://github.com/CosmWasm/wasmd/tree/master/x/wasm/client/rest) in the wasm module. 
The SDK has [removed](https://github.com/cosmos/cosmos-sdk/pull/9594) them for their modules in the v0.46 alphas and current master already.

The "grpc-rest-gateway" is in place for some versions already and can be used instead.

Time to remove the legacy REST endpoints?

**Comment by jhernandezb** [comment]
We have been using mostly the endpoints from the gateway which are automatically wired from proto generation, and also might be a good idea revisit some of the endpoints  like query ones which takes the payload in the URL instead of taking input from a POST request.

**Comment by jhernandezb** [comment]
any plans on what to do with the legacy endpoints? I think it will be nice to remove them and improve the query endpoint, We do heavily usage of the smart query through rest endpoints but having to encoding it through the URL is a bit of an issue.

Also a multi query endpoint could be useful to avoid round trips.

**Comment by webmaster128** [comment]
> Also a multi query endpoint could be useful to avoid round trips.

This was discussed in https://github.com/CosmWasm/wasmd/issues/72 and we were not convinved this is the right™️ way to do it. Could you explain the use case there? Happy to re-open #72.

**Comment by alpe** [comment]
I have reopened #72. Thanks for the link! 
IMHO it is important that we do our housekeeping and drop the legacy apis in our codebase.

@jhernandezb to buy you more time for the migration, we can keep only the smart query endpoint. Would this work for you?

**Comment by jhernandezb** [comment]
I think we should remove them

**Comment by alpe** [comment]
They are all gone in the sdk v47 branch. No need to backport IMHO
