### ISSUE TITLE
StoreAndInstantiate gov proposal

### ISSUE THREAD

**Issue by jhernandezb** [CosmWasm/wasmd#785]
Would be nice to have a single proposal that does both, specially if the store code is uploaded with instantiate permissions `Nobody` having to wait an entire voting period for store + instantiate might be just too long depending on each chain.

**Comment by alpe** [comment]
👍  Good thinking.

**Comment by ethanfrey** [comment]
I question this.

There is a desire to move away from the whole Store Proposal as it is too heavy to vote on. I would look for another way to do that before we consider adding more Proposals that include the entire wasm blob.

Also, I wonder which project will require votes on both store and instantiate?

This is related to https://github.com/CosmWasm/wasmd/issues/780 and I would consider a small re-architecture. If we do not allow StoreCode message to override the permissions, we could check a lot of boxes for permissioned chains. If we set the default InstanitatePermission to Nobody (which cannot be overridden):

1. StoreCodeMsg, then vote to make one Instantitate.
2. StoreCodeMsg, then vote to open up the permissions to instantiate (#780), then anyone can instantiate without a vote

We could also allow the StoreCodeProposal to set a non-Nobody instantiate permissions if people still want to do this vote, but I think the above two will make this whole flow much easier (and avoid gas intensive votes - see #761 )

**Comment by ethanfrey** [comment]
If you agree on this, I would say #780 plus a new issue to prevent StoreCodeMsg from overriding the InstantiatePermissions (quite simple) would cover this, and #761 as well.

**Comment by jhernandezb** [comment]
That kinda makes sense, I like that it will fix storing the blob inside the proposal, I'd be worried mostly about having a lot of contracts being uploaded and not used, but perhaps that could be solved by setting a fee that can be in a way a bit high for example creating a pool in osmosis costs 100 OSMO iirc, creating an nft collection in stargaze costs 1000 STARS.

**Comment by ethanfrey** [comment]
Then this is a bigger problem for those chains.

You suggest a fee for anti-spam resistance.
The gas fee was introduced for anti-spam resistance.
Let's use it.

If people have such low gas fees it doesn't serve at all to stop spam, then why do they want to only stop this one spam possibility and not the others?

We charge plenty of gas to cover compilation and storage of the upload. You could run a few dozen ibc client updates to achieve a similar result.

**Comment by jhernandezb** [comment]
My point wasn't about anti-spam but preventing contracts from being upload that  would  never be used because  of the nature of a permissioned  cosmwasm chain. For example random people uploading contracts but not submitting a gov proposal. With the current flow if a proposal doesn't pass no contract is stored  and it has a deposit fee.  Moving away from this flow eliminates the fee  and the ability of preventing  uploading in the first place.

**Comment by alpe** [comment]
Just adding some context on customizing wasmd gas values: 
We have an [extension point](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/options.go#L106) prepared that can be used to provide a custom [Gas register](https://github.com/CosmWasm/wasmd/blob/master/x/wasm/keeper/gas_register.go#L139) to match your requirements.

Just from personal experience, not using some project "defaults" may cause communication and support overhead elsewhere ...

**Comment by ethanfrey** [comment]
I would start with #796 and #840 as a useable workflow, aiming for them both in 0.27. And then revisit if this is still necessary for the following v0.28 release

**Comment by pinosu** [comment]
Is this still relevant? Since #796 and #840 are now merged, what is the work left for this issue?

**Comment by alpe** [comment]
There were requests for a single proposal that does upload + instantiate for restricted chains where #840 is not setup.

**Comment by ethanfrey** [comment]
Note that as of cosmos-sdk 0.47, proposals will be much cheaper to vote on... not sure if this impacts the desire for this feature. Maybe @jhernandezb can comment here?

**Comment by jhernandezb** [comment]
> Note that as of cosmos-sdk 0.47, proposals will be much cheaper to vote on... not sure if this impacts the desire for this feature. Maybe @jhernandezb can comment here?

Somehow I missed this, seems like it's closed now thanks! I think is still relevant when you want to save some governance burden eg. waiting 2 complete cycles of governance upload + instantiate.
