### ISSUE TITLE
Add tx query to wasmd QueryPlugins for smart contract 

### ISSUE THREAD

**Issue by catShaark** [CosmWasm/wasmd#788]
I think this will be useful since in some cases, contracts need proof of on chain actions. Tx can't be query with StargateQuerrier.

**Comment by ethanfrey** [comment]
Can you please provide a clear use case where this is essential?
One you are building, not some strawman you can imagine.

It may open up some possible non-determinism calling into tendermint, so adding it will require large amount of testing to ensure there is no issue, especially as many validators run patched tendermint versions.

**Comment by ethanfrey** [comment]
wasmd theory is to limit functionality to what we know is correct. and even there, we keep finding odd corner cases where the cosmos sdk doesn't behave like we assumed it did

**Comment by catShaark** [comment]
I want to make a contract on osmosis that manages fund sent from contracts on juno. For example contract A on juno sent 10 ibc juno to this contract, contract A can now send ibc packet to command this contract on what to do with that fund. Right now, this can be done by ibc-ing juno to some controlled osmosis account and then use that controlled osmosis account to send the ibc juno to this contract. This means that controlled osmosis account must be trusted, if the fund is anything related to gov (community pool fund for example), I think it's really inconvenient.

**Comment by alpe** [comment]
This sounds a bit like interchain accounts or a custom protocol built on top of IBC. We provide some very nice integration with IBC, so that you get all their safety guarantees and do not need to replicate them. 
Have you seen https://github.com/CosmWasm/cosmwasm/blob/main/IBC.md ?
