### ISSUE TITLE
Add instance labels/titles

### ISSUE THREAD

**Issue by webmaster128** [cosmwasm/wasmd#79]
As seen in https://github.com/confio/cosmwasm-examples/pull/40 there is a desire to label different instances of a contract. The functionality that was added into the contract is not needed by the contract itself, so it should live in meta data.

This is nice for testing, naming, branding no matter which contract you instantiate.

Those labels should be in the list `/wasm/code/${id}/contracts`

**Comment by ethanfrey** [comment]
Yes, together with #80 and #75 this should make the list queries much cleaner

**Comment by webmaster128** [comment]
This came to my mind when I saw https://github.com/confio/cosmwasm-examples/pull/40 and thought _does this really belong here? Does the contract functionality even care about such a name?_.

**Comment by ethanfrey** [comment]
You are right, it does not belong there. It was just to provide what this issue would solve
