### ISSUE TITLE
How to import wasm module to another project

### ISSUE THREAD

**Issue by raifpy** [CosmWasm/wasmd#795]
`go get -u -x -v github.com/CosmWasm/wasmd/x/wasmd`
Here my import code. My go version 1.18. 
`go: module github.com/CosmWasm/wasmd@upgrade found (v1.0.0), but does not contain package github.com/CosmWasm/wasmd/x/wasmd`

Also when i try to import root project (`go get -u -x -v github.com/CosmWasm/wasmd
`);

```
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/x/@v/list
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/x/wasmd/@v/list
# get https://proxy.golang.org/github.com/%21cosm%21wasm/@v/list
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/@v/list
# get https://proxy.golang.org/github.com/%21cosm%21wasm/@v/list: 410 Gone (0.194s)
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/@v/list: 200 OK (0.194s)
# get https://proxy.golang.org/github.com/@v/list: 410 Gone (0.195s)
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/x/@v/list: 410 Gone (0.298s)
# get https://proxy.golang.org/github.com/%21cosm%21wasm/wasmd/x/wasmd/@v/list: 410 Gone (2.837s)
go: module github.com/CosmWasm/wasmd@upgrade found (v1.0.0), but does not contain package github.com/CosmWasm/wasmd/x/wasmd

```

So, how can i import as a external module?

**Comment by ethanfrey** [comment]
What about simply `go get github.com/CosmWasm/wasmd`?

Or `go get github.com/CosmWasm/wasmd@v0.24.0`

There is no v1.0.0, which makes `module github.com/CosmWasm/wasmd@upgrade found (v1.0.0)` confusing and a likely symptom of a confusion in the go build system

**Comment by alpe** [comment]
Closing this now. If you have more questions, please join our [discord server](https://chat.cosmwasm.com/)
