### ISSUE TITLE
Move init_msg into contract details

### ISSUE THREAD

**Issue by webmaster128** [cosmwasm/wasmd#80]
Having `init_msg` in e.g. `curl http://localhost:1317/wasm/code/1/contracts | jq -r .result` can easily cause megabytes of list data and is not very scalable. I don't see a use case where this data is needed in a list. Only for an instance detail screen the data is good to have. I think it is sufficient to have the `init_msg` in the instance details at `/wasm/contract/${address}`.

Having instance labels (https://github.com/cosmwasm/wasmd/issues/79) also reduces the need for the init messages.

------

Example output

```json
[
  {
    "code_id": 1,
    "creator": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
    "init_msg": {
      "decimals": 18,
      "name": "Jade Token",
      "symbol": "JADE",
      "initial_balances": [
        {
          "address": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
          "amount": "189189189000000000000000000"
        },
        {
          "address": "cosmos17d0jcz59jf68g52vq38tuuncmwwjk42u6mcxej",
          "amount": "189500000000000000000"
        }
      ]
    }
  },
  {
    "code_id": 1,
    "creator": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
    "init_msg": {
      "decimals": 5,
      "name": "Hash token",
      "symbol": "HASH",
      "initial_balances": [
        {
          "address": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
          "amount": "11"
        },
        {
          "address": "cosmos1cjsxept9rkggzxztslae9ndgpdyt2408lk850u",
          "amount": "12812345"
        },
        {
          "address": "cosmos17d0jcz59jf68g52vq38tuuncmwwjk42u6mcxej",
          "amount": "22004000000"
        }
      ]
    }
  },
  {
    "code_id": 1,
    "creator": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
    "init_msg": {
      "decimals": 0,
      "name": "Isa Token",
      "symbol": "ISA",
      "initial_balances": [
        {
          "address": "cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6",
          "amount": "999999999"
        },
        {
          "address": "cosmos1cjsxept9rkggzxztslae9ndgpdyt2408lk850u",
          "amount": "42"
        }
      ]
    }
  }
]
```

**Comment by ethanfrey** [comment]
I understand the size argument.

However, if we have a list without init_msg, there will be no way to distinguish the contracts - just a more or less random address - you need init_msg to get a list of available erc20 contracts for instance.

First, we will really need pagination here to make it production ready.

Secondly, as a smaller fix (against Dos), I could imagine:
1. only returning init_msg if size less than eg 1kB (and you must ask for details if bigger) OR
2. assuming init_msg is json, just keep top-level primitives (in this case decimals, name, symbol). That should be enough to create a sensible identifier to show the user

**Comment by webmaster128** [comment]
Why is the list of instantiations of any value in production? Anybody can just create a pooly configured instance of something and you can have thousands of them. Ethereum is spammed with ERC20 contracts and you better don't take them seriously. So for any production usage of an instance you need to know exactly which address you want to interact with. Having the list is valueable for debugging and curiosity activity like scrolling through a block explorer. But for those use cases I think https://github.com/cosmwasm/wasmd/issues/79 is simpler, more generic and safer due to size limitation.

**Comment by ethanfrey** [comment]
I didn't see #79 before this. I agree that is a better solution - use a human-defined label (debug info) rather than full init_msg.
