### ISSUE TITLE
Issue Updating uploadAccess Param

### ISSUE THREAD

**Issue by czarcas7ic** [CosmWasm/wasmd#804]
I have tried updating the wasm uploadAccess param on the Osmosis testnet with the following param-change gov prop:
```
{
  "title": "wasm",
  "description": "wasm test",
  "changes": [
    {
      "subspace": "wasm",
      "key": "uploadAccess",
      "value": "AllowEverybody"
    }
  ]
}
```
But keep getting this error:
```
raw_log: 'failed to execute message; message index: 0: key: uploadAccess, value: "AllowEverybody",
  err: json: cannot unmarshal string into Go value of type map[string]json.RawMessage:
  failed to set parameter: invalid proposal content'
```
I have also tried different keys such as CodeUploadAccess and nothing has worked. It could very well be something I am doing wrong, but nothing really stands out.

**Comment by alpe** [comment]
Sorry, the proposal content was not correct. I looked deeper into client and server side encodings and tested successfully a submission with this proposal content:

```json
{
  "title": "Foo",
  "description": "Bar",
  "changes": [
    {
      "subspace": "wasm",
      "key": "uploadAccess",
      "value": {
        "permission": "Everybody"
      }
    }
  ],
  "deposit": ""
}
```

Command used:
```
wasmd tx gov submit-proposal param-change <proposal-json-file> --from validator --chain-id=testing -b block
```

**Comment by czarcas7ic** [comment]
This worked, thank you!
