### ISSUE TITLE
wasmd: command not found

### ISSUE THREAD

**Issue by alpereira7** [CosmWasm/wasmd#821]
Hi, I was following this tutorial:
https://docs.cosmwasm.com/docs/1.0/getting-started/installation/

    git clone https://github.com/CosmWasm/wasmd.git
    cd wasmd
    git checkout v0.23.0
    make install

    # verify the installation
    wasmd version`
    
This returns:
`wasmd: command not found`

My path has `/usr/local/go/bin`

**Comment by ethanfrey** [comment]
Please search the closed issues with the same topic.

This is an error in your local Go setup

**Comment by alpereira7** [comment]
> Please search the closed issues with the same topic.
> 
> This is an error in your local Go setup

Thanks for closing my topic without even giving me a chance to expand.

Research with similar topic returned no relevant results.

Go seems to be properly installed:
    go version
returns
    go version go1.18.1 linux/amd64

**Comment by Baeri3000** [comment]
@ethanfrey Please link the closed issue with the same topic.
I have exactly the same problem and can not find the closed issue.
Thank you

**Comment by alpereira7** [comment]
> @ethanfrey Please link the closed issue with the same topic. I have exactly the same problem and can not find the closed issue. Thank you

Thanks for your support.
I was helped by **Alex | CosmWasm** in Discord.

I checked that `~/go/bin` contained `wasmd` executable.
    > ls -la ~/go/bin/
    
Then I noticed that that directory wasn't in my `$PATH`
    > $PATH
    
Finally, add the directory to the $PATH:
    export PATH="$HOME/go/bin:$PATH"
    
Check
    wasmd version

**Comment by ethanfrey** [comment]
I searched again and could not find. Odd... I know I have seen this several times on some GitHub repo.

Anyway, the answer is to run this:

```
export PATH="$HOME/go/bin:$PATH"
``` 

You should also add that line to `~/.zshrc` or `~/.bashrc` so it runs on every shell.
