### ISSUE TITLE
Sending tokens failed

### ISSUE THREAD

**Issue by alpereira7** [CosmWasm/wasmd#830]
Hello, I'm following this tutorial:
https://docs.cosmwasm.com/docs/1.0/getting-started/setting-env/#setup-go-cli

I enter the command
    `JSON=$(jq -n --arg addr $(wasmd keys show -a wallet) '{"denom":"upebble","address":$addr}') && curl -X POST --header "Content-Type: application/json" --data "$JSON" https://faucet.cliffnet.cosmwasm.com`/credit

It returns
    `Sending tokens failed`

**Comment by alpe** [comment]
The faucet is down on cliffnet. You may get faster feedback or help on our [discord](https://chat.cosmwasm.com/)
