### ISSUE TITLE
Update instantiate config command

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#843]
There is currently no message/ command to modify the instantiate settings on code info except for gov (#796).
This functionality should be limited to the [`creator`](https://github.com/CosmWasm/wasmd/blob/v0.27.0-junity.0/proto/cosmwasm/wasm/v1/types.proto#L61) who uploaded the code initially.

This can be achieved by adding a new method to the [`AuthorizationPolicy`](https://github.com/CosmWasm/wasmd/blob/main/x/wasm/keeper/authz_policy.go) and calling it in the `keeper.setAccessConfig`.
Also the change rules in #840 need to be taken into account

**Comment by ethanfrey** [comment]
If we do this, it should only be the actor who can instantiate the code, not the `creator`.

Basically, allowing someone with that ability to transfer it or share it

**Comment by ethanfrey** [comment]
Removing this from v0.29 milestone as not urgent and needing more discussion first

**Comment by ethanfrey** [comment]
Adding to v0.31.0 as part of the UX around permissioning.
