### ISSUE TITLE
Remove unused flag in gov proposals

### ISSUE THREAD

**Issue by jhernandezb** [CosmWasm/wasmd#849]
`flagProposalType` is being set in all gov proposals but only used in the sdk for the main `submit-proposal` command https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/x/gov/client/cli/parse.go#L13 

We should consider removing it if it's not actually used. 

Context: https://github.com/CosmWasm/wasmd/pull/796#discussion_r868125317

**Comment by alpe** [comment]
I remember that this was used when reading a json file for the gov proposal, once. But this may not be the case anymore 🤷

**Comment by ethanfrey** [comment]
Adding it to v0.28.0.

If this is possible without breaking the json import, let's do it. If not, let's just leave it as is (and close as "wont fix")
