### ISSUE TITLE
how to integrate the wasmd module to our blockchain?

### ISSUE THREAD

**Issue by aramakam3505** [CosmWasm/wasmd#865]
I have built a small private network(3 nodes) using cosmos sdk. Now I want to integrate wasmd module to this blockchain. Can I get any doc to do that??

I have found this link but i feel this is outdated.
https://www.notion.so/Smart-contracts-with-CosmWasm-c6fbcd584b78437a843e738b922dc108

Can I get any resources to complete the above task?

**Comment by alpe** [comment]
You can find some doc in https://github.com/CosmWasm/wasmd/blob/main/INTEGRATION.md#integrating-wasmd
This is not a trivial task. You may get help on our [discord](https://chat.cosmwasm.com/) as well.
