### ISSUE TITLE
Should we expose Keepers in app.go?

### ISSUE THREAD

**Issue by faddat** [CosmWasm/wasmd#881]
Currently, in app.go we do like:

app.bankKeeper

the most common practice is to do like:

app.BankKeeper

Should we change the way that CosmWasm presents these?

**Comment by ethanfrey** [comment]
This is a good question.

I have seen both Juno and Osmosis (big users of CosmWasm) do this, and standardising would be nice for compatibility and porting diffs to app.go easier.

I am not sure the reason to make it private? App is only available in the cmd files and the test code. All modules cannot see it, so making these members public doesn't have a security issue wrt importing modules. Not sure if there is something else I am missing.

If there is no good reason to keep them private, I agree with making them public to be more compatible.

**Comment by faddat** [comment]
I felt approximately the same way about this, and it seems that it mainly boils down to the keepers.

#882 brings wasmd much closer in line with practices on Juno and Osmosis.  

It is my hope that in the next month or so, Juno becomes a reference implementation of wasmd of sorts, and these changes would make moving work between the two projects much easier.  

Thanks @ethanfrey @webmaster128 and @alpe -- working on and with CosmWasm has been an unexpected joy.

**Comment by faddat** [comment]
Interestingly, this is throwing a gocritic linter error:

https://app.circleci.com/pipelines/github/CosmWasm/wasmd/2161/workflows/fcbace1f-bdff-40ba-bc71-67b2fbce270d/jobs/7302

To me that complicates the situation somewhat:  I often slavishly follow linters to ensure that we have convention:

https://github.com/cosmos/ibc-go/pull/1418

I guess that the right way here might be to remove gocritic, or to disable that, because as I mention here:

https://github.com/cosmos/ibc-go/pull/1418#issuecomment-1145203991

I began work on this over at Osmosis, and would like to eventually end up with a linting standard that we can use throughout the ecosystem.

**Comment by alpe** [comment]
I was commenting on the PR https://github.com/CosmWasm/wasmd/pull/882#issuecomment-1145954036  but have not had time to look into the code. Let's continue the conversation here.

> Interestingly, this is throwing a gocritic linter error:

I guess some unintended refactoring issue. This is fine in the main branch. 😅
