### ISSUE TITLE
v0.27.0 has broken simulations

### ISSUE THREAD

**Issue by Anmol1696** [CosmWasm/wasmd#887]
The simulations seemed to have been fixed recently after the #870 PR, which is not part of the last release tag. Would it be a good idea to create a release tag (v0.27.1) with the fixed simulation (as well as some other updates) if needed.

From my perspective, v0.27.0 is broken, since simulations does not work, hence adding it to testing is not possible.

**Comment by alpe** [comment]
Thanks for reporting this! Yes, the simulation "operations" are broken in v0.27.0. I had discovered it later when the tag was set already.

Please note that there were no "operations" before and the module was not really contributing to simulations beside some minimal genesis data.. As a quickfix, would it work for you to drop the module from the [simulation manger](https://github.com/CosmWasm/wasmd/blob/v0.27.0/app/app.go#L706)? You would not be loosing much and we could spend our time and effort on the next regular release instead.

**Comment by Anmol1696** [comment]
Thanks for the response.

I think it is not actually blocking, since the fix is already in the commits, the quick fix i went for was to pull the wasmd version with the commit instead of the tag.

I would still like to keep the simulations, since I am hoping over time the sims get more robust and people are able to test moving forward.
