### ISSUE TITLE
Upgrade to cosmos-sdk 0.46

### ISSUE THREAD

**Issue by yihuang** [CosmWasm/wasmd#927]
- [x] [Upgrade to Go v1.18](https://github.com/CosmWasm/wasmd/issues/815)
- [ ] Upgrade to cosmos-sdk 0.46

**Comment by ethanfrey** [comment]
I think Go v1.18 is good to go now (this has been tested on some other chains).

We don't want to move to sdk v0.46 until this has been battle tested by some chains.
I'm happy if there is an "common fork" using this that a few chains can try out, but with past experience, we wait for other chains to debug new sdk issues before updating.

**Comment by yihuang** [comment]
Is it ok to submit a long pending PR for this? other chains can use as well, we can test on our own fork.

**Comment by SpicyLemon** [comment]
> We don't want to move to sdk v0.46 until this has been battle tested by some chains.

My chain can't update to v0.46 until there's a `wasmd` that uses it too. Cosmos-SDK v0.46 removed some things that wasmd references, so `go mod tidy` throws errors like this:
```
github.com/provenance-io/provenance/app imports
	github.com/CosmWasm/wasmd/x/wasm imports
	github.com/CosmWasm/wasmd/x/wasm/client/rest imports
	github.com/cosmos/cosmos-sdk/types/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.0), but does not contain package github.com/cosmos/cosmos-sdk/types/rest
github.com/provenance-io/provenance/app imports
	github.com/CosmWasm/wasmd/x/wasm imports
	github.com/CosmWasm/wasmd/x/wasm/client/rest imports
	github.com/cosmos/cosmos-sdk/x/gov/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.0), but does not contain package github.com/cosmos/cosmos-sdk/x/gov/client/rest
github.com/provenance-io/provenance/internal/provwasm imports
	github.com/CosmWasm/wasmd/x/wasm/types tested by
	github.com/CosmWasm/wasmd/x/wasm/types.test imports
	github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx: module github.com/cosmos/cosmos-sdk@latest found (v0.46.0), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/legacy/legacytx
github.com/provenance-io/provenance/app imports
	github.com/CosmWasm/wasmd/x/wasm/keeper tested by
	github.com/CosmWasm/wasmd/x/wasm/keeper.test imports
	github.com/CosmWasm/wasmd/app imports
	github.com/cosmos/cosmos-sdk/x/auth/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.0), but does not contain package github.com/cosmos/cosmos-sdk/x/auth/client/rest
```
The rest stuff was completely removed, and `/x/auth/legacy/legacytx` was moved to `/x/auth/migrations/legacytx`.

**Comment by ethanfrey** [comment]
I am more and more skeptical of whether we even use the v0.46.0 release from the cosmos-sdk. See https://github.com/CosmWasm/wasmd/issues/941

**Comment by kevinroleke** [comment]
Is there a fork of wasmd that is currently working with sdk 0.46.1? This is needed

**Comment by vuong177** [comment]
@kevinroleke you can try : https://github.com/notional-labs/wasmd/tree/fifth-46

**Comment by aidan-calculated** [comment]
What is the current status of the 0.46 upgrade? The chain our protocol is developing on requires this upgrade in order to process some Authz messages using the legacy amino format.

I'm just trying to guage vague timelines, and what I can do to help move this along (if anything)

Thanks!

**Comment by ethanfrey** [comment]
We have decided to not do a 0.46 upgrade, but rather upgrade to 0.47 directly (which is like 0.46 with a bunch of cleanup, removing some sources of non-determinism that cause CosmWasm trouble, etc)

That depends on the release and testing cycle of 0.47. Ideally around the end of the year we should have wasmd with 0.47, but we don't control all the dependencies, so no promises there. It may well be January.

**Comment by ethanfrey** [comment]
Closing this as we will be going with 0.47 https://github.com/CosmWasm/wasmd/issues/1028

I think this could be much closer if they trim down the size. Seems like some large epics that are barely started that are blocking release. Happy for other views and comments here: https://github.com/cosmos/cosmos-sdk/issues/13456#issuecomment-1303288541

We still plan to go straight to 0.47. Just hope it is sooner rather than later.
