### ISSUE TITLE
Transaction index in Env is always None

### ISSUE THREAD

**Issue by ninkisa** [CosmWasm/wasmd#932]
Hi,
 
I am trying to get information about the current transaction from an execute message with env.transaction.index on our local chain, but it always returns None. 
The custom AnteHandler is set with wasmkeeper.NewCountTXDecorator (same as here: https://github.com/CosmWasm/wasmd/pull/621#discussion_r716545585), but still env.transaction is None

Reproduced it with local wasmd node and against the Malaga testnet and the demo nameservice contract from https://github.com/InterWasm/cw-contracts 
Steps to reproduce:
- In the demo namespace conctract add to ExecuteMsg::Register action 
```
let tx_idx = env.transaction.expect("No transaction"); 
Ok(Response::default().add_attribute("idx", tx_idx.index.to_string()))`
```
- Call the demo contract with 
```
REGISTER='{"register":{"name":"fred"}}' 
wasmd tx wasm execute $CONTRACT "$REGISTER" --amount 100umlg --from wallet $TXFLAG -y
```
env.transaction is None and code will panic

wasmd version 0.27.0
cosmwasm version 1.0.0

Any help will be appreciated!
Best regards,
Nina

**Comment by ethanfrey** [comment]
I have added it to the next milestone to investigate.

If you can make a (failing) Go testcase as a PR, that would raise this up in priority, but in any case, it should be in the next release

**Comment by alpe** [comment]
I can confirm this issue. When I was debugging the env is serialized into : 
```
{
  "block": {
    "height": 61,
    "time": "1661435276327602000",
    "chain_id": "testing"
  },
  "contract": {
    "address": "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
  },
  "transaction_info": {
    "index": 0
  }
}
```
in the [VM execute](https://github.com/CosmWasm/wasmvm/blob/main/lib.go#L178).
Also see [Go env](https://github.com/CosmWasm/wasmvm/blob/main/types/env.go#L13)

As I understand the [Rust Env](https://github.com/CosmWasm/cosmwasm/blob/main/packages/std/src/types.rs#L14) type, it expects the transaction_info to be nested in a "transaction" element

**Comment by webmaster128** [comment]
In the Rust type, the field is called `transaction` and the type is `TransactionInfo`. The `Option` is serialized as `null` or the object. So it should look like this:

```
  "transaction": {
    "index": 0
  }
```

or


```
  "transaction": null
```

The `json:"transaction_info,omitempty"` part in wasmvm seems like a bug to me.

**Comment by webmaster128** [comment]
This is now tracked in https://github.com/CosmWasm/wasmvm/issues/341, which is the repo that contains the bug. Feel free to close here. There issue will disapear with any wasmd containing wasmvm 1.1.0+.

**Comment by webmaster128** [comment]
Patch is here: https://github.com/CosmWasm/wasmvm/pull/345

**Comment by alpe** [comment]
I would keep this open if there is a chance to write an end to end test for this. Do we have an example contract already, that I can use for this to return the env data to the caller?

**Comment by webmaster128** [comment]
Yeah, test contract "cyberpunk" with MirrorEnv execute and query message is there. Have a look at the Go test in the PR. You can copy it over to this repo but I don't think it would test more than what we test already.

**Comment by alpe** [comment]
The test in wasmvm is fine and covering all that is needed for an end to end scenario. Thanks! 🏄 
All that is left to do is the wasmvm upgrade.
