### ISSUE TITLE
Allow AccessConfig to use a list of addresses instead of just a single address

### ISSUE THREAD

**Issue by sunnya97** [CosmWasm/wasmd#945]
Currently the [AccessConfig](https://github.com/CosmWasm/wasmd/blob/main/proto/cosmwasm/wasm/v1/types.proto#L37) allows for a single address to be given for use with `ACCESS_TYPE_ONLY_ADDRESS`.  However, often times we might want to have a set of addresses be given a certain access control.   For example, in a chain with permissioned code upload, we may want to give a list of trusted actors the ability to upload code without going through the governance process.

We should make a new AccessType called `ACCESS_TYPE_ONLY_ADDRESSES` that allows for a list of addresses instead of just a single one.

We could achieve something like this with authz, but a proper whitelist is cleaner and can be fully controlled by governance rather than the original grantee.

**Comment by ethanfrey** [comment]
I agree with the requirements as a useful, backwards compatible addition for permissioned cosmwasm chains.

I would propose using ACCESS_TYPE_ANY_OF to signify any of the listed addresses can upload code alone. (only addresses could imply any or all must sign)

**Comment by alpe** [comment]
This makes sense for me, too and I actually had this in a very early version once. My question would be: to do this with or without state migration? 
I can easily add another field to the [AccessType](https://github.com/CosmWasm/wasmd/blob/main/proto/cosmwasm/wasm/v1/types.proto#L40] for a set of addresses or modify it to `repeated string` which feels like the cleaner option for state and api.
