### ISSUE TITLE
Upgrade to IBC v4 or v5

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#960]
Tracking issue to upgrade the ibc-go dependency to [ v4 ](https://github.com/cosmos/ibc-go/releases/tag/v4.0.0)

This release contains the fee middleware.

See [migration](https://ibc.cosmos.network/main/migrations/v3-to-v4.html) guide

## Versions currently used
* v3.0 [juno main](https://github.com/CosmosContracts/juno/blob/main/go.mod#L8), [terra](https://github.com/terra-money/core/blob/main/go.mod#L9)
* v3.1 [tgrade main](https://github.com/confio/tgrade/blob/main/go.mod#L9), [stargaze main](https://github.com/public-awesome/stargaze/blob/main/go.mod#L11)
* v3.2 [osmosis main](https://github.com/osmosis-labs/osmosis/blob/main/go.mod#L11)

* v5.0-rc0 [gaia main](https://github.com/cosmos/gaia/blob/main/go.mod#L9)

**Comment by faddat** [comment]
Basically, as far as I understand things:

We will want ibc-go v4 OR ibc-go v3.2.0 for cosmos-sdk v0.45.7 -- there were some changes to support the sped-up DB, is my understanding.  I also noticed a change that related to txCtx.R being included in gentx(

**Comment by the-frey** [comment]
Would vote for v5. Do you have thoughts @jhernandezb ?

**Comment by the-frey** [comment]
What we're seeing on testnets is ICA is causing a huge increase in relayer fees so as long as we're >v4 it's probably okay - nevertheless I agree with @faddat's reasoning that we should roll with v5

**Comment by jhernandezb** [comment]
v5 will require moving to sdk 0.46, do we want to push for an sdk upgrade?

**Comment by the-frey** [comment]
Ah I think (from memory) the notion was that wasmd would go straight to 0.47 when available, so that means v4? or is v4 also predicated on 46?

**Comment by jhernandezb** [comment]
IBC v4 still depends on sdk 0.45 that will make it easier to upgrade 
https://github.com/cosmos/ibc-go/blob/v4.1.0/go.mod#L10

**Comment by the-frey** [comment]
Okay, I think then my vote would be v4 for 0.30.0 in that case.

![image](https://user-images.githubusercontent.com/2385077/194586873-3e8c9945-8314-4bc3-b3cf-c466f30af038.png)

**Comment by faddat** [comment]
Personally I am for version 6 and SDK 46 because we should not whip one another unnecessarily, you see, the dragon and it's berries are so fierce. They have delayed 47, and 46 adds useful stuff to the interchain accounts controller.

**Comment by ethanfrey** [comment]
ibc-go v4.1.1 looks good: https://github.com/cosmos/ibc-go/blob/v4.1.1/go.mod#L10 (not 4.0 per their [RELEASE NOTES](https://github.com/cosmos/ibc-go/releases/tag/v4.0.0))

**Comment by alpe** [comment]
v4.2.0 it is now out https://github.com/cosmos/ibc-go/blob/v4.2.0/CHANGELOG.md
