### ISSUE TITLE
Make StargateMsg in cosmwasm remove all events

### ISSUE THREAD

**Issue by ValarDragon** [CosmWasm/wasmd#962]
Currently the stargate message returns events.

Under the current SDK semantics, this is unfortunately not safe. This is because events are currently:
* Not deterministic (kind of crazy, should be fixed)
* Not state machine versioned (this is an intentional decision, due to serving the purpose of being for data integrators)

The SDK at some point introduced MessageResponses. These were half baked, and never had a clearly communicated purpose. I'd like to advocate, we make these non-half baked, and make them usable for state machine composability works. To be not half-baked:
* Tightly tested in every module
* Have all useful response fields you would expect
* State machine versioned (e.g. integrated into the block hash)
  * Also state machine version field names (with backwards compatability plans made if they need to change)
  * API's made, so its easy to generically get fields from, with correct type. (This could just be typecasting or something)

In Osmosis, we are working towards getting many of the "useful response fields" into our modules, and are aiming to make guarantees around these.

I would like to advocate at the Cosmwasm StargateMsg layer we:
* Remove all events from the response. To retain API compatability can just return sdk.Events{}
  * We _could_ make a whitelist for events similar to what were doing for queries, but I think this is a bit excessive, unless today important contracts are going to be broken. If so, then perhaps for Osmosis we add a blacklist, and blacklist all events?
* Encourage use of Message Response, and fix all existing modules to provide the desired response types.

**Comment by ethanfrey** [comment]
I believe we do this in 0.28

We remove all events from everything except for wasm messages

**Comment by ethanfrey** [comment]
See https://github.com/CosmWasm/wasmd/pull/917

and please let me know if this doesn't solve your issue. It removes even more events

**Comment by ValarDragon** [comment]
Oh amazing, thanks! I believe this does resolve all the issue pointed out!

Awesome work
