### ISSUE TITLE
Possible dependency conflict issue

### ISSUE THREAD

**Issue by faddat** [CosmWasm/wasmd#965]
Copied from DM w/ Alex:

OK so here's the deal the other day I was upgrading the Cosmos had and there were OK the hub has upstream dependencies, the liquidity module and the hub router. And the liquidity module failed with 45.8 set on the hub

so, basically, given that cw has a bunch of downstream users, I think that for v0.29.0 it is way safest to ship as a package like:

```
* v3.2.0 or v4.0.0
* sdk v0.45.8
* tendermint v0.34.21
```

Then, we should be really clear that either cw v3.2.0 or v4.0.0 require a migration.  Here's my specific concern-- lots of chains, and their modules also import ibc-go.  I do not claim to understand every complexity of every piece of the stack perfectly, but instead, I'd say that the guidance for upgrading to v0.29.0 should be like:

"to upgrade to cosmwasm v0.29.0, your chain and its various modules should use at minimum:

* cosmos-sdk v0.45.8
* tendermint v0.34.21
* ibc-go v3.2.0 (or if we choose v4, then v4)
"

Because I am pretty sure that everything will go far more smoothly that way. 

Please feel free to contact me if you want more info on that and... I hate to be so direct-- I am not currently in possession of a "why" although I will say that it may have something to do with -- check test_helpers.go and note how we changed some things there for 45.7+.

This is mainly about downstream safety.

**Comment by alpe** [comment]
Thanks for providing some context!
Let's keep this issue open for some time for others to report issues or comment on this.
Personally, I would prefer to have some chains run ibc-go v3.2 on production before upgrading the dependency.
But ibc-go v3.2 and v3.0 are api compatible, which makes it easy for the chains to decide. The upgrade would be in go.mod #937 and not require touching code.

**Comment by Anmol1696** [comment]
I am also waiting on wasmd to upgrade to ibc v3.2.0. Since they fixed some issues there (although minor). Is the concern here that v3.2 is not tested out enough?

**Comment by faddat** [comment]
Personally I feel safer & happier * such with ibc v4.0.0

### Suggested solution:

write a v4.0.0 patch for wasmd v0.28.0 because seems v0.29.0 will take a hot minute.

**Comment by alpe** [comment]
ibc-go v3.2 is in main now. I will close this now. Let's move discussion about v4 to #940
