### ISSUE TITLE
Remove deprecated AccessConfig.Only

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#986]
Follow up on:
https://github.com/CosmWasm/wasmd/pull/974

- [ ] remove `address` from protobuf
- [ ] remove type
- [ ] provide state migration

**Comment by GNaD13** [comment]
Hi @alpe , Can I take this issue?

**Comment by alpe** [comment]
This is a bit early as v0.30 is not tagged, yet. 
I have set `help wanted` labels to some issues: https://github.com/CosmWasm/wasmd/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 . Some may not be ready to start coding yet but feedback, proposal or spike may be useful for discussion

**Comment by pinosu** [comment]
Closed by #1395
