### ISSUE TITLE
Remove genesis messages

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#987]
[Genesis messages](https://github.com/CosmWasm/wasmd/blob/main/x/wasm/client/cli/genesis_msg.go) are a complex functionality in the code and not easy to main. 
Not sure if it is used by anybody.
- [ ] Remove from CLI
- [ ] Remove from genesis protobuf

**Comment by ethanfrey** [comment]
I would agree with this and only use wasmd genesis to load existing contracts and state (from a state dump) rather than add new contracts. But maybe there are some use cases that need this 🤷 

If we do keep it, I think this needs more testing (also manual testing in production by others)

**Comment by alpe** [comment]
I used them for system tests in tgrade only
