### ISSUE TITLE
Enforce version check on wasm lib

### ISSUE THREAD

**Issue by alpe** [CosmWasm/wasmd#994]
when used used as dynamic lib.
Follow up from https://github.com/CosmWasm/wasmd/pull/988#discussion_r965976607

Would a `make build-linux` target with static compilation be a sufficient solution?

**Comment by jhernandezb** [comment]
The only issue I see is that you can only build static binaries with muslc, which would probably require docker.

**Comment by webmaster128** [comment]
The solution shown in https://github.com/public-awesome/stargaze/blob/2b06ae1cb8518dd19b128b65317da125efb9702d/cmd/starsd/cmd/start.go#L11-L22 is pretty cool. It does not differentiate between static libraries (which can be wrong by not updating the .a file in the builer docker) and shared libraries (which can be wrong when juggling with custom build systems).

I only wonder about this duplication. The line `var LibwasmVersion = "1.0.0"` is something that you should be able to get from the Go dependency management using

```
$ go list -m github.com/CosmWasm/wasmvm | cut -d" " -f2 | cut -d"v" -f2
1.1.1
```

Any idea how to get the build system information into the .go file?

**Comment by jhernandezb** [comment]
You can use build info to get the version 
```
package main

import (
	"fmt"
	"runtime/debug"

	_ "github.com/CosmWasm/wasmd/app"
)

func main() {
	buildInfo, ok := debug.ReadBuildInfo()
	if !ok {
		panic("can't read build info")
	}
	for _, d := range buildInfo.Deps {
		if d.Path != "github.com/CosmWasm/wasmvm" {
			continue
		}
		if d.Replace != nil {
			fmt.Printf("%s@%s => %s@%s\n", d.Path, d.Version, d.Replace.Path, d.Replace.Version)

		}
		fmt.Printf("%s@%s\n", d.Path, d.Version)
	}
}
```
